### ISSUE TITLE
In PHPStan 1.12.0 with bleeding edge generated annotations @method for tables are reported

### ISSUE THREAD

**Issue by Harfusha** [cakephp/bake#1002]
### Description

https://github.com/dereuromark/cakephp-ide-helper/issues/353

`\src\Model\Table\AccountsTable.php:55:Class App\Model\Table\AccountsTable has PHPDoc tag @method for method newEntity() parameter #1 $data with no value type specified in iterable type array.`
`\src\Model\Table\AccountsTable.php:55:Class App\Model\Table\AccountsTable has PHPDoc tag @method for method newEntity() parameter #2 $options with no value type specified in iterable type array.`

This problem is with array type in params and with iterable type in params

`@method \App\Model\Entity\Account newEntity(array $data, array $options = [])`
This should be updated to this
`@method \App\Model\Entity\Account newEntity(array<mixed> $data, array<mixed> $options = [])`

`@method \Cake\Datasource\ResultSetInterface<\App\Model\Entity\Account>|false saveMany(iterable $entities, $options = [])`
This should be updated to this
`@method \Cake\Datasource\ResultSetInterface<\App\Model\Entity\Account>|false saveMany(iterable<mixed> $entities, $options = [])`
Or better to
`@method \Cake\Datasource\ResultSetInterface<\App\Model\Entity\Account>|false saveMany(iterable<\App\Model\Entity\Account> $entities, $options = [])`

PHPStan issue: https://github.com/phpstan/phpstan/issues/11593

Edit more issues found:
`@method \App\Model\Entity\Service[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])`
`C:\Workplace\many\many\src\Controller\ServicesController.php:60:PHPDoc tag @method for method App\Controller\ServicesController::paginate() return type contains generic interface Cake\Datasource\ResultSetInterface but does not specify its types: T`

(Used annotations are changed by dereuromark/cakephp-ide-helper, but the issue is same)

### Bake Version

*

### PHP Version

8.3

**Comment by LordSimal** [comment]
In the meantime you can just use https://github.com/dereuromark/cakephp-ide-helper to automatically generate all the necessary annotations so static analysis is happy.

**Comment by dereuromark** [comment]
Both Bake and IdeHelper are currently not adding `<mixed>` to iterable here.

@Harfusha Do u want to make a PR here?

**Comment by Harfusha** [comment]
And how should i implement it? Should i add <mixed> or the specific entity? I would rather add specific entity.

**Comment by dereuromark** [comment]
As specific as possible, sure.
We can do it here first, and then in parallel also port this to the IdeHelper.

**Comment by dereuromark** [comment]
Do all major IDEs understand/support this new "bleeding edge generated annotations"?
My latest PhpStorm 2024.2.3 Build #PS-242.23339.16, built on September 25, 2024
for example does not yet.

I wonder what issues this could bring for IDE usage (and developers).

For Psalm/PHPStan this update is sure useful.

![Image](https://github.com/user-attachments/assets/c9ba8f05-be9e-4f31-b915-80b850cb6d77)

The red marked errors are `Expected: variable`

**Comment by Harfusha** [comment]
But this annotation was already in use. https://github.com/cakephp/bake/blob/ccb0c78a7706feb9b32ff1a702a246a44fca6090/tests/comparisons/Model/testBakeTableRules.php#L24

Edit:
Or does phpstorm have problem only with this annotation in the functions params?

**Comment by dereuromark** [comment]
Jep. Only input apparently.
You should see if there is an open Bug ticket for phpstorm etc we can plus one. Or if we have to create one.
But maybe we need to make this a Feature flag in IdeHelper then.

**Comment by Harfusha** [comment]
Can you please test if we can use Entity[] instead of itterable<Entity>?

**Comment by dereuromark** [comment]
Yes, so
```
@method \TestApp\Model\Entity\BarBar[] patchEntities(\Cake\Datasource\EntityInterface[] $entities, array $data, array $options = [])
```
seems fine here on bake side, and rest could probably be on IdeHelper side.

**Comment by Harfusha** [comment]
Ok i will update it this way :)

**Comment by Harfusha** [comment]
Oh but itterable<> and Entity[] is not same, i dont know if this change is wise. I will revert it back to itterable

**Comment by dereuromark** [comment]
The main point is that any EntityInterface collection is accepted right? So `EntityInterface[]` kind of makes sense as an expression of a collection.
Just iterable is not saying too much I guess.

But sure, either way works.

**Comment by Harfusha** [comment]
But when entities are fetched only using ->all() i will show errors, and you cannot set it to be array of entites, because that will mean that you cannot use any functions of the iterable like ->isEmpty(

**Comment by dereuromark** [comment]
It more and more sounds like we shouldnt touch the Bake templates and rather make it all an opt-in topic for IdeHelper.
We could revisit this in like a year if IDEs caught up by then.

**Comment by Harfusha** [comment]
Yeah, only change i made in the end was array => mixed[] :D

**Comment by beporter** [comment]
This is no longer "bleeding edge", btw. I'm getting the OP's noted errors on phpstan "stable" with the current cakephp/app create-project files. So all new `composer create-project cakephp/app` execution is resulting in phpstan failures now.

It might be time to update the bake templates.
