### ISSUE TITLE
Bake `--force` option is broken

### ISSUE THREAD

**Issue by lorenzo** [cakephp/bake#110]
It does not even show in the help text for bake

**Comment by antograssiot** [comment]
@lorenzo In wich way is it broken ? i used it successfully with almost every command.
I have a PR ready to add the option to the help text but I can look into it with more information

**Comment by lorenzo** [comment]
It is broken as it does not work with `cake bake all users -f` for example

**Comment by markstory** [comment]
The all command is missing the `force` option. Other tasks have it though.

**Comment by markstory** [comment]
I think my pull request solves this.
