### ISSUE TITLE
cakephp3.0: (Enhancement)In baked view.ctp, Related models  should  have pagination and column sorting

### ISSUE THREAD

**Issue by ib-anurag-mishra** [cakephp/bake#116]
cakephp3.0: In baked view.ctp, Related models  should  have pagination and column sorting

**Comment by markstory** [comment]
I feel that attempting to paginate N models at once is a bit outside of the scope of what bake is trying to accomplish. However, you can probably use custom templates to do what you want.

**Comment by jhli** [comment]
I think this would greatly impove rad / oob functionality bit possibly requires changes to the paginator.

**Comment by jhli** [comment]
I think this would greatly impove rad / oob functionality bit possibly requires changes to the paginator.

**Comment by markstory** [comment]
It would also require the generated view methods to be more complex.

**Comment by anuid28** [comment]
it would be great job in bake if this functionality get done

**Comment by josegonzalez** [comment]
We can now paginate multiple models so this is technically possible :)

**Comment by thinkingmedia** [comment]
Let's not add scaffolding features to the bake plugin. This would be better added as bake templates for the http://github.com/friendsofcake/crud-view project.

**Comment by htstudios** [comment]
It is not really scafgolding. The current related bake output can either be huge or is limited to x (= 200) records. Pagination would get rid of that and only leave select options as something that needs to be addressed @ max records

**Comment by dereuromark** [comment]
I agree that this is a bit out of scope of this plugin probably.
We might have to dig into the crud ones - this is not something that will land in this one for quite some time.
Closing as stale.
