### ISSUE TITLE
Support DB prefixes when baking code

### ISSUE THREAD

**Issue by burzum** [cakephp/bake#119]
**Use Case:**

I'm in the situation that I finally need to apply https://github.com/cakephp/cakephp/issues/4118 because of a legacy app. When I want to bake my code for the old DB that uses a prefix, how can I tell bake and cake to use that prefix? I don't want to end up with everything in my app being prefix by `ho_`?

**Proposed solution:**

The way I see it for this situation is this: Let's modify bake to support `--db-prefix`. `--db-prefix` will make bake aware to use the prefix, for example my `ho_`. But bake won't use it in the generated code then. Bake will create the table() call with the prefix then but ignore it everywhere else. Sounds fine?

**Comment by dereuromark** [comment]
I always just use my DbMaintenance Shell to remove the prefixes from the tables I plan on upgrading. Then afterwards it is as they never were prefixed, problem solved.

**Comment by burzum** [comment]
But I'll have to keep it in this case.

**Comment by dereuromark** [comment]
I guess then it sounds fine to add this to the table() statement.

**Comment by lorenzo** [comment]
I think having this is a good idea, @burzum do you want to implement it?

**Comment by burzum** [comment]
Maybe, if I find the time and mood, I'll be busy for the next ~12 days.

I worked around my issue for now by removing the prefix in the SQL dump, via search and replace, importing the DB, baked everything and then used the unaltered dump.

Also I did this:

```php
trait DbPrefixTrait {

	protected $_dbPrefix = '';

	/**
	 * Getter and setter for the DB prefix
	 */
	public function dbPrefix($prefix = '') {
		if (!empty($prefix)) {
			$this->_dbPrefix = $prefix;
		}
		return $this->_dbPrefix;
	}

	/**
	 * Returns the database table name or sets a new one
	 *
	 * @param string|null $table the new table name
	 * @return string
	 */
	public function table($table = null) {
		if (!empty($table)) {
			$table = $this->_dbPrefix . $table;
		}
		return parent::table($table);
	}
}

class AppTable extends Table {

	use DbPrefixTrait;

	public function initialize(array $config) {
		$this->dbPrefix('ho_');
		parent::initialize($config);
	}
}
```

**Comment by ionas** [comment]
Didn't you do some work on this @burzum?

I do like ```--table-name``` much better as it allows arbitrary table names to be specified - either your prefixes or whatever you like.

This makes it easy to create a model layer that has meaningful class table names and point it to some sql table that has a legacy name (or a plugin prefix, or otherwise some prefix). Now that I took a look at how low level cake bake association detection works, that might break quite a few things!

**RFC:** Maybe a simple optional yaml/ini/json/xml/php file which maps tables for cake bake would work?
```json
{
"wp_articles_new" : "articles",
"users_plugin_users" : "users"
}
```
The format (JSON) aside, is that a good concept?

**Comment by josegonzalez** [comment]
You can probably set that info via a bake event. No extra format needed.

**Comment by ionas** [comment]
The problem is when you run a CLI bake command like ```"bake all posts --table-name 'wp_posts'"``` and later on ```"bake all posts --table-name 'wp_comments'"``` how should the association detection across table aliases work, then? Is that clear? Do I miss something?

**Comment by josegonzalez** [comment]
Gotcha. That's an interesting problem, I *think* you can still set the variables for the view properly (since all of the assocs are calculated in the task, not in the view) though it would be annoying.

**Comment by ionas** [comment]
But the task does fetch possible association tables via querying the database/schema directly and thus won't "know" about wp_posts: id, created, modified, title, author_id, body and wp_comments: id, created, modified, author_id, body being associated at all. There is also some messy stuff about what the conventions should then do and if there should be foreign key aliases as well *urgh*.

**Comment by ionas** [comment]
* This is an extended example of prepareing a legacy database schema for cakephp conventions utilized by bake.
* This whole file is NOT mandatory but a way to teach bake to respect non-conventional table names, primary keys and foreign key names.
* RFC: Could all these cases be treated by real-sql foreign keys? Do all our supported adapters support real-sql foreign keys (sqlite?)
* XML is not a must, but it is very clear what's going on. JSON could also be used / XML allows validation prior to parsing, which is good here!
```xml
<tables-bake-configuration>
    <table>
        <name>wp_authors</name>
        <alias>users</name>
        <primaryKey>
            <name>uid</name>
            <alias>id</alias>
        </primaryKey>
    </table>
    <table>
        <name>wp_posts</name>
        <alias>posts</name>
        <primaryKey>
            <name>pid</name>
            <alias>id</alias>
        </primaryKey>
        <foreignKey>
            <name>authors_id</name>
            <alias>user_id</alias>
        </foreignKey>
    </table>
    <table>
        <name>wp_comments</name>
        <alias>comments</name>
        <primaryKey>
            <name>cid</name>
            <alias>id</alias>
        </primaryKey>
        <foreignKey>
            <name>authors_id</name>
            <alias>user_id</alias>
        </foreignKey>
        <foreignKey>
            <name>pid</name>
            <alias>post_id</alias>
        </foreignKey>
    </table>
    <table>
        <name>wp_posts_ratings</name>
        <alias>post_ratings</name>
        <!-- Composite Primary Key Example -->
        <primaryKey>
            <name>pid</name>
            <alias>post_id</alias>
        </primaryKey>
        <primaryKey>
            <name>authors_id</name>
            <alias>user_id</alias>
        </primaryKey>
        <foreignKey>
            <name>pid</name>
            <alias>post_id</alias>
        </foreignKey>
        <foreignKey>
            <name>authors_id</name>
            <alias>user_id</alias>
        </foreignKey>
    </table>
</tables-bake-configuration>

**Comment by dereuromark** [comment]
Is this still interesting to have? Or shall we close?

**Comment by burzum** [comment]
Yes

**Comment by dereuromark** [comment]
Can be partially achieved using table property when baking. Seems sufficient for now.
