### ISSUE TITLE
Table::initialize() is not calling parent in baked table classes

### ISSUE THREAD

**Issue by burzum** [cakephp/bake#120]
The title says it all.

Check the discussion here https://github.com/FriendsOfCake/bootstrap-ui/issues/63

**Comment by AD7six** [comment]
What the title does not say is in what way that's a problem - the parent class method [is empty](https://github.com/cakephp/cakephp/blob/master/src/ORM/Table.php#L304-L324)

**Comment by burzum** [comment]
@AD7six today it's empty, what if it changes? What if I extend my custom Table object like AppTable?

But feel free to close it if you disagree.

**Comment by dereuromark** [comment]
I don't think it would hurt to add the parent call - for consistency at least.

**Comment by AD7six** [comment]
> what if it changes? 

I don't think that's likely.

I also don't think a parent call would hurt but there was no clarification as to whether it's a problem or other.
