### ISSUE TITLE
3.1: PHP Fatal error:  Class 'Cake\Mailer\Email' not found in /path/to/my-app/config/bootstrap.php on line 138

### ISSUE THREAD

**Issue by mtkocak** [cakephp/bake#128]
I am not sure if this is the right place for this but, I installed app using command:

    composer create-project --prefer-source cakephp/app my-app 3.1.x-dev

When I try to run cake bake on app root directory;

    bin/cake bake all

happens this:

    $ bin/cake bake all
    PHP Fatal error:  Class 'Cake\Mailer\Email' not found in /path/to/my-app/config/bootstrap.php on line 138
    PHP Stack trace:
    PHP   1. {main}() /path/to/my-app/bin/cake.php:0
    PHP   2. include() /path/to/my-app/bin/cake.php:31

    Fatal error: Class 'Cake\Mailer\Email' not found in /path/to/my-app/config/bootstrap.php on line 138

    Call Stack:
        0.0004     229728   1. {main}() /path/to/my-app/bin/cake.php:0
        0.0025     269088   2. include('/path/to/my-app/config/bootstrap.php') /path/to/my-app/bin/cake.php:31

Is this a bug? Or did I make an error? Thanks...

**Comment by AD7six** [comment]
This is the wrong repo

The 3.1 cakephp/app branch [requires 3.0](https://github.com/cakephp/app/blob/3.1/composer.json#L9) - so it's out of sync when created in that way since the app expects 3.1 source (Cake\Mailer\Email) but has 3.0 source (Cake\Network\Email\Email).

**Comment by mtkocak** [comment]
@AD7six Can you check https://github.com/cakephp/bake/issues/129 I think that is same problem due to not-updated css file?

**Comment by mtkocak** [comment]
###Question (sorry for that)
How can I install 3.1 version to see new layout?

**Comment by mtkocak** [comment]
ok

**Comment by AD7six** [comment]
`cd vendor cakephp/cakephp; git checkout origin/3.1` or similar. probably the app's composer file should be updated so it just works.

**Comment by mtkocak** [comment]
thank you so much. I will try.
