### ISSUE TITLE
1.1: Layout Problem

### ISSUE THREAD

**Issue by mtkocak** [cakephp/bake#129]
Header and Body is not aligned as seen here.

![screen shot 2015-06-26 at 10 21 39](https://cloud.githubusercontent.com/assets/545472/8373455/44386af6-1bed-11e5-888f-c3acd097e32a.png)

**Comment by mtkocak** [comment]
https://github.com/cakephp/app/blob/3.1/src/Template/Layout/default.ctp

here the layout has

    <ul class="title-area large-3 medium-4 colmuns">

makes this problem, but I don't know if they have any link. :P

**Comment by markstory** [comment]
Could we default to ratios that will work _most_ of the time. It doesn't have to be 100% correct all the time, but more than zero would be great.

**Comment by mtkocak** [comment]
just they has to be aligned only. not more.

2015-06-26 18:35 GMT+02:00 Mark Story <notifications@github.com>:

**Comment by markstory** [comment]
Looks like you need to re-bake your view. That view is also missing the action bar highlight. It should look like.
![screen shot 2015-08-19 at 22 36 34](https://cloud.githubusercontent.com/assets/24086/9374321/c756371a-46c2-11e5-98c7-2d3bf536989f.png)

**Comment by mtkocak** [comment]
That's perfect
20 Ağu 2015 04:36 tarihinde "Mark Story" <notifications@github.com> yazdı:
