### ISSUE TITLE
Adding joinType LEFT for nullable foreign keys

### ISSUE THREAD

**Issue by GuidoHendriks** [cakephp/bake#135]
When baking models currently there's no `joinType` added. For non-nullable fields that's good, since it's always good to inner join those. For nullable foreign keys on the other hand, it will not return any records if there are no associated.

My suggestion is adding a `'joinType' => 'LEFT',` if the foreign key field is nullable.

I'm willing to implement it myself if you guys agree on this.

**Comment by lorenzo** [comment]
I think this is the way it currently works. If that is not the case, I'd be happy to accept your pull request :)

**Comment by GuidoHendriks** [comment]
Sorry, I was wrong. It already works this way! :+1:
