### ISSUE TITLE
Baking a Fixture With Field Types of UUID Results in Empty Values in the Fixture Records

### ISSUE THREAD

**Issue by jtyost2** [cakephp/bake#136]
As an example this table:

```sql
CREATE TABLE `generic_joins` (
  `id` char(36) NOT NULL COMMENT 'UUID',
  `foreign_id` char(36) NOT NULL DEFAULT '',
  `created` datetime DEFAULT NULL,
  `creator_id` char(36) DEFAULT NULL,
  `modified` datetime DEFAULT NULL ,
  `modifier_id` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Running the normal bake command:

```bash
$ ./bin/cake bake fixture GenericJoins
```

Generates this file: https://gist.github.com/jtyost2/c164dfbf898d18d05918

Which generates sample records that lack a populated entry for uuid fields.

This can be seen that they are indeed correctly registered as a `uuid` field type in the `$fields` property: https://gist.github.com/jtyost2/c164dfbf898d18d05918#file-genericjoinsfixture-php-L20 and that the field in the records are set as empty strings: https://gist.github.com/jtyost2/c164dfbf898d18d05918#file-genericjoinsfixture-php-L43 .

I think this is caused due to the `FixtureTask` not understanding how to process fields of type `uuid`: https://github.com/cakephp/bake/blob/master/src/Shell/Task/FixtureTask.php#L329

**Comment by ADmad** [comment]
@jtyost2 You just need to make a pull request for the commit on your fork :)

**Comment by jtyost2** [comment]
Thanks @ADmad PR just issued from my fork.

**Comment by dereuromark** [comment]
PR is now open ( https://github.com/cakephp/bake/pull/137 ).
