### ISSUE TITLE
Insert properties in the entity with 'bake model'

### ISSUE THREAD

**Issue by gsmit1996** [cakephp/bake#145]
Currently 'bake model' exports the following code snippet:

    /**
     * User Entity.
     */
    class User extends Entity
    {

My request was to add the fields of the table in the PhpDoc.

     /**
     * User Entity.
     * @property $username
     * @property $password
     */
    class User extends Entity
    {

If this is implemented IDE's know that the property exists.

**Comment by markstory** [comment]
Would you be able to do a pull request for the templates bake uses?

**Comment by jadb** [comment]
Could this also be made optional and off by default? Sometimes schemas get updated and some of us might prefer not including the fields in the docblock and have an outdated list over time.

**Comment by josegonzalez** [comment]
@jadb I would prefer it not be optional. If you dont want them, delete them or make your own template.

**Comment by jadb** [comment]
Well accessible fields and other baked stuff are made optional, why not this? Maybe you meant include them by default and use a flag to not have them generated? Like it's done for hidden, accessible..?

**Comment by gsmit1996** [comment]
I've created the pull request: https://github.com/cakephp/bake/pull/147
Since I don't use Github that often I don't know how to add it to this issue, sorry for that. :disappointed_relieved:

**Comment by Oxicode** [comment]
Y si se crea otro método para actualizar esos fieles?

**Comment by ADmad** [comment]
Closing as related PR is open.
