### ISSUE TITLE
Fixture default should be one demo record

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#146]
When running `cake bake model ...` it also creates the fixture with 1 demo entry.
After running again `cake bake fixture ...` at some later time it suddenly creates 10 records.

It should also default to 1 here for consistency until told otherwise.
The diff becomes huge without reason and we still only need a single record to do basic find operations for testing etc. No need for these huge demo fixture arrays defined.

**Comment by markstory** [comment]
When calling FixtureTask through the CLI, the `count` option gets defaulted to 10, which is where the 10 generated records are coming from. Perhaps the default value should be 1 instead?

**Comment by dereuromark** [comment]
I vote for that, yes.

**Comment by markstory** [comment]
ok.

**Comment by markstory** [comment]
Pull request up.
