### ISSUE TITLE
Template baking with Tree behavior should omit lft/rght fields in form

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#155]
The lft/right fields in forms should not be displayed as the TreeBehavior manages them on its own.
When baking a model, the Tree behavior is automatically attached.
I would expect the view to also detect the desired tree behavior, or that the Tree behavior is attached, and then skips those two fields from being displayed.

Currently they show and will likely destroy the tree on submit.

It would also be useful to skip those fields for index, as they bear no meaning here, either.

**Comment by markstory** [comment]
Pull request up now.
