### ISSUE TITLE
Baking templates for custom method does not inflect method name for template name

### ISSUE THREAD

**Issue by djamesfar** [cakephp/bake#156]
Cake 3.0.12  If I create a new method for a controller and include it in my theme plugin (Plugin/Template/Bake/Element/Controller), and the method name is in the appropriate camelCase, TemplateTask::_methodsToBake() will not inflect the method name so that it can get the view template in Plugin/Template/Bake/Template.

Example:  I've added a new controller method called addComment(), and added it's template as an element in my Plugin theme.  Baking the controller creates the method correctly in the newly baked controller.
I've also added the accompanying view template, which by Cake conventions should be tableized or under_scored to add_comment.ctp, and placed it in Plugin/Template/Bake/Template/.

However, after baking the controller with it's new method, baking the Template will not find the associated template, add_comment.ctp.  
The reason is in TemplateTask::_methodsToBake() (around line 229), the methods array is created by  array_map'ping the controller methods to 'strtolower', which simply lower-cases them.  This is used to eliminate dupes from AppController methods.
The reason it doesn't show up as a problem in most cases, I'm sure, is because the provided methods are all single-word lowercased anyway and no inflection is required (index, add, edit, view, delete).

The solution, I think, is to simply replace the array_map'ped 'strtolower' function with '\Cake\Utility\Inflector::underscore'.  The array_diff will still work because you're translating all methods so duplicates in AppController are still eliminated.
And the returned array of methods has eg. 'add_comment' instead of 'addcomment', and the appropriate template template is found in the theme plugin.

**Comment by markstory** [comment]
Pull request up now.
