### ISSUE TITLE
Discuss: Bake fixtures using Faker?

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#162]
**Proposal**
To include the [Faker](https://packagist.org/packages/fzaninotto/faker) library so that when bake generates fixture data it's data is a little more intuitive to the user. Plus when generating multiple records in the fixture all the data isn't the same.

**Why not a PR?**
I'm interested in people's thoughts on the introduction of a dependency to Bake. 

**Existing tools**
https://github.com/gourmet/faker

**Comment by josegonzalez** [comment]
How would we define types for a given field? What if a user wants to persist those types? What does a programmatic interface look like? Are we still going to support the old methods of generating fixture data?

**Comment by markstory** [comment]
> Are we still going to support the old methods of generating fixture data?

We would have to at least until 4.x

**Comment by davidyell** [comment]
> How would we define types for a given field?

As I understand it Faker generates data to match your schema column type, so you don't have to define them.

> What if a user wants to persist generated field types with modifications?

I don't understand what this means.

> What does a programmatic interface look like?

```php
$populator->addEntity('Users', 100, [
            'email' => function () use ($faker) { return $faker->safeEmail(); },
            'first_name' => function () use ($faker) { return $faker->firstName(); },
            'last_name' => function () use ($faker) { return $faker->lastName(); },
            'timezone' => function () use ($faker) { return $faker->timezone(); },
            'role' => function () use ($roles) { return $roles[array_rand($roles)]; }
        ] + $timestamp);

// And an example from a seeding migration I have
        $populator->addEntity('Providers', 10, [
                'name' => function () use ($faker) { return $faker->sentence(4); },
                'slug' => function () use ($faker) { return \Cake\Utility\Inflector::slug($faker->sentence(4)); },
                'logo' => function () use ($faker) { return basename($faker->image()); },
                'logo_dir' => function () use ($faker) { return $faker->sha1(); },
                'status_id' => function () use ($faker) { return $faker->numberBetween(1, 4); }
            ] + $timestamp);
```
By being specific with these fields in this manner you can control what data is used, but if you omit a field Faker will generate it for you automatically.

Ref: https://github.com/gourmet/faker#migration - using https://github.com/fzaninotto/faker

**Comment by davidyell** [comment]
Is it worth me looking into developing a PR for this?

**Comment by josegonzalez** [comment]
:+1:

**Comment by davidyell** [comment]
This ticket is redundant now as since Phinx `0.5.0` seeding is now included in Phinx.

http://docs.phinx.org/en/latest/seeding.html
