### ISSUE TITLE
Cake 3 missing controller error in plugin after baking plugin

### ISSUE THREAD

**Issue by AD7six** [cakephp/bake#166]
_From @ashu1459 on October 14, 2015 6:48_

Platform: Windows 7 64-bit
Browser: chrome

When I try to bake a plugin in small case, it gives and error of missing controller while accessing that plugin.
For eg: 
I made a plugin named 'api' using the command 'cake bake plugin api'.
It created plugin folder with the name 'Api'(camel case) and created the namespaces with name 'api'(all small case) such as "namespace api\Controller;" and "use api\Controller\AppController;".
When I tried accessing the plugin it gave me an error of missing controller inside plugin.

What I did to fix it was to change the namespace declaration to "namespace Api\Controller;" and its use to "use Api\Controller\AppController;"(notice a capital A in Api). Then it worked fine!!.

I think the bug lies where the the directory name is created as camel case and namespace created as small case. Of course I intentionally baked it in small case.

Please fix this issue.
Thanks

_Copied from original issue: cakephp/cakephp#7544_

**Comment by ADmad** [comment]
Plugin names are supposed to be CamelCased so you should use `cake bake plugin Api`. But i guess bake could inflecte the plugin name to avoid this problem.

**Comment by AD7six** [comment]
>  I intentionally baked it in small case.

@ashu1459 - why's that?

**Comment by ashu1459** [comment]
@AD7six 
Because I wanted to see if the namespaces and Folder naming conventions matches or not. But it didn't. According to me. Either it should give error in command line or maybe it should create the namespaces with the same name as the plugin directory which is CamelCase.

**Comment by AD7six** [comment]
I see, I wondered if you _wanted_ a lower case plugin and namespace to come out of bake.

**Comment by markstory** [comment]
I wasn't able to reproduce the incorrectly generated namespace name:

```
$ bin/cake bake plugin api

Welcome to CakePHP v3.1.1 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 5.5.27
---------------------------------------------------------------
Plugin Name: Api
Plugin Directory: /Users/markstory/Sites/cakephp-app/plugins/Api
---------------------------------------------------------------
Look okay? (y/n/q)
[y] > y
Generating README.md file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/Api/README.md
Wrote `/Users/markstory/Sites/cakephp-app/plugins/Api/README.md`
Generating composer.json file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/Api/composer.json
Wrote `/Users/markstory/Sites/cakephp-app/plugins/Api/composer.json`
Generating config/routes.php file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/Api/config/routes.php
Wrote `/Users/markstory/Sites/cakephp-app/plugins/Api/config/routes.php`
Generating phpunit.xml.dist file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/Api/phpunit.xml.dist
Wrote `/Users/markstory/Sites/cakephp-app/plugins/Api/phpunit.xml.dist`
Generating src/Controller/AppController.php file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/Api/src/Controller/AppController.php
Wrote `/Users/markstory/Sites/cakephp-app/plugins/Api/src/Controller/AppController.php`
Generating tests/bootstrap.php file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/Api/tests/bootstrap.php
Wrote `/Users/markstory/Sites/cakephp-app/plugins/Api/tests/bootstrap.php`
Generating webroot/empty file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/Api/webroot/empty
Wrote `/Users/markstory/Sites/cakephp-app/plugins/Api/webroot/empty`
Modifying composer autoloader

File `/Users/markstory/Sites/cakephp-app/composer.json` exists
Do you want to overwrite? (y/n/a/q)
[n] > n
Skip `/Users/markstory/Sites/cakephp-app/composer.json`



/Users/markstory/Sites/cakephp-app/config/bootstrap.php modified
---------------------------------------------------------------
Created: Api in /Users/markstory/Sites/cakephp-app/plugins/Api

:) 22:15:34 markstory:cakephp-app (master)
$ cat plugins/Api/src/Controller/AppController.php
<?php

namespace Api\Controller;

use App\Controller\AppController as BaseController;

class AppController extends BaseController
{

}
```

Did you run any other bake commands? I know that `bin/cake bake controller -p api Things` will trust that you provided the correct plugin name, as there are cases where one might want an unconventionally named plugin and I'd like to accommodate those scenarios.

**Comment by ashu1459** [comment]
This works fine for the AppController created during plugin bake but fails for further controllers inside that plugin when I do "cake bake controller api.maps"
The MapsController has "namespace api\Controller;" and "use api\Controller\AppController;"
If I do "cake bake controller Api.maps", then its fine.

**Comment by markstory** [comment]
Ok, You need to do `Api.Maps`. We need to allow lowercase plugin names so, you'll just have to be careful.
