### ISSUE TITLE
error finding table when name contains number

### ISSUE THREAD

**Issue by chipco** [cakephp/bake#175]
I have a table called `user_actions_2`. Running `bake model UserActions2` or `bake model user_actions_2` or `bake model all` results in an error:

```
Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.user_actions2' doesn't exist
```

**Comment by markstory** [comment]
You will have to use the `--table` option to specify the table name as your table doesn't match the typical conventions.
