### ISSUE TITLE
Baking with nested prefixes not working correctly

### ISSUE THREAD

**Issue by ndm2** [cakephp/bake#177]
Using nested prefixes will fail/create unexpected results depending on the prefix format.

Using a format like `pre/fix` will result in a namespace like `Pre/fix` with a matching folder structure, ie a `Pre` folder containing `fix` folder.

Using a format like `pref\fix` ends up with a valid namespace separator, however this may fail on *nix systems unless `\` is being replaced with a valid directory separator somewhere.

Not time for a PR currently, but I can give it a try in the next few days in case no one else is going to take care of it in the mean time.

**Comment by markstory** [comment]
I can take a look.

**Comment by markstory** [comment]
Pull requests up now.
