### ISSUE TITLE
Question about how `cake plugin assets symlink` works.

### ISSUE THREAD

**Issue by LACabeza** [cakephp/bake#179]
I have in my bootstrap.php:
```php
// Only try to load DebugKit in development mode
// Debug Kit should not be installed on a production system
if ( Configure::read( 'debug' ) ) {
     Plugin::load( 'DebugKit' );
}
```
The 'debug' variable is true, and when I run `cake plugin assets symlink DebugKit`, it returns that *Plugin DebugKit is not loaded.*. To get this working, i need to remove the `if Configure::read( 'debug' )`.

Is this right?

**Comment by ADmad** [comment]
Yes the plugin has to be loaded in order to be recognized by the shell.

That said symlinking plugin assets into webroot is meant to improve performance in production and since debugkit is a development tool not meant to be used in production symlinking it's assets isn't really necessary.

**Comment by ADmad** [comment]
In future for help requests please use stackoverflow.com or `#cakephp` channel IRC not this issues tracker.
