### ISSUE TITLE
RFC: "Bake cannot generate associations for composite primary keys at this time"

### ISSUE THREAD

**Issue by ionas** [cakephp/bake#183]
Is this somewhere on the agenda already?

**Comment by markstory** [comment]
#180 is a pull request that has a similar title/contents.

**Comment by ionas** [comment]
Info: That other pr #180  does only fix controller/template related bake things so that navigating a bake result will not break horribly if composite primary keys are encountered.

**Comment by dereuromark** [comment]
Dup of https://github.com/cakephp/bake/issues/197
