### ISSUE TITLE
Coding standards for cake bake templates

### ISSUE THREAD

**Issue by ionas** [cakephp/bake#185]
I'd like to suggest that we do in future stick to either:
- Standard language constructs, e.g. `if() {}`, `foreach() {}`.
- Alternative language constructs, e.g. `foreach () : endforeach` `if(): endif`.
- Either generally to one of those or per domain (view template template vs controller template vs controller action template vs entity template vs table template) or at least per file (tbd).

**Suggestion**
Personally I'd like to see one of the "ways" of constructs to be used for baking level only and one for the generated code. If seen that way maybe it makes sense to:
- Use alternative language constructs for anything but view template templates to generate standard language constructs
- Use standard language constructs for view template templates to generate alternative language constructs.

**Related**
- There should be a coding standard for indentation in all (Entity, Table, Controller, Template) bake files e.g. not the results.
- There should be a coding standard for indentation of generated bake results for view templates, e.g. the results.
- Spacing and semicolons. I like to see a lot of spacing, e.g. `<?= $this->Html->link(); ?>` better than `<?=$this->Html->link();?>` as this improves readability, but I like to see tailing semicolons omitted, e.g. `<?= $this->Html->link() ?>` better than `<?= $this->Html->link(); ?>` as this does not help with readability in view template templates (most crowded files).

**Comment by markstory** [comment]
I think this is mostly an issue of time and priorities. If you have time and feel its important please charge ahead. We have existing coding standards, and reusing those as much as possible seems like a win to me.

**Comment by ionas** [comment]
:+1: Thought so. But first if I find time I ll supply test to the bake composite key issue. Then I ll take a look and try to make things consistent.
What about the generated result. Is regular syntax for anything but view template results AND alternative syntax for view template results okay?

**Comment by markstory** [comment]
I think using whatever makes it easy to separate the templates/output is reasonable.

**Comment by dereuromark** [comment]
Sounds to me like the one place where twig would really make sense.

**Comment by simkimsia** [comment]
My (somewhat related) question is 

1. how do you even test the coding standards of the baked templates? another codesniffer?
2. is there a testcase for the baked actions?

**Comment by AD7six** [comment]
> Personally I'd like to see one of the "ways" of constructs to be used for baking level only and one for the generated code.

:-1: 

For reference, standard constructs are used [for php classes](https://github.com/cakephp/bake/blob/master/tests/comparisons/Controller/testBakeActions.php#L70) and  in view templates it depends on whether using standard constructs would mean [hopping in and out of php tags](https://github.com/cakephp/bake/blob/master/tests/comparisons/Template/testBakeIndex.ctp#L24) - it is not imo a good idea to arbitrarily decide to use one or the other for output and the other for template logic - the factor there is php tags (`<?`) or tempalte tags (`<%`)

We already [run phpcs against test comparison files](https://github.com/cakephp/bake/blob/master/.travis.yml#L45) - i.e. we are already verifying bake output matches the code standard.

**Comment by dereuromark** [comment]
So RFC for CakePHP4:
Please let's use twig or better yet liquid, for both there are also cake plugins then (e.g. https://github.com/gourmet/liquid ).
The advantages are clear:
- No undocumented pseudo-language
- IDE syntax help with those popular templating engines (using plugins?) super helpful
- Those that are already using templating engines don't have to re-adjust, everone else will easily learn the will documented engine more easily than the currently used one.

Did I miss anything?

For me this is way more important than a few spaces or coding standards.
But I wouldn't mind if we got a little bit better documented and organized here at some point, too : )

**Comment by ionas** [comment]
I am torn on adding another dependency and making bake templates more complex than it is.
PHP is already "THE" templating language*.

So I with @AD7six's custom template tags *for now*, but I do think that we should specify not only <?= vs <%= but also that for anything but to use the inverse control structures style compare to what the result should be. For Tables, Entities, Controllers (and Views) this would be alternate control structure style in the meta templates. For the view templates it would depend on what we desire the output to be, standard style or alternate style? The alternate style allows to stay in a PHP tag, so I am not totally following there.

Btw. one could do whatever with their own templates. It is about the out of the box templates and conventions.

* (now if there was a Kernel:: space for all the global functions and a way to opt in a certain set of functions of that Kernel space and classes/methods of other namespaces, one could almost really USE it as a end user template language).

**Comment by dereuromark** [comment]
PHP is not a templating engine, but you are missing the point.
We are NOT using PHP for templating, it is some pseudo code asp tag thing.

**Comment by ionas** [comment]
Thanks for being so kind and leaving it to me to discover if I miss the point. PHP is one of the strongest templating languages, next to not being only that.

As far as I understood the pseudo-PHP tags are rewritten to PHP tags in an internal cache so in essence, we are doubling up on PHP templating.

Don't get me wrong, I do like twig and especially liquid (which I touched in my Ruby days): https://github.com/Shopify/liquid/wiki - my vote counts little and if you can convince @AD7six @markstory and then start implementing based on liquid/gourmet I will :clap: x :100: - I am just unsure if its worth adding another technology/layer because it increases complexity and dependencies.

**Comment by dereuromark** [comment]
Bake is an optional plugin with a independent with pretty much independent development from the main framework. I wouldn't wry about that too much, just as Migrations uses phinx internally, or any of those other optional plugins.
I would wry about maintainability and usability in itself, and if you put all together maybe the decision can be made easier in what direction to go.
Right now it does not seem too much fun to work with.

And internal caching I also don't care much about. Speed is not an issue for development baking, the usability and customization options very much are, though.

**Comment by simkimsia** [comment]
> Right now it does not seem too much fun to work with.

Agree

>the usability and customization options very much are, though.

Agree

If there are ways to increase the usability and customization options without using liquid or twig, I am also for it.

Right now the usability and customization options are not really quite there yet.

**Comment by dereuromark** [comment]
It seems, there is only Twig support yet for PHPStorm.
For Liquid etc there is still an open ticket: https://plugins.jetbrains.com/wishlist/show?pr=&wid=404

**Comment by ionas** [comment]
As for speed: It should not be much slower than now. I am at times baking 150 files concatenated in bash calls. That takes only a few seconds and should not change (by much).

As for Liquid, one editor is no reason to base a decision on. Aside stability, support and learning curve I am concerned about how hard it is to map cakephp helpers, cakephp basic functions and specific cakephp global functions.

**Comment by dereuromark** [comment]
That is to be found out. But right now, one has to learn this custom asp tag thing, which is not even documented, and as such it can only be easier to learn an open source template engine.
But sure, we will have to investigate how custom functions and CO can be built with those.

**Comment by markstory** [comment]
If we're going to use a template system, twig gets my vote. It has a significant adoption outside of CakePHP and is a well maintained library.

**Comment by dereuromark** [comment]
@markstory And since it is a dev only tool and will never be deployed to servers, it is also not a big deal if the license is not MIT.

**Comment by markstory** [comment]
Twig is BSD, which roughly the same as MIT.

**Comment by HavokInspiration** [comment]
As for using a template engine, I'm really in favor of it. I've been writing the bake template for migrations diff this week-end and it is really not pleasant to work with when you are writing "big" files.

I agree with Twig as well : if we are going to adopt a dependency, it might as well be one that has a bigger community and a good adoption outside of "our scope".

**Comment by dereuromark** [comment]
@HavokInspiration For me the killer feature is still the IDE support (My files are red underlined from the top to the bottom, and doing all kind of wonky things because of that^^). Code-highlighting and Auto-complete would be only two of the many benefits.

**Comment by HavokInspiration** [comment]
IDE support would be a nice side-effect indeed even though I think (re-)usability and readability is the priority since not everyone is using the same IDE.

And yeah, PHPStorm is imploding within bake template. Funny thing is when you copy paste from another bake template and it tries to auto-indent...

**Comment by dereuromark** [comment]
Yes, the auto-indent is already quite annoying.

**Comment by markstory** [comment]
Does anyone want to take a pass at updating the current templates to use Twig? I think we will need to keep the current template renderer as well for backwards compatibility.

**Comment by AD7six** [comment]
I don't understand the desire to use twig/liquid - but I also don't have the time/energy for the debate either. If someone want's to change bake to use twig/liquid instead just to have IDE support (instead of e.g. just changing bake template's file extensions to not be php) I'm fine with that.

**Comment by jhli** [comment]
In case this is done :+1: @markstory for keeping the old way for quite some time.

**Comment by markstory** [comment]
@AD7six Part of the desire comes from IDE's mishandling the current templates, the other comes from a few subtle issues related to the current template syntax.

**Comment by dereuromark** [comment]
You can see the [Spryker code generator](https://github.com/spryker/code-generator) use twig templates, they make it very easy to read and write the code IMO
- [example](https://github.com/spryker/code-generator/blob/master/templates/Client/Client.php.twig)

Maybe we could adapt sth like that for the next generation of this plugin?

**Comment by dereuromark** [comment]
Closing as the main point left here has been extracted to a follow up issue.
