### ISSUE TITLE
'limit' => 200 for select dropdowns

### ISSUE THREAD

**Issue by ionas** [cakephp/bake#186]
Is there any sane reason that that's in the bake templates by default?

**Comment by josegonzalez** [comment]
Probably so you don't explode your database?

**Comment by ionas** [comment]
When I get to adding test cases to the composite primary key support I'd like to remove that.

1. I removed it and it returns 5800 now (in this case manufacturers). The HTML file is like 275kbyte (ignoring GZip) and it loaded in a snap. DebugKit reports 3.5MB RAM usage. The query took ~50msec to run (not fast but not a problem either).
2. If you run into these kinds of problems you will have to change how a assoc record is selected ground up. If you don't then you don't need a limit.

**Comment by markstory** [comment]
I think the intent here was to not select unbounded sets as that can lead to issues like @josegonzalez mentioned.

**Comment by AD7six** [comment]
>  I could not say what a sane limit is, 200 for sure is not

The reason it's added is that that data is used by default in a standard html select.

If you have e.g. Foos belongsTo Users - and you have a million users - even if that worked a select with a million options is completely unusable, 200 is an arbitrary (but IMO reasonable) maximum for the standard use case for that code. Also in this circumstance this would mean the code bake generates immediately fails running out of memory or succeeds but is rediculously slow; It can be confusing to developers who just bake and load the foos index and are greeted with a 500 after 30s. Wheras if you really want more than 200 items, it's trivial to either remove in the baked code or use a different template set which doesn't have that limit by default.

You've alluded to your own usage in the comment but frankly a select with 5800 options is ridiculous, unless (which bake doesn't provide by default) there's some sort of auto complete also.
 
:-1: to removing the limit or increasing it.

**Comment by lorenzo** [comment]
The limit was added by me from personal experience. People tend to not think of the consequences of thousands of records in a select list, there will be a moment in which the amount of records will either exhaust the memory of php or the patience of the user waiting for the DOM to load. The limit is there so that people think of that possible case.

If they think it is not a problem for them, they can just delete that part. Or maybe they will think of not loading all results there and use ajax?

**Comment by ionas** [comment]
I was wondering if data was missing in my database due to the baked code and checked it quite at a few places because I am importing data. The issue then was with the bake result, unexpected.
* The select-widget does allow type-a-head in many browsers (Firefox, Chrome at least) - just TAB into the widget and start typing.
* Autocomplete can easily be added by Chosen (JS) or similar - not perfect either but good enough for a quick and completely working RAD interface. It can be applied easy and unobtrusively, but not without changing the bake templates first.
* A developer is free to add these limits himself per action or inside the template.
* A developer not thinking about this will also have issues figuring out why the drop-down is not showing all his records.
* For a RAD interface that should not get into your way it is good enough a sane limit of 10.000 should be enough.
* What do you think of a bake option to make this configurable (I'd then setup a PR for that) and what should be the default limit?

**Comment by lorenzo** [comment]
@ionas an option that probably no one will ever use, but I would not oppose having it

**Comment by ionas** [comment]
:+1: Great. That's a good compromise. When adding I'd also update the book about it.

**Comment by dereuromark** [comment]
Maybe raising it to a 1000 would be good compromise. Everything beyond that sure is crazy, but if you have 300 records and you are cut off by half of them, that might be annoying as you need to refactor the code because of that prior to have the possibility to select the record you are looking for.
And a 1000 does not do too bad impact just yet.

**Comment by AD7six** [comment]
200 is already "you should be nowhere near that" territory - it's a limit set to protect users from creating silly queries/user interfaces without consciously deciding to be do so/fix it.

if a select is so many options that it doesn't fit on the screen:

![screen shot 2015-11-28 at 17 11 35](https://cloud.githubusercontent.com/assets/33387/11452764/206e1762-95f3-11e5-9979-b39ac2c88390.png)

Or worse on mobile:

![screenshot_2015-11-28-17-15-23](https://cloud.githubusercontent.com/assets/33387/11452794/e5cd5f40-95f3-11e5-97da-4e9b51653a7e.png)

The choice is not really appropriate to be a select. I am :-1: on raising the limit and :-1: on making a snowflake option to configure the limit also - it's an option which as jose says no one is likely to use.

**Comment by dereuromark** [comment]
The problem I see is that using bake and rapid development there is no way to customize all those out-of-the-box find(list) calls when baking the crud templates. 
At the beginning it also totally suffices. But over time the record count increases and than it suddenly starts to be cut-off unexpectedly.

**Comment by dereuromark** [comment]
Actually, i still maintain some 2.x sides that over time got crud templates with "user_id" find(list) selects and 2000-4000 entries. And it works. Just fine.
So if I ever upgraded those sites to 3.x all that code in the backend would just not work anymore.

**Comment by ADmad** [comment]
I vote for the new limit to be 42.

**Comment by dereuromark** [comment]
@ADmad Please dont make this a joke.
It is a fair criticism that needs proper discussion, not nonsense sarcasm. 

I do think 1000 would be better as it is a good balance between security and usability. 
But everyone can just create his/her own bake template. So maybe we really don't have to do anything here.

**Comment by josegonzalez** [comment]
I'm :-1: on changing the default but :+1: on allowing people to configure it - even if just by a bake event.

Having worked on admin panels for a long time, I'm siding with @AD7six here. I think an autocomplete form would be *much* more appropriate here, but given that bake doesn't generate that, this is the next best bet.

**Comment by markstory** [comment]
> The problem I see is that using bake and rapid development there is no way to customize all those out-of-the-box find(list) calls when baking the crud templates. 

Wouldn't customizing the templates work? Either way if a pull request for controller task is made that to add a length option, I think that might be a way to keep a reasonable default and allow people to enable larger limits if they need them.

**Comment by ionas** [comment]
By the way, following the same reason one would want to restrict associated tables loaded.

In both cases the missing key is pagination/searching/filtering. I just got a 37mb return by upping RAM/Cycles on the machine on related table information. Should be the same flag for ease, limiting both of these.

**Comment by lorenzo** [comment]
@ionas where?

**Comment by ionas** [comment]
view related tables.

**Comment by lorenzo** [comment]
@ionas that makes sense to me

**Comment by simkimsia** [comment]
@josegonzalez said

I'm :-1: on changing the default but :+1: on allowing people to configure it - even if just by a bake event.

Having worked on admin panels for a long time, I'm siding with @AD7six here. I think an autocomplete form would be much more appropriate here, but given that bake doesn't generate that, this is the next best bet.

I agree. With one addition. There should be an documentation about how to extend the bake template.

**Comment by ionas** [comment]
See the other issue @simkimsia

**Comment by tivotyro** [comment]
I get that there should be a limit, and I am can see the argument to leave it at 200.  But how do you override it?  I just corrupted a huge database because I didn't see that a dropdown was defaulting to the first entry.  That's on me, and luckily I can roll back, but I do need to resolve the problem.

**Comment by dereuromark** [comment]
I would have preferred at least 1000. Anything below is silly in a CRUD app, any DB can easily handle it, and better than having it cut off and unusable for normal sized relations/tables.
An alternative would be to make it configurable.

Anyway, I guess we have to close this then.
