### ISSUE TITLE
EOL configuration

### ISSUE THREAD

**Issue by chipco** [cakephp/bake#187]
Is there any way to configure the EOL used in the baked files?

I'm running bake on windows and all generated files use `\r\n` but I want to get them with `\n`.

**Comment by AD7six** [comment]
Assuming you use version control with your app, you shouldn't need to care too much about that e.g. https://help.github.com/articles/dealing-with-line-endings/

**Comment by ADmad** [comment]
How do the baked files have `\r\n` when the bake templates use `\n`?

**Comment by chipco** [comment]
It's probably caused by Cake View renderLayout. I'm using custom templates saved with \n.

**Comment by chipco** [comment]
After some testing I found the line endings are replaced by `$data = $File->prepare($contents);` in `Cake\Console\Shell -> createFile($path, $contents) `

I guess there's nothing to be done in bake as long as the function `createFile` is used.

**Comment by ADmad** [comment]
Hmm [File::preprare()](http://api.cakephp.org/3.1/class-Cake.Filesystem.File.html#_prepare) uses windows line ending only if second param is `true` and it's default value is `false`. The call in `Shell::createFile()` doesn't pass second param so it should return content with *nix endings.

**Comment by ADmad** [comment]
Err I misread the code, you are right. Closing as the issue lies with `File::prepare()`. It will always use `\r\n` on windows.
