### ISSUE TITLE
Cake bake fixture generates wrong import property

### ISSUE THREAD

**Issue by wvdongen** [cakephp/bake#192]
Example: generating a fixture for the companies table: 
<code>bin/cake bake fixture companies --schema --import-records</code>

Results in a fixture with:
<code>public $import = ['model' => 'Companies', 'records' => true];</code>

According to https://github.com/cakephp/cakephp/blob/master/src/TestSuite/Fixture/TestFixture.php#L67 

Both array keys ‘model’ and ‘records’ do not seem to be used by cake. The ‘model’ key should be ‘table’ and there doesn’t seem to be support for importing records.

**Comment by markstory** [comment]
Your right! I'll get that fixed.

**Comment by markstory** [comment]
Pull request.
