### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by AD7six** [cakephp/bake#2]
From https://github.com/cakephp/cakephp/issues/5319, here's a list of things that aught to be done before a stable release:

 - [x] Convert to a plugin
 - [x] PSR2
 - [ ] Allow baking anything
 - [ ] Restructure to be not tasks, but event based
 - [x] Normalize view/template terminology
 - [x] Baking a plugin should point at a template folder (in a bake theme probably) and recursively render files
 - [ ] Rewrite/improve templates, using helper methods elements etc.

**Comment by davidyell** [comment]
:+1: For event driven bake

**Comment by josegonzalez** [comment]
@AD7six can this be closed?
