### ISSUE TITLE
1.1.2 bake all with --prefix tries to create table class in prefix path - fine in 1.1.1

### ISSUE THREAD

**Issue by ionas** [cakephp/bake#202]
For details see: https://gist.github.com/ionas/90324d5e48a9c935853f
Not sure but this could be the issue: https://github.com/cakephp/bake/commit/214b2f13309f760f5cd6b9d502bd2437f7a9cd87#diff-0c9ca9e63bf919df5c6c12bcbc430ecfR108

Edit: Fixed the gist link showing the bug

**Comment by markstory** [comment]
I can take a look.

**Comment by markstory** [comment]
Pull request up now.

**Comment by ionas** [comment]
I thank you very much.
