### ISSUE TITLE
HasMany detection vs HABTM detection

### ISSUE THREAD

**Issue by ionas** [cakephp/bake#204]
From ```ModelTask.php```
```php
            // Exclude habtm join tables.
            $pattern = '/_' . preg_quote($tableName, '/') . '|' . preg_quote($tableName, '/') . '_/';
            $possibleJoinTable = preg_match($pattern, $otherTable);
            if ($possibleJoinTable) {
                continue;
            }
```
Now for me associations were missing between ```suppliers``` and ```managed_suppliers``` - somehow (and I don't know why or how) those associations indeed were detected correctly, *before* (e.g. on cake 3.1.4 and some corresponding bake).

I looked through bake 1.0.14 to 1.1.2 and it is always the same above. ```managed_suppliers``` is not being checked as a possible HasMany assocation because the matching removes it, as it considers it a possible join table.

Do I remember correctly that at least for 2.x the convention for HABTM join tables was:

1. both parts plural (e.g. ```groups_users```, not ```grouped_users```)
2. both tables actually have to exist (e.g. ```groups``` and ```users```)
3. alphabetically sorted (e.g. ```groups_users``` not ```users_groups```)

Is this correct? Not anymore for 3.x?

Trying to auto detect hasMany assocations with bake on ```suppliers``` and ```managed_suppliers``` should fail on convention 1 and convention 2 (3 would be correct, theoretically, if it was ```manages_suppliers```).

**Comment by ionas** [comment]
Ref: http://book.cakephp.org/3.0/en/intro/conventions.html#model-and-database-conventions
> Join tables, used in BelongsToMany relationships between models, should be named after the model tables they will join, arranged in alphabetical order (apples_zebras rather than zebras_apples).

**Comment by ionas** [comment]
SQL: https://gist.github.com/ionas/94558dc1fd30ed614b3d

**Comment by ionas** [comment]
This is especially troublesome when combined with prefixes.
prefix_products and products will try to setup a HABTM even if you intend to just extend products (hasMany/hasOne) by a plugin for instance.

**Comment by ionas** [comment]
**Question:** Would a PR be welcome that checks if both tables actually exists? E.g. `managed_sets` would be treated as a HABTM in the HasMany detection part but only under the circumstance that `managed` and `sets` both actually exist as tables?

A better solution would be to also check if both sides are actually plural (but possibly harder).

Last but not least why not keep HasMany ALONGSIDE HABTM as HABTM is always also HM/BT <> BT/HM?

**Comment by ceeram** [comment]
Hasmany and having unique constraint on supplier_id in managed_suppliers table?

**Comment by jhli** [comment]
I did remove the unique constraint (effective HasOne); same issue.

**Comment by jhli** [comment]
Also note: It is not detected as HABTM just the HasMany detection fails

**Comment by markstory** [comment]
I've not checked but I think the conventions around has many/belongs to many haven't changed between 2.x and 3.x. At least they haven't intentionally been changed.

Checking for the target table for belongs to many relations would help better identify has many/belongs to many I think.

**Comment by ionas** [comment]
Is ```/^table_|_table$/``` (see: https://regex101.com/r/oX8iG1/2) a good enough regexp for line: https://github.com/cakephp/bake/blob/master/src/Shell/Task/ModelTask.php#L327?

**Comment by markstory** [comment]
@ionas That does look like an improvement to the regex.

**Comment by ionas** [comment]
What should we do about non-alphabetical ordering of HABTM join tables. Not enforcing those during bake time allows developers to be sloppy. Enforcing them now possibly breaks some bake setups.

*Test if alphabetical ordering is wrong and deprecate to be changed for a bake release to be released for 4.0?*

**Comment by lorenzo** [comment]
I prefer not enforcing it

**Comment by josegonzalez** [comment]
You could warn the users but continue on :)

**Comment by ionas** [comment]
I prefer to either remove the convention (e.g. allow both orders) or warn the user (DEPRECATE) and at some point in future enforce it. A convention that is not required by the framework is nothing good.

**Comment by josegonzalez** [comment]
Yep that looks good.

**Comment by ionas** [comment]
PR was up and got merged.
Same for the docs update.
Closing.
