### ISSUE TITLE
Adding traits to baked classes

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/bake#205]
One thing I've started doing is letting bake handle almost everything automated - behavior/component initilization etc. - and then adding custom code into traits that can then be included in my classes. By doing so, I can set a `trait` to use for a baked class and add custom code there, allowing me to rebake files later without losing customizations.

Thoughts on adding this to bake? I think it could be useful in both entities and tables, though less useful for controllers.

**Comment by lorenzo** [comment]
Not a crazy idea, the main problem I see is that multiple traits cannot implement the initialize() method

**Comment by josegonzalez** [comment]
Yeah, the initialize method would still do what it normally does, and you can configure all the stuff you need in there for the most part.

I'm thinking of this as more of a way to move my custom finds/validation rules etc. to another place that doesn't get overridden by bake.

**Comment by lorenzo** [comment]
ah ok, that makes sense to me. Would validators be in a trait for example?

**Comment by josegonzalez** [comment]
Yeah so I imagine we *could* move `validationDefault` into a trait - and it would be great to offer this as an option.

Right now I've modified my bake template to not include extra methods and then just added the `validationDefault` and `buildRules` methods to a `App\Model\Table\Traits\UsersTrait` trait.

**Comment by jhli** [comment]
I am solving a similar problem by having a FooLogic, BarLogic etc classes and getting tables there, adding custom finders etc. It also allows non table business logic to have its place. It does miss things like extended validators that are respected by Calls made to table and entity objects in controller context, thus a I'd love a cleaner solution for extending model bake results, possibly this one.

**Comment by davidyell** [comment]
I assume this would be a kind of '--trait=SavantTrait` type of command line option?

**Comment by josegonzalez** [comment]
Comma-separated of course, so you can add multiple :)

**Comment by dereuromark** [comment]
Looks like we could probably close this 3+ year old one as not too relevant. If someone still wants to implement it sure, but lets focus on the actual issues first.

**Comment by josegonzalez** [comment]
I'll work on it this weekend.

**Comment by dereuromark** [comment]
Closing until a PR can be produced.
