### ISSUE TITLE
bake template users index

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/bake#215]
Hi all,

maybe dumb question, but why is always connection required when using bake for template?

Let's assume I create own bake theme for some templates and want to use them even without connection.

Example I have Users controller with index action, but no model for users and when I run ```bake template users index``` it throws connection error

Thanks

**Comment by ionas** [comment]
Because it gets its fields from the database instead of the entity, AFAIK.

**Comment by LubosRemplik** [comment]
I mean why are fields/schema/connection required, in some case you just want to bake simple mix of HTML&PHP code, something like ```bake/src/Template/Bake/Template/login.ctp```

**Comment by ionas** [comment]
My 2 cents: Because it is KISS (keep it stupid simple). If you can find a simple solution to differentiate if a database/schema is required or not, a PR is then probably welcome.

**Comment by markstory** [comment]
@LubosRemplik Without a connection we cannot reflect the schema which is generally useful/required for generating code.

Closing as this is a question.
