### ISSUE TITLE
bake Model, set hidden fields, bake template/form

### ISSUE THREAD

**Issue by smarek** [cakephp/bake#218]
Hello

is it possible to bake template/form after editing properties of Model (Table/Entity), to exclude some fields in index/view/edit actions ?

I've tried baking model, modifying `$_accessible` var and/or editing `$_hidden` var, and baking template+form after that, but it didn't work

**Comment by markstory** [comment]
Yes. But you will need to use custom bake templates. Perhaps in the future someone can contribute an option that allows the fields to be limited.

**Comment by smarek** [comment]
That's actually good point, is there please any documentation on how to provide custom bake templates? I'd love to provide mine, if I can start off current ones

**Comment by ionas** [comment]
Check the book. If it is not in there, mimic this:
https://github.com/davidyell/CakePHP-NiceAdminBakeScripts
If that helped you out, please consider contributing back to the book/docs.

**Comment by smarek** [comment]
Thanks, also is there anything about BakeView syntax please, such as `<%=` ? It's breaking my Intellij IDEA php validation, so it's hard for me to work with that

**Comment by ionas** [comment]
@smarek While there is at least one bug with that, I believe, it is a lot easier and less error prone to work that way meta-programming PHP templates than having to quote/escape every time. Consider contacting Intellij IDE developers and/or ask around in #cakephp in freenode IRC.

**Comment by davidyell** [comment]
Not sure if it's related, but I fixed hiddenFields in entities a while ago.

https://github.com/cakephp/bake/pull/213

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/cakephp/bake/issues/222
