### ISSUE TITLE
Neither view template nor form element (add, edit) are handling hasOne relations

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/bake#219]
It seems that the view template it trying to show them the same way as belongsTo relation, which is ok, but it ignores it when filtering with map function. BelongsTo and hasOne relations are mixed together into $immediateAssociations array, then this array is filtered checking if the [foreingKey exists as a field](https://github.com/cakephp/bake/blob/master/src/Template/Bake/Template/view.ctp#L22), which is true for belongsTo associations but not for hasOne: 

```php
$immediateAssociations = $associations['BelongsTo'] + $associations['HasOne'];
// ...
$associationFields = collection($fields)
    ->map(function($field) use ($immediateAssociations) {
        foreach ($immediateAssociations as $alias => $details) {
            if ($field === $details['foreignKey']) {
                return [$field => $details];
            }
        }
    })
    ->filter()
    ->reduce(function($fields, $value) {
        return $fields + $value;
    }, []);
```

As for the form template, used on add and edit, there is no clue of hasOne relations. Is it on purpose?

In the meantime I'm working to see if I can fix view template.

**Comment by markstory** [comment]
I don't think its on _purpose_. Most likely its an oversight that was introduced during a refactoring. If you're fixing the templates for your application, a pull request would be appreciated :smile:

**Comment by xavier83ar** [comment]
Ok, working on it. It's my first time doing it, so I'm reading contributing guidelines and such things.

**Comment by xavier83ar** [comment]
Well, I think I did understand the bake's tests structure. As far as I see there is no test case for hasOne relations. 

At first I got confused a bit because on the folder for the espected baked templates results there is a testBakeIndex.ctp file, a testBakeEdit.ctp and a testBakeView.ctp, but the last one is never used, also this file is outdated after the new templates introduced by @midorikocak, even I've deleted this file and all tests are still passed.
Instead I've found a testBakeTemplate.ctp file which is used by testBakeTemplate method to test view.ctp results. 

I think that this should be changed, in my opinion using testBakeView as file name and method name is far more representative of what this test case actually does. However the presence of this file (testBakeView) outdated makes me think that this was like this on the past and gets changed to testBakeTemplate, I can't guess why.  What do you think?

In the meantime I keep working on add some test case for hasOne relations and fixing the issue.

**Comment by xavier83ar** [comment]
I see that view template was renamed [here](https://github.com/xavier83ar/bake/commit/cf0b42122273db7944ac141701ede242c98758a5) when renaming views as templates. I guess it was done by mistake, because particulary there "view" wasn't refering to "view" as template instead to the view template... it's a pun, I guess that such things confirm that renaming views for template was ok, now we can be clear about the view template, instead of talking of the view view.. :stuck_out_tongue_closed_eyes:.
So, what do you think on getting back to "view" this particular case? as it's refering to the view template.

**Comment by markstory** [comment]
> So, what do you think on getting back to "view" this particular case? as it's refering to the view template.

Sounds good to me. You're right that change looks like a mistake.

**Comment by xavier83ar** [comment]
Well, I've added hasOne relation on view template, also I've updated its test case in order to tests this relations, to do this I had to add some fixtures and I took the chance to add also hasMany relation which wasn't being tested.

I've run all tests and all passed ok, except for two that were marked as skipped with the message "Additional tables detected" (testMainIntoAll, testSkipTablesAndAll both from ModelTaskTest). I guess that it's because I've added fixtures. What should I do with them?

I've also check Coding standars and have passed the CakePHP Code Sniffer. 

You can take a look to the changes here (https://github.com/cakephp/bake/compare/master...xavier83ar:master) buut, now I need some help, I'm pretty new to git, I followed instructions on cakephp documentation (Cakephp/Contributing/Code page) without issues, but when I did that, there was no 1.1.4 nor 1.2.1 tags, so I had created a branch from master. Now I see that there were 13 commits after I've forked it and these two new branches.... so, I've got no idea what to do now, how should I proceed to make a pull request?

**Comment by markstory** [comment]
Closing as a pull request is up now.
