### ISSUE TITLE
SkipFields enhancement

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#222]
See https://github.com/dereuromark/cakephp-setup/blob/master/docs/Console/Bake.md#skipping-fields
for current implementation

``` php
public $scaffoldSkipFields = array('password', ...); // For all actions
public $scaffoldSkipFieldsIndex = array('admin_comment'); // Only for index action
```

Ported from https://github.com/cakephp/cakephp/issues/1889

**Comment by markstory** [comment]
Could we skip `_hidden` fields? Or is this different than that. Having two lists of hidden/skipped fields on 2 different classes is a bit confusing to me.

**Comment by dereuromark** [comment]
hidden is different, I think.
Because this part of skip fields also mainly depends on the view type (form != view != index).

But I am fine keeping it in my custom template, if there is no interest in adapt.

**Comment by markstory** [comment]
Its not that I'm not interested. I'm just trying to make it consistent with other features we have. Is the reason you don't want to use CLI flags that these settings should persist beyond a single bake run?

**Comment by dereuromark** [comment]
Yes

A propos persisted. That is currently a big issue with using the shell in general.
All settings like theme and alike should also be persisted, using a Configure `Bake` key, so they are read into the shell as default settings on a per app basis.

**Comment by markstory** [comment]
If there is a need/desire for persistent configuration in bake, I would prefer we do just that vs. adding properties to arbitrary classes.

**Comment by dereuromark** [comment]
Well, we would have to add those new config options one way or another.
But most of those options should not be cli-enabled, as it is just super painful to manually append them to the call. Those should be internal config (either inside class as I did, or config file) only.

**Comment by markstory** [comment]
A standalone config file feels like a better long term solution to me. We could also use this file to allow customisations to other tasks or enabling specific cli flags by default.

**Comment by josegonzalez** [comment]
You could just use bake events for this.

**Comment by othercorey** [comment]
Looks like this isn't getting support for now.
