### ISSUE TITLE
i18n not work in edit and add for field labels.

### ISSUE THREAD

**Issue by aoliverio** [cakephp/bake#233]
i18n not work in edit and add for field labels. I have changed as follows in for all  $this->Form->input in Bake/Element/form.ctp

```php
<?= $this->Form->input('<%= $field %>', ['label' => '<%= Inflector::humanize($field) %>']); ?>
```

What do you think ?

**Comment by markstory** [comment]
How does that change help with i18n?

**Comment by aoliverio** [comment]
Sorry markstory, but the error was in my Bake custom template. I saw that the helper input natively translates the label. Thanks for all the work you do for us.
