### ISSUE TITLE
Bake confused by "_id" field name.

### ISSUE THREAD

**Issue by ADmad** [cakephp/bake#236]
_From @thinkingmedia on April 5, 2016 13:45_

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.6
* Platform and Target: Apache2, MySQL, Php 7

### What you did

Added a field named `_id` as an integer to the MySQL table. It was not the primary key of the table as it already had an `id` field that is uuid. 

The `_id` is just a field to store an reference value from a third-party source.

### Expected Behavior

Bake to treat this field as regular value field.

I understand that the field name "_id" does not follow Cake naming conventions. I needed the prefix since all field names mapped to  third-party JSON fields. This just made my job of processing data easier.

### Actual Behavior

Bake generated an empty `belongsTo` association in the table.

```
        $this->belongsTo('', [
            'foreignKey' => '_id',
            'joinType' => 'INNER',
            'className' => 'TheMovieDB.'
        ]);
```

Bake generated an empty `@property` in the table.

```
/**
 * Genres Model
 *
 * @property \Cake\ORM\Association\BelongsTo $
 * @property \Cake\ORM\Association\BelongsToMany $Movies
 * @property \Cake\ORM\Association\BelongsToMany $TvShows
 */
```

Bake generated an empty `@property` in the entity.

```
/**
 * Genre Entity.
 *
 * @property string $id
 * @property int $_id
 * @property \TheMovieDB\Model\Entity\ $
 * @property string $name
 * 
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 */
```

> Note: TheMovieDB is the name of my plugin.

I assume that this can be an easy fix. Bake just needs to validate the format of a field name before treating it as an associated. I think bake is just checking if it ends in `_id`. It needs to end with `_id` and be more then 3 characters.

_Copied from original issue: cakephp/cakephp#8595_

**Comment by ADmad** [comment]
@thinkingmedia Would you like to submit a fix for this?

**Comment by thinkingmedia** [comment]
@ADmad Yes, I will do that.

**Comment by ionas** [comment]
Solution name your non primary/foreign keys or custom primary keys `key`and `_key`

**Comment by thinkingmedia** [comment]
@ionas the table columns match fieldnames from json. To keep importing simple I didn't want to rename anything and the json already has `id`. So to track fieldnames that are not part of the json I prefix them with `_`. So I added a `_id`.

It's not really a normal thing to do.

**Comment by ionas** [comment]
- You can add a virtual field in the Entity as a work around.
- If a table holds at least one foreign key constraint we could ignore any foreign key matching by conventions.
- Via conventions "_id" should neither count towards primary key(s) nor foreign key(s) - however foo_id might and in case you have no foreign key constraints setup bake will and should not do what you want.

**Comment by markstory** [comment]
Pull request open now.
