### ISSUE TITLE
Add @method stubs for tables to declare return type.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/bake#237]
When you generate a `Table` with bake. You get a class phpDoc like this.

For example, `PostsTable` with some associations.

```
/**
 * Posts Model
 *
 * @property \Cake\ORM\Association\HasMany $PostLikes
 * @property \Cake\ORM\Association\HasMany $PostViews
 * @property \Cake\ORM\Association\BelongsToMany $Boards
 */
```

Afterwards when you want to use `get` or `newEntity` you have to do this to get proper type auto-complete.

```
    /**
     * @type \App\Model\Entity\Post $post
     */
    $post = $this->Posts->get($id);
```

It peppers the source code with type declares and is a pain to always write. So what I do is declare the return types using `@method`. Like this

```
/**
 * Posts Model
 *
 * @property \Cake\ORM\Association\HasMany $PostLikes
 * @property \Cake\ORM\Association\HasMany $PostViews
 * @property \Cake\ORM\Association\BelongsToMany $Boards
 *
 * @method get($primaryKey, $options = []) : Post
 * @method newEntity($data = null, array $options = []) : Post
 * @method patchEntity(EntityInterface $entity, array $data, array $options = []) : Post
 */
```

Now auto-complete works in the IDE

```
     $this->Posts->get($id)->title;   <-- title marked as property from Post entity.
```

There are other methods from the table that could use this trick as well. Like "save", "newEntities", etc. Any method where the return type is the `EntityInterface`

Would this be something worth adding to the bake plugin?

**Comment by markstory** [comment]
Wouldn't we need to add `@method` hints for every method that returns an entity?

**Comment by thinkingmedia** [comment]
@markstory you can't only hint by changing the return type. There aren't that many that return just `Entity`.

**Comment by markstory** [comment]
So how many methods would need IDE hints?

**Comment by thinkingmedia** [comment]
I would only hint for `RepositoryInterface` the methods that return a `EntityInterface`. You can't change the calling signature using `@method`, but you can change the return type.

So that would be **5** methods.

Like so

```
/**
 * Posts Model
 *
 * @method get($primaryKey, $options = []) : Post
 * @method newEntity($data = null, array $options = []) : Post
 * @method newEntities($data = null, array $options = []) : Post[]
 * @method patchEntity(EntityInterface $entity, array $data, array $options = []) : Post
 * @method patchEntities(EntityInterface $entity, array $data, array $options = []) : Post[]
 */
```

**Comment by markstory** [comment]
@thinkingmedia If you could put a pull request together, that would be great.

**Comment by markstory** [comment]
Closing as a pull request is up now.
