### ISSUE TITLE
Add @mixin for tables that use behaviors.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/bake#238]
To expand on #237 that adds return stubs. This improvement would add mixins for behaviors.

If bake adds the `TimestampBehavior` it should also add the `@mixin` for that behavior to the class.

```
/**
 * Posts Model
 *
 * @property \Cake\ORM\Association\HasMany $PostLikes
 * @property \Cake\ORM\Association\HasMany $PostViews
 * @property \Cake\ORM\Association\BelongsToMany $Boards
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
```

This would give you auto-complete on all the public functions from that behavior on the table.

```
    $this->Posts->touch($post); // <- IDE sees touch as valid method of Posts
```

Without the `@mixin` the IDE will mark `touch` as invalid method for that class.

**Comment by josegonzalez** [comment]
What IDE supports this?

**Comment by thinkingmedia** [comment]
@josegonzalez works with PhpStorm.

**Comment by markstory** [comment]
@thinkingmedia A pull request would be great for this.

**Comment by markstory** [comment]
Closing as a pull request is up.
