### ISSUE TITLE
Be able to rewrite the validationDefault method on a table class.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/bake#239]
I don't think there are any features in bake that allow you to modify an existing class, but if it could. I would like to be able to regenerate the `validationDefault` method on a table.

It shouldn't be technically difficult to rewrite just one method.

**Comment by josegonzalez** [comment]
It actually would because you'd need to parse the entire class into tokens and then replace *just* your tokens without modifying the rest of the code.

Related: https://github.com/cakephp/bake/issues/205

**Comment by markstory** [comment]
Bake has never done inline edits. Its a really hard problem that I'd prefer to not try and solve.

**Comment by thinkingmedia** [comment]
@markstory I accept your challenge and will raise you one pull request.

**Comment by markstory** [comment]
Closing as editing existing files is well outside of bake's scope for the present. Programmatically editing user modified code requires more complex methods like AST transforms, and I'm not sure we want to take that scope on in bake.
