### ISSUE TITLE
Bake template don't use the correct --connection parameter

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/bake#243]
I have two datasources, the default is used on my virtual machine, it connects to postgres using unix soquet and the 'cli' connection i use to run commands from my local terminal. Both datasources connects to the same database.
```php
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'unix_socket' => true,
            'host' => '',
            'username' => 'vagrant',
            'database' => 'my_db',
            'quoteIdentifiers' => false
        ],
        'cli' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'unix_socket' => false,
            'host' => 'dev1.local',
            'username' => 'vagrant',
            'database' => 'my_db',
            'quoteIdentifiers' => false
        ],
```

This works. If i run from my local terminal:
``bin/cake bake template -c cli -p Fluid --prefix App -v``  
Bake returns:  

    Possible tables to bake view templates for based on your current database:
    - Pages
    - Sessions
    - Users

Now, i run:
``bin/cake bake template --connection cli -p Fluid --prefix App -v Users``  
And the bake returns:

    Exception: SQLSTATE[08006] [7] could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"? in [/mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php, line 48]

When i changed the 'default' connect the database using the same values as 'cli' and the same command as before, it works.

This issue is similar to #63.

**Comment by markstory** [comment]
If I'm understanding you correctly, the `-c` option works while `--connection` does not?

**Comment by LACabeza** [comment]
no, both don't works.  
what i meant is `bin/cake bake template -c cli -p Fluid --prefix App` works, it show the database's tables while `bin/cake bake template --connection cli -p Fluid --prefix App Users` don't work, it raises the error.

**Comment by LACabeza** [comment]
An easy way to reproduce this problem is set incorrect parameters on 'default' datasource and correct params on another datasource.

Then run the command `bin/cake bake template -c corret_connection`, it will works, but it will fail when you give the table name to generate the template `bin/cake bake template -c corret_connection TableName`

**Comment by markstory** [comment]
Ok, thank you for the clarifications.

**Comment by markstory** [comment]
I wasn't able to reproduce this issue with either the template task, or the model task. In all cases, bake works as it should and no SQL errors are emitted.

Do you have relations between your connections, or perhaps a stack trace for the error you are getting?

**Comment by alysson-azevedo** [comment]
Datasources:

        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'unix_socket' => true,
            'host' => '',
            'username' => 'vagrant',
            // 'password' => '',
            'database' => 'app_db',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false
        ],
        'cli' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'unix_socket' => false,
            'host' => 'dev1.local',
            'username' => 'vagrant',
            'password' => '',
            'database' => 'app_db',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false
        ]


This works:
```bash
$ bin/cake bake template --connection cli         

Welcome to CakePHP v3.2.8 Console
---------------------------------------------------------------
App : src
Path: /mnt/data/appweb/src/
PHP : 5.6.20
---------------------------------------------------------------
Possible tables to bake view templates for based on your current database:
- Pages
- Sessions
- Settings
- Users
```

This fail:
```bash
$ bin/cake bake template --connection cli Settings

Welcome to CakePHP v3.2.8 Console
---------------------------------------------------------------
App : src
Path: /mnt/data/appweb/src/
PHP : 5.6.20
---------------------------------------------------------------
Exception: SQLSTATE[08006] [7] could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"? in [/mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php, line 48]
2016-05-03 03:44:32 Error: [PDOException] SQLSTATE[08006] [7] could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Stack Trace:
#0 /mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php(48): PDO->__construct('pgsql:dbname=ap...', 'vagrant', '', Array)
#1 /mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Driver/Postgres.php(68): Cake\Database\Driver\Postgres->_connect('pgsql:dbname=fl...', Array)
#2 /mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Schema/BaseSchema.php(45): Cake\Database\Driver\Postgres->connect()
#3 /mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Dialect/PostgresDialectTrait.php(165): Cake\Database\Schema\BaseSchema->__construct(Object(Cake\Database\Driver\Postgres))
#4 /mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Schema/Collection.php(52): Cake\Database\Driver\Postgres->schemaDialect()
#5 /mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(43): Cake\Database\Schema\Collection->__construct(Object(Cake\Database\Connection))
#6 /mnt/data/appweb/vendor/cakephp/cakephp/src/Database/Connection.php(317): Cake\Database\Schema\CachedCollection->__construct(Object(Cake\Database\Connection), true)
#7 /mnt/data/appweb/vendor/cakephp/cakephp/src/ORM/Table.php(428): Cake\Database\Connection->schemaCollection()
#8 /mnt/data/appweb/vendor/cakephp/bake/src/Shell/Task/TemplateTask.php(286): Cake\ORM\Table->schema()
#9 /mnt/data/appweb/vendor/cakephp/bake/src/Shell/Task/TemplateTask.php(147): Bake\Shell\Task\TemplateTask->_loadController()
#10 [internal function]: Bake\Shell\Task\TemplateTask->main('Settings')
#11 /mnt/data/appweb/vendor/cakephp/cakephp/src/Console/Shell.php(456): call_user_func_array(Array, Array)
#12 /mnt/data/appweb/vendor/cakephp/cakephp/src/Console/Shell.php(450): Cake\Console\Shell->runCommand(Array, false)
#13 /mnt/data/appweb/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(217): Cake\Console\Shell->runCommand(Array, true, Array)
#14 /mnt/data/appweb/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(181): Cake\Console\ShellDispatcher->_dispatch(Array)
#15 /mnt/data/appweb/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(127): Cake\Console\ShellDispatcher->dispatch(Array)
#16 /mnt/data/appweb/bin/cake.php(20): Cake\Console\ShellDispatcher::run(Array)
#17 {main}
```

When i set the default connection with the correct parameters, the command `$ bin/cake bake template Settings` works.

**Comment by alysson-azevedo** [comment]
i did some debugging here.  
On `bake/src/Shell/Task/TemplateTask.php(286)`, `$modelObject->schema()` is called without arguments, then on `cakephp/src/ORM/Table.php(426)` runs
```
$this->_schema = $this->_initializeSchema(
                    $this->connection()
                        ->schemaCollection()
                        ->describe($this->table())
                );
```
and that `$this->connection()` (line 427) returns 'default' instead 'cli'. This raises the error.

**Comment by alysson-azevedo** [comment]
Changing the `bake/src/Shell/Task/TemplateTask.php(280)` to
```
$modelObject = TableRegistry::get($this->modelName, [ 'connectionName' => $this->connection]);
```
fix the problem here. Do you want me try make a pull-request?

**Comment by josegonzalez** [comment]
Looks like the following classes also need modification:

- `\Bake\Shell\Task\TestTask`
- `\Bake\Shell\Task\FixtureTask`

**Comment by markstory** [comment]
@alysson-azevedo A pull request would be great if you have the time. I'll take another look tonight as well.

**Comment by alysson-azevedo** [comment]
@josegonzalez where `\Bake\Shell\Task\FixtureTask`needs to be changed? I checked and it do uses the -c parameter when creating the table objects.

**Comment by josegonzalez** [comment]
It looks like we depend upon the `exists` [check](https://github.com/cakephp/bake/blob/master/src/Shell/Task/FixtureTask.php#L420).

**Comment by alysson-azevedo** [comment]
Well we have a problem. If the model exists on the TableRegistry, we can't call get() method with options, [it would raise an exception](https://github.com/cakephp/cakephp/blob/master/src/ORM/Locator/TableLocator.php#L133).

i'll update the code so it'll check if table exists too.

**Comment by markstory** [comment]
Thanks for opening the pull request @alysson-azevedo :smile:
