### ISSUE TITLE
Exception, if "tmp" folder is missing

### ISSUE THREAD

**Issue by makallio85** [cakephp/bake#244]
Exception: mkdir(): No such file or directory in file vendor\cakephp\bake\src\View\BakeView.php and line 100

If "tmp" folder does not exists, bake folder creation inside it fails. Is this way it should work, or should we just assume, "tmp" folder always exists?

**Comment by dereuromark** [comment]
Did you forget to enable debug Mode?

**Comment by makallio85** [comment]
No. Debug mode was enabled. Of course these directories are created by cakephp/app installer file, but is it good practice to rely on it?

**Comment by dereuromark** [comment]
You are responsible that those folders exist.

**Comment by jhli** [comment]
I'd personally say creating those folders with bake is good as you need to have write privileges for bake, anyway!

**Comment by markstory** [comment]
You need to make the directory. The exception tells you that. We don't automatically make the directory as people can be pretty fussy about permissions on `tmp`.
