### ISSUE TITLE
Composer ignores /src/Template/Bake/Plugin/tests directory

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/bake#248]
As the title says, composer doesn't install that [tests](https://github.com/cakephp/bake/tree/master/src/Template/Bake/Plugin/tests) dir and its [bootstrap.php.ctp](https://github.com/cakephp/bake/blob/master/src/Template/Bake/Plugin/tests/bootstrap.php.ctp) file.

i tried delete the `/vendor/cakephp/bake` dir, `composer clear-cache`, then:
```bash
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing cakephp/bake (1.2.4)
    Downloading: 100%

$ ls -1 vendor/cakephp/bake/src/Template/Bake/Plugin
composer.json.ctp
config
phpunit.xml.dist.ctp
README.md.ctp
src
webroot
```

**Comment by markstory** [comment]
I bet this is because of the `/tests export-ignore` in the `.gitattributes` file.

**Comment by alysson-azevedo** [comment]
I agree.
