### ISSUE TITLE
cake 3.x bake model fails when the default connection is invalid and a valid --connection is given by argument.

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/bake#250]
Yes, this is kind of related with #243, but the problem is different and it'll be hard to fix.
I have a virtual machine with the database and the webserver.
So, my 'default connection' is set to work from the VM (imagine the 'host' param is 'localhost'). I also have another connection called 'cli' that i use to run commands from my terminal (the database's host param  is '192.168.33.10'). This is very convenient for me.

In that database i have have a table called `plans`. So, if I go to VM and run the command `bin/cake bake model Plans`, everything works, but from my local machine, i run the command `bin/cake bake model -c cli Plans`, it should work too, but instead i get the same error as #243 issue, but with a different stack trace ([see here](https://gist.github.com/alysson-azevedo/f024a391eebf67912fdd7a499fcff897)).

I did some debug and it seem the problem is some associated tables try to connect to the database using the 'default' connection instead the 'cli'. 
In that table `plans` there's a field called `reference_id`, but i don't have a table called `reference`, but even so the [ModelTask::findBelongsTo()](https://github.com/cakephp/bake/blob/master/src/Shell/Task/ModelTask.php#L257-L288) add to the BelongsTo association list. 
At this point i get lost. 

At the [ModelTask::getEntityPropertySchema](https://github.com/cakephp/bake/blob/master/src/Shell/Task/ModelTask.php#L480), the $association variable has no _tableLocator and no _targetTable assigned.
![Imgur](http://i.imgur.com/pQmd77X.png)
Then, i step into [Association::target()](https://github.com/cakephp/cakephp/blob/master/src/ORM/Association.php#L296) and _targeTable already has a Cake\ORM\Table object, with connectioName = 'default' instead 'cli'.
![Imgur](http://i.imgur.com/hb3E5X5.png)

Like i said, this issue is very complex and can stay on hold, since i can just change the default connection and everything works.

**Comment by markstory** [comment]
I'm not sure this is 'fixable' to be honest.

**Comment by ewbarnard** [comment]
I am just starting to use CakePHP 3 (3.2.12) and believe I am seeing the same issue. 
`bin/cake bake model WssCallLogOds  -c ods`
blows up, unable to access the default connection. My table has column `member_id` but that connection has no members table. The default connection does NOT have valid connection information.

However, if I add the undocumented (?) no-associations parameter:
`bin/cake bake model WssCallLogOds -c ods --verbose --no-associations`
everything appears fine.

See Bake\Shell\Task\ModelTask::getAssociations() (around line 197). I'm guessing this issue might be fixable by allowing a bake parameter which says "Do not search for associations on other connections." In my current case no-associations is correct.

Would it make sense to add no-associations to the --help output?

**Comment by ewbarnard** [comment]
I have a fix for my use case, but I'm not sure that it covers all relevant cases. I'm familiar with the CakePHP 2.x code generator but not for the CakePHP 3 ORM. Here is a diff, followed by an explanation. I'm happy to figure out how to do a proper pull request if this is actually a usable fix.
```
diff BatsDashboard/vendor/cakephp/bake/src/Shell/Task/ModelTask.php WssCallLog/vendor/cakephp/bake/src/Shell/Task/ModelTask.php
294c294,296
<             $associations['belongsTo'][] = $assoc;
---
>             if ($this->_allowAssociation($assoc['alias'])) {
>                 $associations['belongsTo'][] = $assoc;
>             }
299a302,306
>     protected function _allowAssociation($alias) {
>         return empty($this->params['same-connection']) ||
>             in_array(Inflector::tableize($alias), $this->_tables, true);
>     }
> 
374c381
<                 if ($assoc) {
---
>                 if ($assoc && $this->_allowAssociation($assoc['alias'])) {
418c425,427
<                 $associations['belongsToMany'][] = $assoc;
---
>                 if ($this->_allowAssociation($assoc['alias'])) {
>                     $associations['belongsToMany'][] = $assoc;
>                 }
1006a1016,1018
>         ])->addOption('same-connection', [
>             'boolean' => true,
>             'help' => 'Only generate associations on the same connection.'
```
1. The final section (line 1006) adds the --same-connection option to the model generator.

2. The second section (line 299) adds _allowAssociation(). This method checks to see if the tableized alias is in the list of tables on the current connection. If so we allow the association.

3. The other three sections change findBelongsTo(), findHasMany(), findBelongsToMany() to call _allowAssociation().

Note that code-generation behavior only changes if you add the --same-connection parameter. I'm not sure if we want to be generating cross-connection relationships at all. If not we don't need the --same-connection parameter; just hard-code the calls.

**Comment by markstory** [comment]
>  I'm not sure if we want to be generating cross-connection relationships at all. If not we don't need the --same-connection parameter; just hard-code the calls.

I'm not sure either. Cross connection associations can get pretty expensive time-wise and awkward to work with.

**Comment by ewbarnard** [comment]
Mark, I'll create a pull request. I'll leave the command-line parameter in so that it remains absolutely backwards compatible, i.e., you need to specify --same-connection to get use of my fix.

**Comment by markstory** [comment]
Ok. I don't think the flag is necessary though.

**Comment by ewbarnard** [comment]
Sounds good. Expect a PR Monday-ish with tests, assuming I can find a way to test it. I'll check to see if there's anything in the book to update. Thank you for the kind feedback.

**Comment by markstory** [comment]
:metal:

**Comment by markstory** [comment]
@ewbarnard ping

**Comment by alysson-azevedo** [comment]
I'll close this issue since #392 is open.
