### ISSUE TITLE
Dont' bake validation rules for non-manual primary keys (sequential integer, uuid)

### ISSUE THREAD

**Issue by ionas** [cakephp/bake#253]
``` php
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');
```

... should be covered by:

``` php
    protected $_accessible = [
        '*' => true,
        'id' => false, // this
    ];
```

**Comment by dereuromark** [comment]
If that is the case, then I agree with you.
Anyone interested in a PR here?

**Comment by dereuromark** [comment]
On the other side:
What if you tmp allow it to be accessible? Wouldnt you then want the validation rule to work?

But I do agree that this is not the common scenario and that adding the overhead here seems not to be a good default.

**Comment by dereuromark** [comment]
It doesnt hurt too much and if no one makes a PR this is just stale here.
