### ISSUE TITLE
Bake test for controller with prefix returns error

### ISSUE THREAD

**Issue by markstory** [cakephp/bake#254]
_From @tzvio on May 30, 2016 6:35_

This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.9
- Platform and Target: Ubuntu 16.04  Apache 2.4.18 Postgresql 9.5.2 
  using cake bake from console.
### What you did

I'm having an admin section in my app , 
and some of the controllers use admin prefix.
run this command from console:

`bin/cake bake test Controller --prefix admin CustomersController`
### Expected Behavior

Generate test for CustomersControllerTest in TestCase/Controller/Admin
### Actual Behavior

Received error:

_Error: Unknown option `prefix`_

_Copied from original issue: cakephp/cakephp#8907_

**Comment by markstory** [comment]
It looks like test baking for prefixed controller works fine when the tests are generated at the same time as the controller. This is due to `ControllerTask` customizing the classname when invoking the test task. You might have better luck using `bin/cake bake test Controller 'Admin\CustomsController'` as a workaround/solution.

**Comment by tzvio** [comment]
Thanks, I'll try that

**Comment by markstory** [comment]
Pull request open now.

**Comment by hisame64** [comment]
@markstory 
Please reopen this issue, this problem occurs now yet.
I did `bake controller` with `--prefix` , occurred same problem.  

```
[root@localhost public]# /bin/bash bin/cake bake controller --prefix Cart View

Welcome to CakePHP v3.3.10 Console
---------------------------------------------------------------
App : src
Path: /home/testproj/public/src/
PHP : 7.0.12
---------------------------------------------------------------

Baking controller class for View...

Creating file /home/testproj/public/src/Controller/Cart/ViewController.php
Wrote `/home/testproj/public/src/Controller/Cart/ViewController.php`
Bake is detecting possible fixtures...
Exception: Call to a member function alias() on null in [/home/testproj/public/vendor/cakephp/bake/src/Shell/Task/TestTask.php, line 436]
2016-12-23 17:08:45 Error: [Error] Call to a member function alias() on null
Stack Trace:
#0 /home/testproj/public/vendor/cakephp/bake/src/Shell/Task/TestTask.php(471): Bake\Shell\Task\TestTask->_processModel(NULL)
#1 /home/testproj/public/vendor/cakephp/bake/src/Shell/Task/TestTask.php(421): Bake\Shell\Task\TestTask->_processController(Object(App\Controller\Cart\ViewController))
#2 /home/testproj/public/vendor/cakephp/bake/src/Shell/Task/TestTask.php(226): Bake\Shell\Task\TestTask->generateFixtureList(Object(App\Controller\Cart\ViewController))
#3 /home/testproj/public/vendor/cakephp/bake/src/Shell/Task/ControllerTask.php(206): Bake\Shell\Task\TestTask->bake('Controller', 'Cart\\View')
```

**Comment by markstory** [comment]
@hisame64 This looks like it might be caused by your controller being called `ViewController`. When generating fixtures bake naively uses `$controller->{$controller->modelClass}` assuming its a Table class but in your case it is null. There are clearly some missing null checks.

**Comment by markstory** [comment]
New pull request up now.
