### ISSUE TITLE
autoIncrement option error

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#255]
Yesterday, `bin/cake` bake migration_snapshot baked:
```
		$this->table('users')
			->addColumn('id', 'integer', [
				'autoIncrement' => true,
				'default' => null,
				'limit' => 10,
				'null' => false,
				'signed' => false,
			])
```

Running migrations migrate afterwards on a fresh db table gets:
```
 == 20141125043024 Init: migrating
  [RuntimeException]
  "autoIncrement" is not a valid column option.
```

Also `->addPrimaryKey(['id'])` is unknown and errors.
Did someone forget the  constraints of the phinx dependency to set them up?

Latest dev master.

**Comment by HavokInspiration** [comment]
Wrong repo ?

**Comment by dereuromark** [comment]
Darn. Yeah

**Comment by ADmad** [comment]
This issue was moved to cakephp/migrations#238
