### ISSUE TITLE
Bake makes IDE unhappy

### ISSUE THREAD

**Issue by Xymanek** [cakephp/bake#259]
I use PhpStorm and recently I started seeing this warning: 
![screenshot_7](https://cloud.githubusercontent.com/assets/2865341/16832223/03a3fb38-49b2-11e6-8231-0d5d502baee0.png)

When I stated digging around I found that the class is defined in following files:

* src/Model/Table/UsersTable.php
* vendor/cakephp/bake/tests/comparisons/Model/testBakeWithRules.php

So the problem is that I **cannot** exclude the files from project as they are automatically added as external libraries due to use of composer. Disabling that auto-behavior will create a lot of problems so that's out of question.

After further investigation it turns out that come classes are prefixed (eg. `BakeArticles` and all entities) but some aren't:

* CategoriesProductsTable
* CategoriesTable
* OldProductsTable
* ProductsTable
* ProductVersionsTable
* UsersTable

So all of them might cause warnings in case there is an overlap with the ones in the actual project.

What can be done (my idea/opinion):

* Prefix all of the Tables ***OR***
* Like the core CakePHP package, remove the tests from composer installations (probably safe bet)

**Comment by dereuromark** [comment]
Sounds like a good idea
so baiscally

    tests/TestCase export-ignore

is missing right now etc.
Feel free to make a PR.

**Comment by Xymanek** [comment]
Sorry, but I just started to learn how tests work so I'm afraid I am unable to fix this problem myself and PR. The ideas that I suggested are based of how I saw it was done already so I thought that whoever has done it before will be able to help out with this issue as well.

**Comment by dereuromark** [comment]
See https://github.com/cakephp/cakephp/blob/master/.gitattributes and compare it to the one here.

**Comment by Xymanek** [comment]
Ah I think I understand. Will make a PR now

**Comment by thinkingmedia** [comment]
> So the problem is that I cannot exclude the files from project as they are automatically added as external libraries due to use of composer.

Yes you can. This is how you do.

- Start `PhpStorm`
- Press `ATL+1` to open the project explore
- Navigate to `vendor/cakephp/cakephp/tests`
- Right click and select "Mark directory as / Excluded"

All the files in that folder will not be excluded in intellisense (which handles autocomplete).

In addition to excluding directories. You should also mark your `app/src` directory as "Sources Root", and then mark your `app/webroot` as "Resources Root". You can also mark your own `app/tests` folder as "Test Sources Root"

PhpStorm is a great editor for Cake. Try the CakePHP plugin which can be found in the plugin gallary.

> Like the core CakePHP package, remove the tests from composer installations (probably safe bet)

Yes, this should be excluded. It'll also make installing Cake faster.

**Comment by Xymanek** [comment]
Ok, made the PR. As for @thinkingmedia 's suggestion, I tried that. Howver that option is missing for me: 
![screenshot_1](https://cloud.githubusercontent.com/assets/2865341/16834089/e71a0396-49ba-11e6-9437-d31e4c6e45d0.png)
I think that's because PhpStorm already marked the `vendor/cakephp/bake` as library root. Also the Cake plugin is very nice as well but for some reason it doesn't work for my latest project (works for 2-3 other ones)

**Comment by thinkingmedia** [comment]
@Xymanek don't mark it as library root.

PhpStorm can auto detect namespaces for most vendor packages. I think you only need to mark library root is a package isn't using an autoloader and PhpStorm can't tell what the namespace is.
