### ISSUE TITLE
Baked (and all plugins in general) must include "cakephp/plugin-installer"

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#268]
Pretty much all plugins are currently missing:

    "require": {
        "cakephp/plugin-installer": "*",

But in fact, this is a hard dependency, and without it an app having this require statement it will never find any plugins. But the app itself must not have to know about it, you simply require a plugin and that one would know about this requirement.

So this should be added to a baked plugin skeleton composer json IMO.

We must also educate to all user land plugins to also contain this one in order for people to easily be able to use plugins.

**Comment by markstory** [comment]
Can't the app's have the dependency?

**Comment by dereuromark** [comment]
That's dependency-wise incorrect.
The app does not need it. Once You require a plugin you do. Thus the Plugin must provide this Bridge Tool.

**Comment by ADmad** [comment]
The plugin does not need the installer. The app needs the installer to use the plugin :)

**Comment by dereuromark** [comment]
No, thats the wrong dependency. Your argumentation is flawed.
If you do require plugin-name, nothing else must be needed to get it to run.
Otherwise the plugin's responsibility wasn't met regarding it's direct dependencies.

**Comment by ADmad** [comment]
> If you do require plugin-name, nothing else must be needed to get it to run.

But that's not the case since the app's composer.json needs [this](https://github.com/cakephp/app/blob/master/composer.json#L38) `post-autoload-dump` script for the `cakephp-plugins.php` to be generated.

So as I stated earlier it's the app that needs the plugin installer not the plugin itself.

**Comment by dereuromark** [comment]
Interesting, because an upgraded app so far didnt need that repo included, until the first plugin came along, and only then it needed that `cakephp-plugins.php` generation either.

**Comment by ADmad** [comment]
`cakephp-plugins.php` is needed to locate and load files from `config` and `webroot`. Class loading will work fine even without it.

**Comment by dereuromark** [comment]
Sure, but that still requires a plugin to be present in the first place, does it not?
In that case: Include a plugin and its config/webroot, now also include/require the installer.

**Comment by dereuromark** [comment]
I do however see your point about the post-autoload-dump hook.
Makes me think if that one shouldnt be part of the installer, but not sure if that is technically possible.
If not, I agree that there is no perfect solution here then.

**Comment by renan** [comment]
Afaik that's not supported by composer yet:

> Note: Only scripts defined in the root package's composer.json are executed. If a dependency of the root package specifies its own scripts, Composer does not execute those additional scripts.

https://getcomposer.org/doc/articles/scripts.md#scripts
