### ISSUE TITLE
Numeric column names break baked templates

### ISSUE THREAD

**Issue by mo86** [cakephp/bake#269]
**What you did**
Having a few database columns which names are just numeric and "baked" all models/templates.

**Expected Behavior**
A baked template should work with numeric column names.

**Actual Behavior**
If you bake all templates for Model "Foo" and model Foo has a column named "123" than cake bakes for example an index.ctp with the following code:
`
<?= h($foo->123) ?>`

but it should output this:

`<?= h($foo->{123}) ?>
`

**Comment by markstory** [comment]
You'll have to edit the templates yourself. Bake is intended to handle _conventions_ based applications. Numeric columns, and those with spaces in them do not follow conventions. I don't think that maintaining the additional complexity in bake for what should be a very rare scenario is worth the effort.
