### ISSUE TITLE
Association generation should use defined constraints

### ISSUE THREAD

**Issue by markstory** [cakephp/bake#278]
If an association is detected between two tables, we should use any defined constraints as the primary source of foreign key information, and then fallback to conventions. This would make bake more useful for people with non-conventional column names, but defined constraints.

See cakephp/cakephp#9576

**Comment by dereuromark** [comment]
Are we already doing this to some extend?

**Comment by markstory** [comment]
Looking through the association code, yes this seems better than it would have been in 2016.
