### ISSUE TITLE
What is difference 'addresses' and 'addrs', 'organizations' and 'orgs' after bake?

### ISSUE THREAD

**Issue by gnh1201** [cakephp/bake#286]
Related issues: #283 #132

Error message:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.addrs' doesn't exist 

Why occurred abbreviate table name of generated codes after bake command?

1. mydb.addresses -> mydb.addrs
2. mydb.organizations -> mydb.orgs

I do not understand this abbreviation policy in bake instruction in cakePHP.

**Comment by dereuromark** [comment]
Are you sure this is on CakePHP (Bake) site?
This looks like a project specific issue with your database table.
The Bake plugin does not abbreviate ever by itself. Check your DB tables and the meta schema etc.

**Comment by gnh1201** [comment]
[Table] users: [Fields] user_id(FK), addr_id, somethings...
[Table] addresses: [Fields] addr_id(FK), org_id, addr_name, somethings...
[Table] organizations: [Fields] org_id(FK), org_name, somethings...

I think, Bake consider to prefix of fields such as 'user_', 'addr_', 'org_'.
so, I can not use 'mydb.addresses' expression in my project after Bake.

Is it correct?

**Comment by dereuromark** [comment]
Your schema is invalid as per CakePHP conventions.
You must either rename "addr_id" to "address_id" for it to find the relation ("org_id" to "organization_id") - or you cannot use the relational part here out of the box.

Closing as invalid then.
