### ISSUE TITLE
Task is listed as an option to bake test files, but not found

### ISSUE THREAD

**Issue by steinkel** [cakephp/bake#289]
Doing `bin/cake bake test` I get

1. Entity
2. Table
3. Controller
4. Component
5. Behavior
6. Helper
7. Shell
8. Task
9. Shell_helper
10. Cell
11. Form
12. Mailer

But `bin/cake bake test task` reports Error: "task" is not a valid value for type. Please use one of "Controller, controller, Table, table, Entity, entity, Helper, helper, Component, component, Behavior, behavior, Shell, shell, shell_helper, Cell, cell, Form, form, Mailer, mailer"

I'll leave this ticket as a todo for the task test or remove the option from the help output.

**Comment by markstory** [comment]
Pull request open now.
