### ISSUE TITLE
@CakePHP3.4 Bake Output: Replace FormHelper::*input*() with FormHelper::*control*()

### ISSUE THREAD

**Issue by inoas** [cakephp/bake#294]
CakePHP 3.4 will bring a deprecation of *FormHelper::input()* and similar methods in favour of *FormHelper::control()*. Bake template output should reflect that.

### Issue

From there-on bake will not be backwards compatible with < 3.4, so it would require a new major release.

**Comment by antograssiot** [comment]
We can keep it as is for now and keep it working with as many version as it can right now.
I'very been thinking about this and a lot of deprecated function are added by bake but I think that itranslation better benefits to people if it keep working and be supported for most 3.x version

**Comment by inoas** [comment]
We can also switch around the template output by creating a helper method and detect Configure::version()?

**Comment by antograssiot** [comment]
That's a possibility that I didn't considered.
Testing the output will probably not be fun...

**Comment by inoas** [comment]
I am afraid adoption will lack if bake doesn't do it.
There could be a switch around the test case to use based on Configure::version() again, or the version could be statically set to 3.4 for the tests.

**Comment by markstory** [comment]
We can also use composer requirements :)
