### ISSUE TITLE
Why don't shell methods return?

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#295]
When baking a shell, the `main()` method is created, and it looks like the following.

```php
    /**
     * main() method.
     *
     * @return bool|int Success or error code.
     */
    public function main()
    {
        $this->out($this->OptionParser->help());
    }
```

However, when I run PHPCS with the CakePHP standard I get a warning, saying, that the function has no return so should be `@return void`. 

![PHPStormPHPCS](http://i.imgur.com/5G3qokv.png)

I'm not sure what the correct course of action is here, as the `out()` method does actually have the same docblock return.

**Comment by dereuromark** [comment]
Technically, returning null means here true from the implementation.
You could make a PR that also adds `|null`.

But I agree with you that it would be cleaner to expect either bool or int, and at the end such a method would return true :)
Same issue exists with actions.

For now, the PR with the doc block change might be the easiest solution in 3.x.
