### ISSUE TITLE
Plugin use wrong namespace when main project has custom namespace.

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/bake#300]
This [App\Controller\AppController](https://github.com/cakephp/bake/blob/master/src/Template/Bake/Plugin/src/Controller/AppController.php.ctp#L20) should use the App.namespace value instead being fixed.

**Comment by ADmad** [comment]
Would you like to submit a PR to fix it?

**Comment by alysson-azevedo** [comment]
I can fix the problem, but I forgot how to write tests (I've been 2 years away from php)

**Comment by markstory** [comment]
@alysson-azevedo If you fix the code, I can fix the tests :smile:

**Comment by markstory** [comment]
Closing as there is a pull request open now.
