### ISSUE TITLE
[Bake plugin] composer.json and unicode characters

### ISSUE THREAD

**Issue by jacricelli** [cakephp/bake#319]
Would it be possible to add **JSON_UNESCAPED_UNICODE** to the options passed to **json_decode()**?

https://github.com/cakephp/bake/blob/master/src/Shell/Task/PluginTask.php#L245

**Expected result**
```json
{
    "description": "This is a test.",
}
```
**Actual result**
```json
{
    "description": "Th\u00eds is a t\u00e9st.",
}
```

**Comment by markstory** [comment]
Sounds reasonable. Would you be willing to put a pull request together?

**Comment by markstory** [comment]
Closing as a pull request is up.
