### ISSUE TITLE
Bake multiple belongsTo associations to the same table

### ISSUE THREAD

**Issue by champidead** [cakephp/bake#339]
Hi,

First of all, thanks for Bake. I'm using it to generate my CRUD app from my SQL code and it is really useful.

I am surprised that multiple `belongsTo` associations to the same table is not handled by Bake. I think the problem comes from the naming convention that is therefore not respected.

Here is my example to reproduce the issue:
```
-- a simple list of types
CREATE TABLE frame_delivery_types (id INT AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (id));
INSERT INTO frame_delivery_types (name) VALUES ("Discard"), ("Deliver Conditionally"), ("Deliver Unconditionally");

-- a simple table that references three times the list of types
CREATE TABLE evcs (
    id INT AUTO_INCREMENT,
    name VARCHAR(255),
    PRIMARY KEY (id),
    ucast_frame_delivery_type_id INT,
    mcast_frame_delivery_type_id INT,
    bcast_frame_delivery_type_id INT,
    FOREIGN KEY (ucast_frame_delivery_type_id) REFERENCES frame_delivery_types (id),
    FOREIGN KEY (mcast_frame_delivery_type_id) REFERENCES frame_delivery_types (id),
    FOREIGN KEY (bcast_frame_delivery_type_id) REFERENCES frame_delivery_types (id)
);
```
At this point, a `bake all` will not handle correctly these three foreign keys. And it is not really convenient to edit each time all the templates generated to make the correction.

Why not introduce a new naming convention for this kind of association? For example, as in my example, we can prefix (or suffix or whatever) the field with a special value to distinguish the foreign key among the others.

Thanks.

**Comment by markstory** [comment]
We have talked about adding support for generating associations from foreign keys for a while but no one has taken the initiative to build it. I think generating associations based on foreign keys would help solve this problem too.

**Comment by champidead** [comment]
Hi @markstory, thanks for your answer.

Actually, generating an association from a foreign key works well. Here is an example:

```
-- a simple list of types
CREATE TABLE frame_delivery_types (id INT AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (id));
INSERT INTO frame_delivery_types (name) VALUES ("Discard"), ("Deliver Conditionally"), ("Deliver Unconditionally");

-- anoter simple list of types
CREATE TABLE vc_types (id INT AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (id));
INSERT INTO vc_types (name) VALUES ("Point-to-Point"), ("Multipoint-to-Multipoint");

-- a simple table that references three times the list of types
CREATE TABLE evcs (
    id INT AUTO_INCREMENT,
    name VARCHAR(255),
    ucast_frame_delivery_type_id INT,
    mcast_frame_delivery_type_id INT,
    bcast_frame_delivery_type_id INT,
    vc_type_id INT, -- new foreign key
    PRIMARY KEY (id),
    FOREIGN KEY (ucast_frame_delivery_type_id) REFERENCES frame_delivery_types (id),
    FOREIGN KEY (mcast_frame_delivery_type_id) REFERENCES frame_delivery_types (id),
    FOREIGN KEY (bcast_frame_delivery_type_id) REFERENCES frame_delivery_types (id),
    FOREIGN KEY (vc_type_id) REFERENCES vc_types (id) -- new foreign key
);
```

A `bake` will generate, just as expected:

**src/Model/Table/EvcsTable**

```
...
$this->belongsTo('VcTypes', [
            'foreignKey' => 'vc_type_id'
        ]);
...
```

**src/Template/Evcs/add.ctp**

```
...
echo $this->Form->control('vc_type_id', ['options' => $vcTypes, 'empty' => true]);
...
```
 
It is the generation of associations from multiple foreign keys to the same table that don't work.

**Comment by champidead** [comment]
Hi @markstory,

As I said, I thought about a naming convention that would integrate some prefix detection. It does not seem too hard to implement but, in the meantime, I noticed I just have to modify few lines in my model to get multiple foreign keys to the same table working. It is not that long to modify and hence there is no need for us to implement this naming convention for now.

Thanks.
