### ISSUE TITLE
CakePHP3.0.0 RC1: While baking the model Form Validation should applied as per the rules defined at Database  end.

### ISSUE THREAD

**Issue by ib-anurag-mishra** [cakephp/bake#34]
Hi,

if a column has defined as  'Unique', then 'validateUnique' rule should automatically applied while bake.
Please make it dynamic. It should  not only applied to fixed column names  'username', 'email' etc.

Also when  more than one column declared as  unique , then respective validations must also be applied while baking.

For example  

if I have declared collectively 'Column 1' and 'Column 2' and 'Column 3' as Unique, so respective validation should be automatically applied while bake.

**Comment by ib-anurag-mishra** [comment]
Hi,
Please refer:  https://github.com/cakephp/cakephp/issues/5802

Use RulesChecker::isUnique() which takes array of fields as argument.

**Comment by anuid28** [comment]
What if multiple fields collectively marked as 'Unique', For Example : 'first_name'  and  'last_name' fields may be marked as unique key at database end

**Comment by dereuromark** [comment]
Then there should be a unique rule across those together automatically.

**Comment by othercorey** [comment]
The validateUnique configuration still needs work for this I think.
