### ISSUE TITLE
Bake fixture should allow user to "munge" data from live DB

### ISSUE THREAD

**Issue by curtisgibby** [cakephp/bake#343]
When baking a fixture using the `-r` flag (i.e. `bin/cake bake fixture -r -n 3 Users`), it would be nice to be able to apply a callback to the generated data (i.e. the results of **FixtureTask::getRecordsFromTable()**) before you save it out to the fixture file. You could provide a class that would take the original results and return the munged data.

For example, you could have classes to:
- change email addresses from `joeuser@gmail.com` to `joeuser@mailinator.com`
- change credit card numbers from real CCs to valid fake test numbers like `4111111111111111`
- update specific columns based on a [Faker formatter](https://github.com/fzaninotto/Faker#formatters) instead of the real data

When I mentioned this idea to @steinkel at CakeFest, he thought that it made sense to use Events that the user could hook into to return the munged data.

**Comment by markstory** [comment]
I agree that events would likely be easier than a hook method.

**Comment by davidyell** [comment]
Couldn't this just be solved with Faker though? If you setup the Users id fields.
