### ISSUE TITLE
'cake bake people' is generating inconsistent code

### ISSUE THREAD

**Issue by bakroistvan** [cakephp/bake#346]
I have a people and cars table.
The cars table has a people_id column.

The `bin/cake bake people` generates the People model.
Looking at this: https://inflector.cakephp.org/Person
I think it should be called Person.

I am using cakephp 3.4.*

**Comment by bakroistvan** [comment]
At first I am not 100% sure about what should I expect.

If I am right the problem is with the
https://github.com/cakephp/bake/blob/master/src/Shell/BakeShell.php#L255

**Comment by cleptric** [comment]
I tried `bin/cake bake all people` and ended up with an `PeopleTable` and `Person` Entity, which looks fine to me.

**Comment by markstory** [comment]
@cleptric's results are correct.
