### ISSUE TITLE
Include MIT license by default for baked plugins

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#348]
We should add
https://github.com/cakephp/bake/blob/master/src/Template/Bake/Plugin/composer.json.ctp#L20

    license: MIT

by default
as most dont even know that there should be a license defined, and for most MIT suffices, for propriety and others they can just change it pretty quick.
This would prevent people from just by fun using AGPL or other not so suited default ones. 
Refs https://github.com/FriendsOfCake/awesome-cakephp/pull/271

**Comment by markstory** [comment]
Sounds reasonable to me.
