### ISSUE TITLE
"cake bake all"  should include 'empty' => true, 'default' => '' for date DEFAULT NULL fields

### ISSUE THREAD

**Issue by renardrouge** [cakephp/bake#35]
For a database field defined "date DEFAULT NULL" a user must currently modify the generated add.ctp and edit.ctp  code to include '    array('empty' => true, 'default' => '')     '  for the application to store correctly a NULL.

The current generated code is   echo $this->Form->input('date_of_birth');  and the result on Submit is to store the date displayed in the  'date_of_birth' panel.
![null_date_8](https://cloud.githubusercontent.com/assets/10366395/6032472/8b766dea-abd7-11e4-9207-1af11022bb2d.JPG)

A test case is produced by doing a "cake bake all users" on the following table.
CREATE TABLE IF NOT EXISTS users (	
  id			int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  username		varchar(254) NOT NULL,	
  user_email		varchar(254) NOT NULL,
  date_of_birth		date        DEFAULT NULL,
  UNIQUE KEY (username),
  KEY (user_email),
  PRIMARY KEY (id)
);

**Comment by dereuromark** [comment]
With the change of https://github.com/cakephp/cakephp/pull/6559 only `empty => true` is required to be added for DEFAULT NULL fields.

**Comment by renardrouge** [comment]
Thank you Mark !

A couple of months ago I began to look at the problem of "single quotes" 
not being rendered properly for the PDF code documentation.
It seems that a person who really knows the internals of LaTex could 
come up with a clean solution.
Unfortunately I was unable to understand where in LaTex such a change 
might be made.

I looked at the Jenkins logs trying to determine the process.  I am on a 
Windows 7 platform so I was unable to duplicate the process.

However I was able to come up with a crude solution which worked on my 
sample of one piece of auth.rst  code.
It consists of a PHP preprocessor which scans .tex code produced by 
rst2latex  for single quotes and substitutes the appropriate 
"\\textquotesingle".
The resulting .tex file was then run through a Windows pdfLaTex program 
to produce a correct representation of PDF code documentation.

I have attached that piece of preprocessor code.  If you think it has 
any merit as a solution it is yours to use as you see fit.

Best regards

Lorne

**Comment by dereuromark** [comment]
Are you sure you wanted to answer *this* issue? Your report looks totally off topic..

**Comment by renardrouge** [comment]
Sorry Mark !

I have been away from cakePHP work for a couple of months.
I neglected to notice that your email was tied to the particular github 
issue.
This relates to an old issue.
It was intended for your personal attention only, to do with as you please.

**Comment by DSchalla** [comment]
I will try to take care of this today.

**Comment by markstory** [comment]
Thanks @DSchalla
