### ISSUE TITLE
Error bake seed

### ISSUE THREAD

**Issue by Ashrafdev** [cakephp/bake#354]
![image](https://user-images.githubusercontent.com/14801084/28995368-294fb9aa-7a1a-11e7-8dd7-e88aa1430656.png)

- fresh install cakephp 3

**Comment by Ashrafdev** [comment]
you can try after fresh install cakephp 3 and bake seed .

**Comment by ADmad** [comment]
Duplicate of #353

**Comment by HavokInspiration** [comment]
The relevant PR has been merged a new release of migrations plugin have been made. This should be fixed now.
