### ISSUE TITLE
Dont skip array type for entity annotation

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#358]
Schema
```php
    'content' => [
		'type' => 'array',
		'length' => null,
		'null' => false,
		'default' => null,
		'collate' => 'utf8_unicode_ci',
		'comment' => '',
		'precision' => null,
		'kind' => 'column'
	],
```
as JSON data
Is currently skipped for bake
It should, however also be annotated as
```
@property array $content
```
Same for "json" type.

**Comment by dereuromark** [comment]
Same issue for "mediumtext and "longtext" in mysql as it seems.

**Comment by dereuromark** [comment]
I currently use a custom mapping on top here in the IdeHelper for the time being: https://github.com/dereuromark/cakephp-ide-helper/blob/master/src/Annotator/EntityAnnotator.php#L134

**Comment by markstory** [comment]
Are you overriding a column's type to be array?

**Comment by dereuromark** [comment]
A custom Json type is in place here which returns to the outside as array, yes.

**Comment by markstory** [comment]
Ok. I  agree it makes sense to handle json fields better. How would custom app mappings work?

**Comment by dereuromark** [comment]
See my linked PR for IDE helper. I used a simple key value pair.
