### ISSUE TITLE
bin/cake not listing bake shell

### ISSUE THREAD

**Issue by boindil** [cakephp/bake#36]
Executing ```composer require --dev cakephp/bake``` results in bake being cloned to /vendor/cakephp/bake, but bin/cake does not list the Bake-Shell. Probably this is the result of no Plugin folder being created in /plugins?

**Comment by markstory** [comment]
It could be that. Have you updated you app to require cakephp/plugin-installer. Also the plugin wont properly work until you include Plugin::load('Bake') as part of your bootstrap code.

**Comment by jadb** [comment]
@boindil - plugins you install using composer are not created in `plugins/` anymore, they are created in `vendor`, just like you noticed for `vendor/cakephp/bake`. 

However, as @markstory mentioned, you need to add `Plugin::load('Bake');` to [config/bootstrap_cli.php](https://github.com/cakephp/app/blob/master/config/bootstrap_cli.php#L20)

**Comment by boindil** [comment]
Aaah I see, after adding ```use Cake\Core\Plugin;``` and ```Plugin::load('Bake');```, it actually works :+1: 

thanks!
