### ISSUE TITLE
problem with hierarchy of namespace in plugin name

### ISSUE THREAD

**Issue by zoghal** [cakephp/bake#37]
when use problem with hierarchy of namespace in plugin name, baker generating incorrect any class of need used namespace
for example: plugin name is Rita/Users, baker generate entity class Similar this :
```
<?php
/* /Plugin/Rita/Users/src/Model/Entity/User.php */
namespace Rita/Users\Model\Entity;

use Cake\ORM\Entity;
```

**Comment by markstory** [comment]
I can take a look at this.

**Comment by DSchalla** [comment]
https://github.com/cakephp/bake/blob/master/src/Shell/Task/ModelTask.php#L642

The Namespace must be adjusted in case its a Plugin with vendor prefix, at least that is what seems to be the issue. A str_replace should fix that.

**Comment by markstory** [comment]
Closing as #38 has been merged.
