### ISSUE TITLE
Switch to Twig (plugin) for "bake" templating engine

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#371]
This will remove the issue with the current readability of the different "real" and pseudo php tags and how templating currently works.
It will hopefully also support the twig native  (IDE supported) logic pieces, like iteration and other things for highlighting, code auto complete etc.

We generate PHP files via PHP which is totally bad and needs hacking around with a unicorn solution.
So here it makes sense to completely switch to a true templating engine that is written in a different "language" so to speak.

See https://github.com/WyriHaximus/TwigView
and the really messy to read mix of <? and <% etc: https://github.com/cakephp/bake/blob/master/src/Template/Bake/Element/form.ctp

Refs https://github.com/cakephp/bake/issues/185

**EDIT FOR CLARIFICATION** This is only for the bake plugin templates to generate template files. The generated template files will still be .ctp PHP files. This is not part of the change here.

**Comment by steinkel** [comment]
I would suggest keeping the Twig engine as optional (possibly as the default engine) and keep the current templating engine (PHP) based maintained unless we can provide a fully automated migration script to upgrade people with existing CakePHP 3 projects.

While I can see the benefits of using a template engine like Twig, and I would definitely use it for new projects, existing projects would face the following (hard) issues:
* Migration of existing PHP based views to Twig
* Learning curve, we would need to learn another thing to work with the framework, increasing the initial entry barrier for new developers. This would apply for new projects too

Migration from version 2 to version 3 required a rewrite of the model layer in many cases, if we introduce a hard to migrate change in the view layer now, we'll increase the cost to keep these projects up-to-date to latest version.

**Comment by dereuromark** [comment]
> Learning curve

This is not an argument IMO, twig would probably be way easier to understand (thx to IDE, code-complete/highlighting and docs) than the current syntax that is 100% red underlined in any IDE^^

Sure can be optional until 4.x lands.

**Comment by inoas** [comment]
Note: *TwigView 5.0.0 will require minimum of PHP 7.0.0 due to Twig2 requiring it: https://github.com/twigphp/Twig/blob/2.x/composer.json#L30*

- I don't think we need a migration tool to auto-migrate `<%-bake` to twig-bake files. A tool like that will be hard to create and error prone and the output will be far form optimal.
- I do think we should keep the `<%-based engine` even in 4.x if it is not too much hassle.
- In CakePHP 4.0 the default should be the Twig based engine.

**Comment by steinkel** [comment]
I agree setting a better default, and we should provide a migration path to existing Cake3 working applications, even more after cake2 -> cake3 was already painful. 

For a team already familiar with the existing view layer, switching to a Twig based view layer will need "some" learning curve, even if this is beneficial for them on the long run, mastering it and finding "how do this in twig" takes time. It will be cool to have IDE code complete, docs and I'm happy to get this as an option, but forcing people to a heavy refactor in 4.x would not be nice.  (I can hear project managers crying in their caves)

At least we should provide a 'fallback' view layer that could handle existing (and working) views, allowing users to get familiar with Twig benefits during 4.x and removing this layer later.

**Comment by inoas** [comment]
Do you agree that removing the bake template but not the engine in 4.x would be a good compromise?

- Existing projects could then continue using the old style bake templates.
- New projects can create old style bake templates from scratch (or copy them from older bake versions) but it would be recommended to just use twig. And I can tell you, even for newbies and non-developers/designers, Twig is /much/ easier to use and we can run it in strict mode with error reporting and then you will know very precisely what you did wrong.

**Comment by markstory** [comment]
@dereuromark Are you proposing change only bake's templates to use Twig, or changing the *output* of bake to generate Twig templates instead of PHP templates?

**Comment by markstory** [comment]
@steinkel We've talked a bit in slack about having Twig be the default template system sometime in Cake 4.x. With that said it will likely not be 4.0.0, and the PHP templates would live for quite some time because migrating is hard and tedious and I don't want to force another big rewrite on people when we can do an incremental one instead.

With that said. I don't think our PHP  templates are a good idea long term. It is far too easy to accidentally make a XSS hole.

**Comment by ADmad** [comment]
> With that said. I don't think our PHP templates are a good idea long term. It is far too easy to accidentally make a XSS hole.

:+1:

**Comment by inoas** [comment]
> be the default template system sometime in Cake 4.x

Is there a reason to plan bigger changes mid-major-release cycles?

**Comment by dereuromark** [comment]
there is no XSS for bake, maybe you are mistaking the scope of the issue here :)
It is NOT about changing the templates for bake, they should STILL be .ctp PHP files.

This is only about using twig files for bake templates, nothing else.

**Comment by markstory** [comment]
> Is there a reason to plan bigger changes mid-major-release cycles?

When twig is added it would be a opt-in view layer, that would be 'defaulted' on for new applications. As for rationale, I don't want to push back the release date of 4.0.0 and make it a big splash. Instead I'd rather use 4.0 as a cleanup release, and then add new features incrementally throughout 4.x. Much like how we've used 3.x releases to add new features.

**Comment by inoas** [comment]
The XSS part is about the cake view template output (generated by bake) I assume.

**Comment by inoas** [comment]
Well @dereuromark we could reduce some work if the new bake engine (twig) would only generate twig output and not ctp *and* then also twig output. Other than that you are right, let's keep it separate.

**Comment by ADmad** [comment]
> It is NOT about changing the templates for bake, they should STILL be .ctp PHP files.

Yeah sorry, we hijacked this issue to discuss using Twig for core itself too :)

**Comment by dereuromark** [comment]
Core now is https://github.com/cakephp/cakephp/issues/11343 :) For all that want to discuss the other thing in more dept.

**Comment by steinkel** [comment]
Yeah I was confused about the title too
