### ISSUE TITLE
CakePHP3.0.0 RC1: While baking 'view' action, it should paginate all its hasMany relations (sorting and pagination)

### ISSUE THREAD

**Issue by ib-anurag-mishra** [cakephp/bake#39]
CakePHP3.0.0 RC1: While baking 'view' action, it should paginate all its hasMany relations (sorting and pagination)

-- You could provide ajax pagination on view action/page for sorting and pagination.

**Comment by dakota** [comment]
The default bake templates stay away from javascript/ajax implementations since everybody wants them done in very different ways. This would be trivial for you to implement in your own bake templates.

**Comment by ADmad** [comment]
Closing for same reasons stated by @dakota.

**Comment by ib-anurag-mishra** [comment]
Hi Dakoda,
I agree with you, however I think pagination (column sorting & pagination) should be there, same as  index pages {No ajax} for all hasMany associations/Listing displaying  on the view page.

Thanks

**Comment by DSchalla** [comment]
That is required for only a few cases, I personally don't think that hasMany relations will often reach a level where that would be required. 

You can easily implement that with own bake themes

**Comment by AD7six** [comment]
@ib-anurag-mishra if you want something, the right way to make that possible is to create a pull request - though as I mentioned in your other related ticket what you're asking for isn't in the scope of what we want bake to be. As mentioned above the right action to take is to create your own bake theme.

**Comment by ib-anurag-mishra** [comment]
Hi AD7six,

I can understand,  it is not an issue. I am asking/requesting for an enhancement.
As you guys expertise in this, I am requesting for this enhancement.

DSchalla   - Consider the case, One country has many users (10 lac), so in this case , pagination would be needed. This will also affect the page performance .

Team - Please do this enhancement in the bake default theme. This will save a lots of hours . Because I had asked many times by clients to  implement the same for all baked 'View' actions/page.

Thanks

**Comment by ADmad** [comment]
> Because I had asked many times by clients to implement the same for all baked 'View' actions/page.

Sounds like you want others to do your work for free for which you will be paid in return.

**Comment by DSchalla** [comment]
@ib-anurag-mishra *You* need the feature, why *you* don't implement it? The implementation is only required in edge cases and would be unnecessary for most users. My opinion at least.
