### ISSUE TITLE
bake all --everything fails with non-default connection

### ISSUE THREAD

**Issue by ewbarnard** [cakephp/bake#392]
There is a problem with the order of operations for "bake all --everything --connection xxx". In cakephp/bake/src/Shell/Task/ModelTask.php function bake() (around line 109), we bake the table, entity, fixture, and test.

The problem is that when baking the test, we go off looking for associations. The associations can be for models which have not yet been baked. Therefore at

cakephp/cakephp/src/ORM/Locator/TableLocator.php line 210:

`$connectionName = $className::defaultConnectionName();`

returns the default connection, because that model class ($className) has not yet been baked.

I can work around the issue by not baking tests/fixtures on the non-default connection. In ModelTask::bake(), between bakeEntity() and bakeFixture() (line 116), I can insert the following workaround:

```
if (array_key_exists('connection', $this->params) && ($this->params['connection'] !== 'default')) {
  // Associated models may not yet be baked so their default connection will be unknown
  return;
}
```

This is related to #250 but it's not the same issue. I suggest disallowing automatic generation of tests for "bake all everything" on the non-default connection. It's an edge case not worth taking up a lot of time. To do that, insert something like the above code but adding a check for "everything"; add a notice to BakeShell::all() near line 253 that tests/fixtures will not be generated; update documentation for bake all everything.

**Comment by markstory** [comment]
>  I suggest disallowing automatic generation of tests for "bake all everything" on the non-default connection. It's an edge case not worth taking up a lot of time. To do that, insert something like the above code but adding a check for "everything"; add a notice to BakeShell::all() near line 253 that tests/fixtures will not be generated; update documentation for bake all everything.

I think this is a good approach. With alternate connections is is hard to know the scope of 'everything'.

**Comment by ewbarnard** [comment]
Mark, I'll see if I can get a PR together by the end of this week.

**Comment by saeideng** [comment]
a PR merged about this issue
