### ISSUE TITLE
Annotate the ResultSetInterface for controller paginations

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#398]
Currently, the annotations look like this for a paginate call in a controller
```
@method \Cake\ORM\Entity[] paginate($object = null, array $settings = [])
```
or a concrete App\Model\Entity\MyEntity, of course, if available.

See https://github.com/cakephp/bake/blob/master/src/Template/Bake/Controller/controller.twig#L39

But in fact this should be annotated:
```
@method \Cake\ORM\Entity[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
```

otherwise toArray() will not be recognized on the result by the IDE and marked as yellow/not existent.

I will first update the IDE Helper here as the fixer for those already generated classes.

**Comment by chinpei215** [comment]
by the way does paginate() return Entity[] really? If it doesn't, I think it should be annotated as `\Cake\Datasource\ResultSetInterface` simply, even if it helps in foreach. Though I don't mind the IDE helper lies for auto-completion, I think raw baked templates should not lie.

**Comment by dereuromark** [comment]
The whole purpose of those docblocks in generated template is to fully allow CakePHP developers to quickly and reliably write CakePHP code.
This single line helps to auto-complete and type-hint those methods and properties in pretty much all modern IDEs. Who doesnt use one can also just ignore it :)
Either way those should be annotated as part of a rapid development framework to resolve part of the magic underneath and make it easier for especially beginners to work with the framework, its methods and functionality.

**Comment by dereuromark** [comment]
PS: both bake and the IdeHelper plugin rewrite it to the concrete entity class if existent :)
That then helps even more as the properties can then also be autocompleted and typehinted directly inside foreach loops in the controller scope.

**Comment by chinpei215** [comment]
but would not it suggest [] operator despite of ResultSetDecorator doesn't support it?

**Comment by dereuromark** [comment]
I do not follow. The type is necessary for the methods and properties of the base or concrete class to be annotated. As it is an array of those entities when you loop over it.

**Comment by chinpei215** [comment]
Would not there be any better annotations for Iterators, like Generics in Java? If no, I am ok, as it is a plugin.

**Comment by dereuromark** [comment]
Not in the scope of the current toolings. You are free to improve IDEs via plugins in general, but that is not what this here is about - or we in PHP can currently do.

**Comment by chinpei215** [comment]
OK.

**Comment by dereuromark** [comment]
PR open
