### ISSUE TITLE
CakePHP3.0.0 RC1: While baking 'view' action, if click  on 'edit'  link of listing of 'hasMany' relation, it should open a new browser pop up window for edit.

### ISSUE THREAD

**Issue by ib-anurag-mishra** [cakephp/bake#40]
CakePHP3.0.0 RC1: While baking 'view' action, if click  on 'edit'  link of listing of 'hasMany' relation, it should open a new browser pop up window for edit instead of navigating away from the actual  'View' page,  and there after validating and saving the records in that new browser window , it should close that browser pop window.

**Comment by rchavik** [comment]
:-1: on popup

**Comment by dakota** [comment]
Popup windows are in general a very bad design choice. If you really really want them, then you should implement them yourself in your own app/custom bake templates.

**Comment by ADmad** [comment]
Strike three.

**Comment by AD7six** [comment]
I recommend you to create your own bake theme, these kind of suggestions (this and your previous one) are not going to appear in bake itself.
