### ISSUE TITLE
Better requirePresence default

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#412]
The tables get generated with validatioDefault of
```php
        $validator
            ->scalar('author')
            ->requirePresence('author')
            ->notEmpty('author');
```
etc.

But 
```php
        $validator
            ->scalar('author')
            ->requirePresence('author', 'create')
            ->notEmpty('author');
```

Would be a more sane default (generated by bake), as it would allow updates to pass also when only changing e.g. status field.
With this patching would always fail for partial updating - which is not a good default IMO.

**Comment by markstory** [comment]
Sounds like a reasonable change :+1:

**Comment by dereuromark** [comment]
Yeah, especially since the not null constraints on DB level are only relevant for fresh inserts.

**Comment by dereuromark** [comment]
Hm, I must have been using some other version or alike.
Running it now I cannot reproduce - closing then.
