### ISSUE TITLE
OptionParser generate description with ReflectionDocBlock to keep DRY

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/bake#417]
When I create new `shell` / `task` method I usually write some phpdoc and then I add same description to the `getOptionParser` for the subcommand, which is not DRY (adding same thing 2x).

Would it be good idea to generate default help for subcommand by https://github.com/phpDocumentor/ReflectionDocBlock from the method summary when available?

Something like

```
public function getOptionParser()
{
    $parser = parent::getOptionParser();
    $parser->addSubcommand('sound', [
           'help' => $docblock->getSummary(); // not needed, would be default
    ]);
    return $parser;
}

/**
* Makes some noise
**/
public function sound()
{
}
```

**Comment by markstory** [comment]
Are you proposing that the default `help` for all commands be generated from the doc block? That sounds like it might be more of a CakePHP console feature than bake.

**Comment by LubosRemplik** [comment]
I am and you are right, the issue should be submitted in cakephp/cakephp. Do you think it is good idea or nonsense? If it sounds OK, will submit issue there and think about possible PR :)

Closing issue as I submitted on wrong place :)

**Comment by markstory** [comment]
I think it is a reasonable default value. I would prefer an implementation that doesn't add additional dependencies though.
