### ISSUE TITLE
baking Fixture with a custom JSON data type

### ISSUE THREAD

**Issue by chrisch-hh** [cakephp/bake#419]
**What I did**
Baked a fixture by importing records from my database, which includes a JSON data type field. My database doesn't support a native JSON data type, so I've included CakePHPs predefined JSON data type according to the documentation with:

```
// In config/bootstrap.php
use Cake\Database\Type;
Type::map('json', 'Cake\Database\Type\JsonType');

// In src/Model/Table/UsersTable.php
use Cake\Database\Schema\TableSchema;

class UsersTable extends Table
{
    protected function _initializeSchema(TableSchema $schema)
    {
        $schema->columnType('preferences', 'json');
        return $schema;
    }
}
```

**What happened**
After baking the fixture with record import, the fixture looks something like this:

```
public $fields = [
    'id' => ['type' => 'integer', 'length' => 10, 'unsigned' => true, 'null' => false, 'default' => null, 'comment' => '', 'autoIncrement' => true, 'precision' => null],
    'preferences' => ['type' => 'text', 'length' => null, 'null' => true, 'default' => null, 'collate' => 'utf8_general_ci', 'comment' => '', 'precision' => null],

public $records = [
    'id' => 1
    'preferences' => array(
        'someKey' => 'someValue'
    )    
]  
```
When running tests against this fixture, I'm getting an exception:
`Exception: Cannot convert value to string in \cake\vendor\cakephp\cakephp\src\Database\Type\StringType.php, line 52`

This happens obviously because the array in the record cannot be converted to a string.

**What I expected to happen**
I would expect that the Bake detects the JSON column type definition and 

- set the **type** in the Fixture's $fields property to 'json' instead to 'text'. With 'type' => 'json' the tests are working.

- or store the JSON data in the record as a JSON string and not as an array

**Comment by markstory** [comment]
How are you generating the fixture with bake? Are you creating the fixture with `bake fixture` or `bake model`?

**Comment by chrisch-hh** [comment]
I use `bake fixture users -r` to bake the fixture and import some test records from the database.

**Comment by markstory** [comment]
Pull request open now.
