### ISSUE TITLE
Support of bake templates inside a plugin

### ISSUE THREAD

**Issue by frankvanhest** [cakephp/bake#423]
Hi, 

Currently I've created a bake theme for our custom plugin. It would be great if you could just include the bake templates inside the plugin. The path would be `plugins/<name>/src/Template/Bake`.
By looking at the ControllerTask in the bakeController method, you could just check if there is a plugin given in the bake command and use that one like `$this->BakeTemplate->generate($this->plugin . 'Controller/controller')`. This seems to work, but of course a more generic solution is more elegant.
Is it an idea to create this concept? I would be happy to provide the code for it.

Cheers,

Frank

**Comment by markstory** [comment]
Isn't this very similar to [bake themes](https://book.cakephp.org/3.0/en/bake/development.html#creating-a-bake-theme)?

**Comment by frankvanhest** [comment]
Not quite. For example, I have a plugin called Foo. I want specific controller bake templates for this plugin. Now I would have to create another plugin FooTheme for the bake templates. I feels a bit of an overkill to create an extra plugin just to add a specific controller bake template for the plugin Foo. 
My proposal is that the bake templates specific for our example Foo are located within this plugin.
I hope this clarifies my idea a bit.

**Comment by ADmad** [comment]
> Now I would have to create another plugin FooTheme for the bake templates

No you don't. You can just have put the bake templates in `Foo` plugin itself inside `src/Template/Bake/` and then baking specify `--theme Foo` option.

**Comment by frankvanhest** [comment]
@ADmad Ah, so that is the way to do it. Thanks you!
