### ISSUE TITLE
Expression is not allowed as field default value

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#425]
# What I did
Installed bake `1.6.2` into my project and generated a migration against my Packages table.

```bash
$ bin/cake bake fixture -n 1 -r Packages
```

# What happened
My fixture was baked successfully.

# What's wrong?
I opened my fixture in PHP Storm and was presented with the following. Which PHP Storm says is `Expression is not allowed as field default value`

![PHP Storm error](https://i.imgur.com/gTmxluU.png)

When I remove the call to `Cake\I18n\FrozenTime::__set_state()` the errors go away and I can run my tests.

If you try and execute a test with a baked fixture, the test throws a fatal.

```bash
PHP Fatal error:  Constant expression contains invalid operations in /tests/Fixture/PackagesFixture.php on line 52
```

**Comment by davidyell** [comment]
If it adds anything, the `exit_links` dimension of the data is created using contain in a plugin behaviour. As it's a dynamic attachment.

**Comment by markstory** [comment]
Looks like we should be converting those timestamps into string values.

**Comment by dereuromark** [comment]
> I'm wondering if another solution would just be to have Bake set $records in init() instead of when defining the property

That sounds like a great idea, would also allow other more "runtime/dynamic" things out of the box.
The hardcoded property is a bit outdated these days.

**Comment by markstory** [comment]
I'm on-board if we want to start generating new fixtures to use the method based approach. Is anyone interested in putting a pull request together for that?

**Comment by ethanpooley** [comment]
This is basically what we did, but I don't feel at all qualified to say what the repercussions might be for widespread adoption. If this is pretty much it I can certainly PR it for us.

![screenshot from 2018-03-08 17-11-24](https://user-images.githubusercontent.com/856884/37185162-de317fca-22f3-11e8-8724-e9ebfbd1a626.png)

**Comment by dereuromark** [comment]
PR open.
