### ISSUE TITLE
Model TestCase fixtures

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/bake#427]
When you bake Model Table Test, it bakes `$fixtures` property with all possible fixtures depending on associations. Sometimes there are too many and I think by default it could bake just fixture for the table itself, for example for `PostsTableTest` it would bake 

```
public $fixtures = [
    'app.posts'
];
```

I am thinking about this because once I bake something, I have to remove fixtures otherwise phpunit test fails 

What do you think?

**Comment by dereuromark** [comment]
Let's compromise: At least only the own model and direct relations.
All fixtures are really too much, I agree. Always have to delete 80+ of the 84 etc.

**Comment by LubosRemplik** [comment]
So I would just delete lines from https://github.com/cakephp/bake/blob/master/src/Shell/Task/TestTask.php#L446 to the end of the method, but I think you would just not call the processModel recursively?

**Comment by markstory** [comment]
> Let's compromise: At least only the own model and direct relations.

👍 to this if we're going to make a change.

**Comment by dereuromark** [comment]
@LubosRemplik Give it a try.
