### ISSUE TITLE
Cannot install the Bake and ORM projects only

### ISSUE THREAD

**Issue by lllopo** [cakephp/bake#441]
I'm planning to use CakePHP/ORM subproject as standalone ORM layer for writing Joomla components and it works fine more or less. Unfortunately, when I tried to install the Bake project with composer, it failed. Is there a way to use the Baker with the ORM project standalone or a full CakePHP is absolutely required ?

**Comment by lllopo** [comment]
Yeah, I can also setup a side cake copy and just build the models there as a workaround, then move them to the right place. Since the baker can do models only too, I thought it is eventually possible to use it this way, though. It's a pity it can't. Thanks for your answer anyway.

**Comment by ADmad** [comment]
> Unfortunately, when I tried to install the Bake project with composer,

How exactly did it fail? One should be able to add bake as a dev dependency even in non cake projects, it will just pull in full cake as it's dependency.

**Comment by lllopo** [comment]
![untitled](https://user-images.githubusercontent.com/5485902/39582599-f297e06a-4ef6-11e8-94d1-400e925cc5f2.png)

Failed like this. Sorry it's a screenshot, but I cannot copy from where I got it.

**Comment by ADmad** [comment]
In an empty folder/project i ran `composer require cakephp/orm` followed by `composer require --dev cakephp/bake` and did not get any errors.

**Comment by ADmad** [comment]
Following sequence doesn't cause any issues either:

```
composer require cakephp/orm
composer require cakephp/cache
composer require --dev cakephp/bake
```

**Comment by ADmad** [comment]
Sorry that we can't help you get around Joomla's weird folder structure and/or autoloading practice.

**Comment by lorenzo** [comment]
@lllopo installing the ORM by itself is definitely possible, but I don't think bake was made to be installed outside a cakephp applications, since its purpose is to create classes for a cake application following conventions.
