### ISSUE TITLE
Use column comments from database for entity annotation

### ISSUE THREAD

**Issue by dmromanov** [cakephp/bake#442]
It would be great if Bake was using column comments from a table in a database for annotating an Entities' properties.

**Comment by dereuromark** [comment]
They would need to be stripped/sanitized to avoid chars accidentally breaking the doc blocks.

**Comment by dereuromark** [comment]
Is someone interested in making a PR here?

**Comment by dmromanov** [comment]
I am interested but currently can not give any estimates.

**Comment by ravage84** [comment]
@dmromanov could you show us an example of how it could look and behave? What is the scope of this feature. How far do you want to go?

**Comment by dereuromark** [comment]
It should not be too difficult to PR this.
Do you want to try it?

**Comment by dmromanov** [comment]
This feature is on my list, but I can not give any estimates.

**Comment by ravage84** [comment]
@dmromanov thank you for your explanation. I stand with my counter-arguments on this feature as mentioned in https://github.com/cakephp/bake/issues/465#issuecomment-428910084.

But if we are going to implement this feature into bake directly and not as an extension as mentioned by @dereuromark in https://github.com/cakephp/bake/issues/465#issuecomment-439724532, I would prefer this behavior to be optional. For example activatable through a CLI parameter and/or an interactive question.

**Comment by dereuromark** [comment]
I would rather go away from interactive or CLI towards the global config. That is way cleaner in terms of consistency in the project as well as easier to use for CLI typing (annoying to type out all of them).
I said that before numerous times. The current config hell via CLI is already a PITA and pitfall.
But then, this would be an easy to opt-in feature :)

**Comment by dmromanov** [comment]
Opened a PR.
