### ISSUE TITLE
3.6: Bake command

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#443]
https://book.cakephp.org/3.0/en/console-and-shells/commands.html

the new "shells"

**Comment by markstory** [comment]
This is a big pile of work but something that should be done :+1:

**Comment by dereuromark** [comment]
buildOptionParser() should be protected in the docs.
Also, the Command method here is protected, but the generated (baked) code is public visibility.
 
We should also bake it protected IMO, just as the parent. No need to make it visible beyond the internal scope.

**Comment by dereuromark** [comment]
Docs fixed in https://github.com/cakephp/docs/pull/5820
