### ISSUE TITLE
Inconsistent naming of baked test class and an actual class

### ISSUE THREAD

**Issue by dmromanov** [cakephp/bake#445]
CakePHP 3.6.2
Bake 1.7.3

## Steps to reproduce

Bake a class. Name of the class should have a suffix, same as the baking type.
`$ ./bin/cake bake shell TestShell`

```
Creating file .../app/src/Shell/TestShellShell.php
Wrote `.../app/src/Shell/TestShellShell.php`

Baking test case for App\Shell\TestShell ...

Creating file .../app/tests/TestCase/Shell/TestShellTest.php
Wrote `.../app/tests/TestCase/Shell/TestShellTest.php`
```
## Expected

Class file and test file should be named the same: either `TestShellShell` & `TestShellShellTest` or `TestShell` and `TestShellTest`

## Actual result

Resulting test file has a different name and referrers to incorrect class: `TestShell` instead of `TestShellShell`.

**Comment by dereuromark** [comment]
This is somewhat an edge case. Usually you wouldnt add the Shell suffix on the input, to avoid the suffix to be doubled.
But yeah, this could easily be fixed.
Are you interested in making a PR with a suggested fix?

**Comment by dmromanov** [comment]
I am interested but currently can not give any estimates.

**Comment by ADmad** [comment]
Closing as this is an edge case which no one seems interested in fixing.
