### ISSUE TITLE
Incomplete PHPDoc in controller on bake

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/bake#451]
When bake controllers I get a warning from PHPStorm that is missing the "@throws\Aura\Intl\Exception" PHPDoc declaration. Not a error, but I wanted to share it with the community..

**Comment by markstory** [comment]
Where does PHPstorm think that exception annotation should be placed?

**Comment by dereuromark** [comment]
You need to fix phpstorm here IMO. Those should only be placed and required on primary level.
0 that is for this IDE.

**Comment by dereuromark** [comment]
As discussed this is more likely a setting to fix in phpstorm.
Adding those to the controller doesnt bear any additional value (those should also not be caught).
