### ISSUE TITLE
Incorrect behaviour baking model

### ISSUE THREAD

**Issue by DinoSane** [cakephp/bake#452]
https://github.com/cakephp/bake/blob/1e54dd0695925215796322318fb056147b3fd2d8/src/Shell/Task/ModelTask.php#L428

Show be something like this instead:
if (!in_array($fieldName, $primaryKey) && (strtolower($fieldName)  === strtolower($foreignKey))) {

I have a table contracts (Windows does bother much about uppercase) and in a associated table I have the field Contract_id which is not properly recognize by bake due this lower/upper case difference.

The current code evals if "contract_id" === "Contract_id"

**Comment by dereuromark** [comment]
If you chose to violate the conventions there is nothing bake can do.
contract_id would be the correct field name. Then it also works as expected.
We cant just make it all switching cases everywhere as this will create other issues.

**Comment by markstory** [comment]
Your fields don't match the conventions that bake supports. I'd rather us stay consistent than add exceptions piecewise.
