### ISSUE TITLE
Baked callbacks need proper annotations

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#456]
Refs https://github.com/dereuromark/cakephp-ide-helper/issues/86

```php
/**
 * ...
 * @param \App\Model\Entity\Post $entity The entity that is going to be saved
 * ...
 */
public function beforeSave(Event $event, EntityInterface $entity, ArrayObject $options)
```

The callback typehints can't just be changed, also for extendability.
But then at least the doc block annotations must refer to the concrete object where existing. 
Otherwise, you are not allowed to use any property or custom method of the entity inside the callbacks, which is not practicable. 

Should this stay an ide helper improvement? Or can/should be bake here properly from the start?
I think we are already using the same logic in other places:

        $entityClass = sprintf('%s\Model\Entity\%s', $namespace, $entityClass);
        if (!class_exists($entityClass)) {
            $entityClass = EntityInterface::class;
        }

The fallback is easily applicable here, too.

**Comment by dereuromark** [comment]
I included this for now into the IdeHelper via https://github.com/dereuromark/cakephp-ide-helper/pull/88
So no immediate need for this in bake now, as this can be done async afterwards easily.
Maybe this can be closed then for now?

**Comment by markstory** [comment]
I think this makes sense to do in bake. Would we potentially run into phpcs errors because the doc string and typehint don't match?

**Comment by dereuromark** [comment]
Not with the right ruleset. It often happens that the type is customized. The variable must match at least.
