### ISSUE TITLE
Wrong Exception

### ISSUE THREAD

**Issue by mctom987** [cakephp/bake#462]
Should this not be RecordNotFoundException like the others?
https://github.com/cakephp/bake/blob/73073c27eb599d2aa7155472dd465d210ac782eb/src/Template/Bake/Element/Controller/edit.twig#L25

**Comment by markstory** [comment]
@mctom987 Yes it should.

**Comment by saeideng** [comment]
@mctom987  I created a PR with your commit https://github.com/cakephp/bake/pull/473
