### ISSUE TITLE
Use bake without cake

### ISSUE THREAD

**Issue by elboletaire** [cakephp/bake#492]
I know it can't be done currently (the plugin does not have a `bin` section in composer, so there's no way to install it globally right now), but I think it could be a nice feature to be able to have bake installed system-wide. 

The only problem is that the only feature which would not require a full cakephp installation, is plugin scaffolds (that's why I'm opening this, because I wanted to create a plugin without creating an empty project where use bake).

So here's my question/issue:

Would it really make sense to allow this? Are there other reasons, a part from creating plugin scaffolds, to do so? If not, I understand this would be a very big change for such a small improvement.

Also, if there's currently some way to do it (a part from cloning scaffolds like the usemuffin one), I'm open to proposals! :sweat_smile:

**Comment by dereuromark** [comment]
Whats the use case?
The whole thing is very tightly coupled to Cake as framework
See also https://github.com/cakephp/bake/blob/master/composer.json#L22 as hard dependency - and tight coupling to core everywhere.

I think this is not relevant for now
If you want to create a generic bake tool, it should be a separate project.

**Comment by elboletaire** [comment]
The only use case I can think of is creating plugin scaffolds. My idea was to be able to create a plugin without the need to create an empty project. So, right now, if anyone wants to create an empty plugin with bake (as is), and outside of cake, has to do something like:

~~~bash
composer create-project --prefer-dist cakephp/app temp-project
cd temp-project
bin/cake bake plugin MyAwesomePlugin
mv plugins/MyAwesomePlugin ..
cd ..
rm -frv temp-project
~~~

And, what I'd liked to do, was:

~~~bash
bake plugin MyAwesomePlugin
# which would create MyAwesomePlugin folder with all its contents
~~~

As I already said, if this is the only use case, ofc it's non-sense to do such amount of changes only for this; that's why I was also asking if anyone has an alternate method to bootstrap plugins.

BTW what I'm doing right now is using the `Muffin/Skeleton`, and I guess that's the best approach to do what I want, right?

**Comment by elboletaire** [comment]
I close it, as obviously the `Muffin/Skeleton` option seems the more obvious here.

Although I'd like to clarify.. I create plugins inside projects because bake forces me to, but when creating plugins which will end in packagist.. I prefer to develop them outside of the project (and import them as vendors, which is what I'll end up doing at the end). That's why I use the Muffin/Skeleton generator instead of bake inside a project.

**Comment by dereuromark** [comment]
Tip: You can create them into /plugins and just copy and paste the folder content into its own git repo then easily.
No need to overengineer :)

**Comment by elboletaire** [comment]
Yeah but the think is to work without the entire cakephp core. I usually create plugins (ala TTD), and then include them directly as composer packages.

**Comment by dereuromark** [comment]
We all to the same. My point is: It can easily be done given the already present things.
