### ISSUE TITLE
Bake mistakenly thinks composer dump-autoload failed

### ISSUE THREAD

**Issue by sitedyno** [cakephp/bake#51]
Baking a plugin I see this at the end:
> Found composer executable in /usr/local/bin
> Running php '/usr/local/bin/composer' dump-autoload
> Error: Could not run `composer dump-autoload`: Generating autoload files

Composer does write to stderr: https://github.com/composer/composer/blob/master/src/Composer/Command/DumpAutoloadCommand.php#L60

The autoloader is updated as I can see the namespaces added to vendor/composer/autoload_psr4.php

**Comment by markstory** [comment]
Writes to STDERR, everything OK :cry:

**Comment by ceeram** [comment]
Recently changed in composer: https://github.com/composer/composer/pull/3715

<info> output should not go to stderr :(

2015-03-03 23:34 GMT+01:00 Mark Story <notifications@github.com>:

**Comment by sitedyno** [comment]
The choice to send info to stderr aside, shouldn't the return value of proc_close() be used to determine success or failure?

**Comment by dzuelke** [comment]
Welcome to Unix, where the success or failure of an operation has been indicated through an application's exit code since the 1960s. Output on the standard error stream does not mean an error occurred.

**Comment by josegonzalez** [comment]
@dzuelke Like I said in the composer thread, we're definitely going to change this to not depend upon stderr (it was a bug to do so) but I still think composer should not just arbitrarily write status messages to stderr without some notion of debug/warning/info/etc log levels.

**Comment by dzuelke** [comment]
@josegonzalez Composer is a console app... If you want more verbosity, use `-v`, if you want less, `-q`, that's what most of those do.

IMO it might be useful for "composer install" to write the installed packages to `stdout` at the end as a summary of some kind, but that's another story.

**Comment by markstory** [comment]
@sitedyno @dzuelke Yes, I should have used the sub-processes' exit code. That's the change I was planning on making :smile:

**Comment by markstory** [comment]
Closing as a pull request is up now.
