### ISSUE TITLE
Cake 4 - Baked fixtures have mismatched method signatures

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#522]
## What I did
Created some database tables and used `bin/cake bake model all`

## What happened?
The `init()` method was highlighted by PHP Storm for not matching the `TestFixture` method signature.

https://i.imgur.com/mm1WR9i.png

**Comment by davidyell** [comment]
This is using `"cakephp/bake": "4.x-dev"` :)

**Comment by dereuromark** [comment]
PR https://github.com/cakephp/bake/pull/525 open
