### ISSUE TITLE
Cake 4 - Update newEntity

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#523]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-alpha1
* Platform and Target: PHP 7.3.2

### What you did
I baked a controller for my `Questions` table.

### What happened
The `add` method baked with the following line
```php
$question = $this->Questions->newEntity();
```

This throws an exception, because the method requires a param.
```
Too few arguments to function Cake\ORM\Table::newEntity(), 0 passed in /Users/davidyell/Sites/CakePHP4/src/Controller/QuestionsController.php on line 51 and at least 1 expected
```

### What you expected to happen
I thought that bake would use `newEmptyEntity()`

**Comment by dereuromark** [comment]
Can you open a PR for it?

**Comment by ADmad** [comment]
PR up.
