### ISSUE TITLE
Better requirePresence detection

### ISSUE THREAD

**Issue by Ali1** [cakephp/bake#531]
I've only used MySQL, so forgive the narrow view.

But currently, a `requirePresence` rule is baked in for fields that aren't nullable. This is regardless of whether a default field value is set for the column in the database.

I feel it makes more sense if `requirePresence` is baked only for fields that aren't nullable AND don't have default value set for the column.

Would be consistent with MySQL Strict Modes. In strict, MySQL would require a field's presence on create if no default value is set for the column otherwise it generates an error. This seems quite intuitive. It encourages developers to set a blank default value when the field's presence is not required when creating the table - ensures developers define their intention for that column at database level.

Thoughts?

**Comment by dereuromark** [comment]
I ran into the same issue!

**Comment by Ali1** [comment]
```
            if ($metaData['default'] === null) {
                $validation['requirePresence'] = [
                    'rule' => 'requirePresence',
                    'args' => ["'create'"],
                ];
            }
```
I was thinking something to wrap the creating of requirePresence with this in a PR. Which branch should I use?

**Comment by dereuromark** [comment]
You can do this for master, it will be ported to 4.x then as well.

**Comment by dereuromark** [comment]
PR open
