### ISSUE TITLE
Return value ModelCommand::getDisplayField() must be of the type string

### ISSUE THREAD

**Issue by ava007** [cakephp/bake#544]
### Environment

CakePHP 4.x (latest development version 2019-05-10)
Bake 4.x (latest development version 2019-05-10)
PHP 7.3.5

### What I did
bin/cake bake model images

### What I got
Exception: Return value of Bake\Command\ModelCommand::getDisplayField() must be of the type string, null returned in [...vendor/cakephp/bake/src/Command/ModelCommand.php, line 486]

**Comment by dereuromark** [comment]
PR open
