### ISSUE TITLE
Max length rule baked without a length

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#551]
## Environment
* PHP 7.3.5
* CakePHP 3.7.5
* Bake 1.9.6

## What I did
I baked a Table class and entity for my Upsells database table.

## What happened?
The following validation rules were baked out for me.

```php
        $validator
            ->add('name', 'scalar', ['rule' => 'scalar'])
            ->add('name', 'maxLength', ['rule' => 'maxLength'])
            ->add('name', 'requirePresence', ['rule' => 'requirePresence'])
            ->add('name', 'allowEmpty', ['rule' => 'allowEmptyString']);
```

When I baked my template files I got the following notice
`Notice (8): Undefined offset: 0 [CORE/src/View/Form/EntityContext.php, line 473]`

Which happens to be for the max length rule, because no length was supplied.
https://github.com/cakephp/cakephp/blob/master/src/View/Form/EntityContext.php#L473

## What did you expect to happen?
I thought that bake would detect the length of the database field and apply that to the validation rule, and bake a rule like the following.

`->add('name', 'maxLength', ['rule' => ['maxLength', 255]])`

**Comment by cleptric** [comment]
I just created fresh app with CakePHP 3.7.7. Bake version is 1.9.6 as well.
My username is set as a VARCHAR 255, ALLOW NULL is false.
I got this result

```
        $validator
            ->scalar('username')
            ->maxLength('username', 255)
            ->allowEmptyString('username', false);
```

**Comment by davidyell** [comment]
The issue here seems to be my accidental inclusion of a bake theme into my bake command.

Apologies, I will resolve this.
