### ISSUE TITLE
4.x - Fail nicely when missing a table

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#554]
## What you did
`bin/cake bake template --theme CakeBootstrap --prefix Admin Questiojs`

## What happened?
`Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cakephp4testing.questiojs' doesn't exist in [/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 134]`

## What you expected to happen
I would think this could output a more concise error message, rather than a PDO exception.

**Comment by ADmad** [comment]
The current error message clearly conveys what the problem is, that's what error messages should do.

**Comment by markstory** [comment]
The current error message 'works' but it could be simpler/better.

**Comment by davidyell** [comment]
Does it really need an entire stack trace output to the console. I don't
think so

**Comment by davidyell** [comment]
Hopefully this screenshot will illustrate my issue a bit more clearly. I think this is too much output for a 'Missing table' error.

https://i.imgur.com/qtpM2ar.png

**Comment by dereuromark** [comment]
I agree that usability could be improved. If you want you can make a PR here.

**Comment by dereuromark** [comment]
PR https://github.com/cakephp/bake/pull/556 open
