### ISSUE TITLE
Allow cake bake of controllers to switch between web and API template

### ISSUE THREAD

**Issue by liaogz82** [cakephp/bake#555]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.7.
* Platform and Target: LAMP STACK.

### What you did
As usual I run command `bin/cake bake controller [NAME]`.

### What happened
It bakes the usual controller CRUD commands but I am building an API services. I ended up redoing all the functions in the controller but retaining all the scaffolding function names.

### What you expected to happen
It performs as expected, but I was hoping for `bin/cake bake controller api [NAME]` so as to indicate that I am building an API using cake framework, hence doing away the need of Flash and Redirect component in the controller while baking

**Comment by liaogz82** [comment]
I can give this a shot. Any materials on how to build a CakePHP plugin?

**Comment by markstory** [comment]
@liaogz82 You can use `cake bake plugin` to get a plugin skeleton generated to get you started.

**Comment by liaogz82** [comment]
and how do I do hello world in the command line interface?

**Comment by markstory** [comment]
You can use bake to generate a command `cake bake command MyPlugin.MyCommand`. However, for a bake theme you mostly need to build new templates.

**Comment by liaogz82** [comment]
you guys like to use the word `template`. what are those anyway?

Please help me as a lot of my projects are API based so developing this plugin will help a lot

**Comment by markstory** [comment]
@liaogz82 bake uses twig templates to generate the php code it creates. For bake to generate API specific controllers you would need a new set of templates that create the controller actions needed for an API endpoint.

**Comment by dereuromark** [comment]
And then you just create a plugin that ships with those, see other plugins that contain custom bake templates.
They should then show up in your bake console as option to chose from if you enabled your plugin.

Closing this then as the rest is now support topic and can be solved via slack channel, forum or other help resources.
