### ISSUE TITLE
Bake Api And Authentication enhancement

### ISSUE THREAD

**Issue by lpj145** [cakephp/bake#562]
Hey bakers, nice to talk yours, many i'be downlaod cake and think, why bake don't have a command to add default Authentication and Authorization or implementation of Rest api mode ?

Why yours think about it ?

**Comment by markstory** [comment]
@lpj145 I think a lack of time has been the main factor in why those features haven't been implemented yet. Wiring up authentication and authorization sounds like something that could be done inside the application skeleton. However, generating rest endpoints is something bake could do but hasn't been built yet. #555 is the most recent related issue.

**Comment by lpj145** [comment]
@markstory i think some features sounds cool to bake or to authentication plugin, community have interest in more commands ? why you list all necessities on thread ? bake or plugins have style guide to contributors ?

**Comment by lpj145** [comment]
i make skeleton here: https://github.com/lpj145/cake_jwt maybe it should be better, but, with docs have now i can make it easily and work as expected with unit tests.

**Comment by dereuromark** [comment]
This can be an extra plugin extension on top.
