### ISSUE TITLE
Baking a fixture with custom data type generates invalid SQL

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#567]
# Environment
* CakePHP 3.7.9
* Bake 1.9.6
* PHP 7.3.6

# What I did
`bin/cake bake fixture Calls`

This generated my fixture file as normal. Then I implemented this into my integration test using `public $fixtures = ['app.Calls']`.

I have a custom data type set to a field in this table, configured in the Table class.

# What happened
My test failed because the SQL generated from the fixture was invalid. This was because the fixture had created a schema setup of the following.
`'telephone_number' => ['type' => 'telephone', 'length' => 255, 'null' => false, 'default' => null, 'collate' => 'utf8mb4_general_ci', 'comment' => '', 'precision' => null, 'fixed' => null],`

This obviously fails as `telephone` is not a valid data type for MySQL.

**Comment by markstory** [comment]
How should bake find out the column type when the model has mapped the column to a custom type?

**Comment by davidyell** [comment]
I would assume a string. As it'll store almost any data type.

**Comment by ADmad** [comment]
`TypeInterface` does have `getBaseType()` method. Could we leverage that (assuming dev has setup proper base type)?

**Comment by davidyell** [comment]
I like that solution @ADmad could we enforce that method in userland code somehow? I notice it's in the interface, and implemented into `Type`.

Would it be worth creating an AbstractClass for userland types to inherit from to ensure the method exists? Or is that almost too much change to the core for what is essentially an edge-case?

**Comment by markstory** [comment]
Updating the docs for custom types and having fixtures use it when creating schema sounds like a good solution. Custom types would still be included in fixture $fields and schema generation would be dependent on the base type defined in the type class.

**Comment by chrisch-hh** [comment]
Any news about this?

I'm using a custom data type `OrderedUuid` which extends `BinaryUuid`. Baking the fixtures gives me:

```
public $fields = [
 'uuid' => ['type' => 'ordereduuid', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null]
...
]
```
Running tests isn't possible due to SQL error. The generated SQL for table creation looks like this:

```
CREATE TABLE `myTable` (
 `uuid` NOT NULL
...
)
```
Obviously the data type is missing in this statement. It should be BINARY(16) in my case. 

Is there a way to define the data type?

**Comment by markstory** [comment]
> Is there a way to define the data type?

Not right now there isn't which is the source of this problem. Type mappers don't know and can't reasonably know about their storage data type as storage types are dialect specific. The schema dialects that convert abstract types into dialect specific ones are not aware of custom types. We might be able to solve this by adding an interface that allows type classes to define a 'parent's abstract type that they use for storage.

**Comment by chrisch-hh** [comment]
For those who might be interested in a workaround to use custom data types with bake fixtures: 

Add your custom data type (e.g. `mycustomtype` which should be a `BINARY(16)`) in `cake/vendor/cakephp/cakephp/src/Database/Schema/TableSchemaInterface.php`:

```
/**
 * My custom data type
 *
 * @var string
 */
const TYPE_MY_CUSTOM_TYPE = 'mycustomtype';
```

If you use MySQL, add in `cake/vendor/cakephp/cakephp/src/Database/Schema/MysqlSchema.php` into the function `columnSql()`:

```
...
TableSchema::TYPE_BIGINTEGER => ' BIGINT',
TableSchema::TYPE_BINARY_UUID => ' BINARY(16)',

TableSchema::TYPE_MY_CUSTOM_TYPE => ' BINARY(16)', // use mysql type BINARY(16)

TableSchema::TYPE_BOOLEAN => ' BOOLEAN',
TableSchema::TYPE_FLOAT => ' FLOAT',
TableSchema::TYPE_DECIMAL => ' DECIMAL',
...
```
If you use another database then edit the corresponding schema file. With these changes, bake will generate valid SQL for fixture creation.

Be careful: those changes will get lost if you update CakePHP. 

Still hoping that there will be an option in future CakePHP releases to define the database type in the custom data type.

**Comment by dereuromark** [comment]
We could try to look up based on the class, and otherwise just default to text or some default that will always work?
Better than failure maybe?

**Comment by bradmcnaughton** [comment]
For anyone trying @chrisch-hh 's solution for POINT or other geometry (with mysql) such as the one described in the cookbook (https://book.cakephp.org/4/en/orm/database-basics.html#mapping-custom-datatypes-to-sql-expressions)

Make the following changes:

Add to **TableSchemaInterface.php**

```
/**
 * Point data type
 *
 * @var string
 */
const TYPE_POINT = 'point';
```

Add to typeMap in **MysqlSchemaDialect.php** (note MysqlSchema deprecated and replaced with this in v 4.1+)

```
...
TableSchema::TYPE_POINT => ' POINT',
...
```

In your fixture file define the POINT value as a string containing the coordinates separated by a space. E.G. in LocationsFixture.php inside init()


```
$this->records = array(
        array('id' => '13683', 'locality' => 'ADELAIDE', 'coordinates' => '-34.932829,138.603813'),
);
```

**Comment by markstory** [comment]
@bradmcnaughton You shouldn't need to patch cakephp to add custom types. There are public APIs for all of that.

**Comment by bradmcnaughton** [comment]
Thanks @markstory, you're correct it looks like the issue I was having was just in the format of the coordinates/point data in the fixture file.

**Comment by dereuromark** [comment]
@markstory / others: Whats the current recommendation to resolve this?
Maybe I can take a look here.

**Comment by dereuromark** [comment]
But given that Bake is now not providing schema anymore, this seems to be more an issue for Migrations and Core.
Fixtures generated only contain data, so as long as that works, I guess we can also just close?
