### ISSUE TITLE
Add fixture namespace and `public $connection` based on `--connection` argument

### ISSUE THREAD

**Issue by mehov** [cakephp/bake#568]
What I'm doing: 
----

- `bin/cake bake fixture --connection=otherdb --records --count 100000 Users`
- `mv tests/fixture/UsersFixture.php tests/fixture/otherdb/UsersFixture.php`
- open `tests/fixture/otherdb/UsersFixture.php` and manually add:
  - `namespace App\Test\Fixture` → `namespace App\Test\Fixture\Otherdb`
  - `public $connection = 'test_otherdb';`

Doing this just once isn't a big deal, but I need to bake many fixtures and thought this experience could be improved.

What I'm suggesting:
----

Seeing that `--connection` is explicitly provided, it could be safe to presume it should be used for the fixture as well? I'd put the file into the corresponding location and make the above changes to the file right away. (Or at least ask the user.)

**Comment by markstory** [comment]
Including the `$connection` attribute in the fixture makes sense. We don't generally have a connection => namespace mapping convention though.

**Comment by ethanpooley** [comment]
+1 Ran into this when splitting a database, and it took me a while to figure out what the problem was.

**Comment by markstory** [comment]
> Are there any plans to implement this? I have 11 tables to bake, which isn't that much, but having a way to provide a subfolder and have everything else taken care of would have been convenient :)

Not at this point in time. Instead of subfolders you could use plugins that are part of your application. Failing that you could create your own model task that does what you need.

**Comment by mehov** [comment]
@markstory do you think it's actually a bad idea to prefix the table models this way? Not only I just spent quite some time moving the baked file and then editing the associations, then moving and editing the test fixtures, tables, entities, but I'm now also editing the actual table classes with `$this->setAlias()` and `$this->setEntityClass()`, and it finally feels like I'm fighting the framework, which is never a good sign. 

I've seen your point on using plugins, but except for the above this doesn't warrant a plugin (I guess), it's just a different datasource.

**Comment by markstory** [comment]
> do you think it's actually a bad idea to prefix the table models this way?

I don't understand why you would prefix tables. In the past it was an escape hatch for shared host environments where you had only one database and potentially multiple applications sharing that database. I don't think that is still a problem as hosting has gotten better.

**Comment by mehov** [comment]
I'm sorry, I probably should have clarified better. This isn't because I'm prefixing the table names like I would on some shared host in 2008.

My application uses several data sources (each of those being a separate database where yes, I can name the tables in any way I want). So a data source for general application DB, a datasource for analytics data, a datasource for an external CMS-powered website I'm integrating into.

I believed sorting the models into corresponding folders (so e.g. `Model/Table/Analytics/ReportTable.php`) instead of dumping them all into one shared folder would keep the application structure cleaner. But I may be wrong here.

**Comment by ADmad** [comment]
Use plugins, period. Based on your example you would have an `Analytics` plugin, `Wordpress` plugin, etc.

**Comment by mehov** [comment]
Thank you @markstory and @ADmad, I have revisited the plugin idea, and you were right, that seems like the *way* to go. It's also a step towards future-proofing the setup, as I can at any point add version control and reuse these internal plugins for our websites I may not know about yet. I guess the takeaway is: if you feel like you're fighting the framework, you probably are :)
