### ISSUE TITLE
Baked fixture decimal precision

### ISSUE THREAD

**Issue by mehov** [cakephp/bake#569]
What I did:
----

```
CREATE TABLE `prices` (
  `price` decimal(6,4) DEFAULT NULL,
  /* ... */
```
```
INSERT INTO `prices` VALUES (3.1920),(1.2000),(2.4000),(3.6000),(4.8000),(6.0000)
```
```
bin/cake bake fixture --records --count 100000 Prices
```
```
$this->records = [
    [
        'price' => 3.1920000000000002
    ],
    [
        'price' => 1.2
    ],
    [
        'price' => 2.3999999999999999
    ],
    [
        'price' => 3.6000000000000001
    ],
    [
        'price' => 4.7999999999999998
    ],
    [
        'price' => 6
    ],
];
```
Same table worked fine before, but once I re-imported the data from the above SQL file, I'm getting this inprecision. Previous imports worked as well. Is it something that can be improved on the bake's end?

I found cakephp/bake/issues/211 and cakephp/cakephp/issues/9522, seems close but not the case

**Comment by garas** [comment]
Output is generated by `var_export()`.

Precision is affected by [serialize_precision](https://www.php.net/manual/en/ini.core.php#ini.serialize-precision), try to use -1 value (enhanced algorithm, default from PHP 7.1).

**Comment by othercorey** [comment]
I think the only other solution is rounding and exporting as a string.

**Comment by othercorey** [comment]
CakePHP 4 maps decimal types to a string. To fix this for CakePHP 3, you have to override the DecimalType.
