### ISSUE TITLE
Annotate table associations using & Intersection

### ISSUE THREAD

**Issue by raul338** [cakephp/bake#573]
from dereuromark/cakephp-ide-helper#133

Maybe it should annotate like this
```php
/**
 * @property \App\Model\Table\BooksTable&\Cake\ORM\Association\HasMany $Books
 */
class AuthorsTable extends Table
{
    // ....
    $this->Books->link($book, [$author1, $author2]);
}
```

With `|` phpstan throws that BooksTable does not have a method `link`, changing to intersection fixes that.

Maybe should it be the default for CakePHP 4.0 app?

**Comment by ADmad** [comment]
I don't think we need to wait till next major to improve annotations.

**Comment by raul338** [comment]
Then should I open a PR? Are there tests for annotations??

**Comment by markstory** [comment]
> Are there tests for annotations??

No there are not. We have snapshot tests for the code that bake generates though.

**Comment by raul338** [comment]
PR open
