### ISSUE TITLE
4.x - Bake plugins without routes.php

### ISSUE THREAD

**Issue by ADmad** [cakephp/bake#575]
Plugins generally have a small number of routes connected if at all, so a separate `routes.php` file isn't really necessary.

We can instead include the `routes()` method in baked `Plugin.php` with comment that one can setup their routes in that method.

**Comment by ADmad** [comment]
Could do the same for bootsrap too.

**Comment by saeideng** [comment]
we dont have bootstrap by default in plugin ,but yes empty method + calling parent `bootstrap()`

**Comment by ADmad** [comment]
Loading of routes and bootstrap for plugin's is identical. The respective methods in `BasePlugin` check for existence of either file and include if available.

My proposal is in baked Plugin.php the methods should be overridden and made empty with reasonable comment.

**Comment by markstory** [comment]
Closing as there is a pull request open where we can discuss further.
