### ISSUE TITLE
Annotate `@uses` for Controllers etc

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#577]
I would like to discuss https://github.com/dereuromark/cakephp-ide-helper/issues/132#issuecomment-515999335 also for bake.

```php
/**
 * @uses \App\Controller\EventsController
 */
class EventsControllerTest extends IntegrationTestCase {
```

It might be super useful also in general to have the controller annotated here, this way you can quick jump to it.
Apart from IDE discovery of usage for such magically invoked classes.

What do people think?

**Comment by markstory** [comment]
Sounds ok to me.

**Comment by dereuromark** [comment]
I think it mainly is relevant for the integration test case classes
- Controller
- Command

I implemented the IdeHelper update task here already: https://github.com/dereuromark/cakephp-ide-helper/pull/135
