### ISSUE TITLE
Integrate prefix option for 'bake all'

### ISSUE THREAD

**Issue by DSchalla** [cakephp/bake#58]
The bake plugin is missing the 'prefix' Option for bake all, I will implement that in an PR.

Just note that down that this is already taken and WIP.

**Comment by markstory** [comment]
Sounds great :+1:

**Comment by andtxr** [comment]
Going to send a pr soon.

**Comment by DSchalla** [comment]
@andtxr Thanks, since I had to pause the project where I needed this I totally forgot about it.

**Comment by andtxr** [comment]
:+1:

**Comment by dereuromark** [comment]
Closing as PR is now open.
