### ISSUE TITLE
Automatically add @property annotations to Tables

### ISSUE THREAD

**Issue by nrother** [cakephp/bake#59]
It would be nice if baked Table classes would have `@property` annotations for the associations they have, like this:
```php
/**
 * Entries Model
 *
 * @property \Cake\ORM\Association Users
 * @property \Cake\ORM\Association Jobs
 */
```
(The code above was in fact added by a PhpStorm inspection and is really usefull)

AFAIK this is already done for Controller so it should not be so hard to implement.

**Comment by josegonzalez** [comment]
Should that be the namespace?

**Comment by markstory** [comment]
@josegonzalez Yes as the association classes are part of CakePHP and proxy method to the table classes in many cases.

**Comment by ndm2** [comment]
I'm currently working on adding more hints, including table associations, but I'm a little busy and adding hints to entities and views will take some more time in order to be implemented properly. The table hints however are quite simple, and I could push them already in case anyone would like to see them rather sooner than later?

**Comment by markstory** [comment]
@ndm2 Having better hints can be an incremental process. Having more sooner is always nice as we do releases for bake reasonably frequently.

**Comment by ndm2** [comment]
@markstory Ok, cool, then I'll probably push it out little by little, as especially entity property hints are giving me a headache... do you think it's worth trying to take custom database types into account? I can't really think of a proper way to figure the datatypes that they accept for marshalling and for converting to PHP.

**Comment by markstory** [comment]
Lets start with the table properties and go from there. Entity hints will be hard, as will database types as they often are not connected for the first round of bake.
