### ISSUE TITLE
2.x: Add "check database structure" command to cake shell

### ISSUE THREAD

**Issue by LordSimal** [cakephp/bake#592]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.x

## The scenario

Lets image we have some database structure with multiple tables and some of these tables are connected via 1:1, 1:N or N:M connections.

Before we perform "cake bake" it would be awesome to let CakePHP check the current database structure for automatically detected joins.

### Something like:
Book has one Publisher
Publisher has many Stores (and therefore Stores belongs to Publisher)
Book has and belongs to many Authors

Additionally CakePHP could check, if all required tables and their fields are present.
And if not, notify the user about that.

Otherwise `cake bake model all`, `cake bake controller all` and `cake bake template all` would generate false code which doesn't work as intended. 

What are your thoughts about that?

**Comment by markstory** [comment]
Checking that the intended tables exist seems reasonable. It will not work when there are cross connection associations, but may save more pain than it causes.

**Comment by LordSimal** [comment]
Doesn't seem like this feature is much wanted/needed by any other community members^^

**Comment by othercorey** [comment]
> Doesn't seem like this feature is much wanted/needed by any other community members^^

I wouldn't say that.  There are not many vocal community members that review issues.  

I would suggest starting with something simple that can work with multiple database vendors (mysql, postgres, etc).  If that works, then you can verify more.

**Comment by othercorey** [comment]
Also, keep in mind this is something that needs to be maintained and must have unit tests.

If you cannot deliver complete unit tests, you might not want to take this on.

**Comment by LordSimal** [comment]
Just to make this clear:
I never intended to create this issue because I want to fix it myself.
As seen in the description of the issue I just wanted to discuss if and how we would implement this (probably) new feature.

**Comment by dereuromark** [comment]
I would love to see this. Please make this a plugin.
You can call it `RelationDetecter` or `DatabaseAnalyzer` or alike.

And from there you could then make also a visible table/graph, similar to what already was done in a way here: https://github.com/mamchenkov/CakePHP-GraphViz-Models
So best to consult in that repo with a fresh issue and either then make your own plugin or make this one shinier.

Closing then as out of scope for Bake plugin.

**Comment by dereuromark** [comment]
I actually want to see if I can make it work for Cake4 again:
https://github.com/dereuromark/cakephp-model-graph/pull/1

Feel free to help out here and lets push a shiny new feature.

**Comment by dereuromark** [comment]
I also wrote quite a few validation tasks in the past, e.g. some are here:
https://github.com/dereuromark/cakephp-setup/tree/master/src/Command
Maybe that could also be a point to collect validation commands for various important/useful topics.
