### ISSUE TITLE
4.x Empty layout templates created for `bin/cake bake mailer Ticket`

### ISSUE THREAD

**Issue by steinkel** [cakephp/bake#596]
* Using `cakephp/bake                          4.x-dev 1d28d25`

* Running `bin/cake bake mailer Ticket` produces
```
Creating file /var/virtual/cakefest2019/src/../templates/layout/email/html/ticket.php
Could not write to `/var/virtual/cakefest2019/src/../templates/layout/email/html/ticket.php`.


Creating file /var/virtual/cakefest2019/src/../templates/layout/email/text/ticket.php
Could not write to `/var/virtual/cakefest2019/src/../templates/layout/email/text/ticket.php`.


Creating file /var/virtual/cakefest2019/src/Mailer/TicketMailer.php
Wrote `/var/virtual/cakefest2019/src/Mailer/TicketMailer.php`

Baking test case for App\Mailer\TicketMailer ...

Creating file /var/virtual/cakefest2019/tests/TestCase/Mailer/TicketMailerTest.php
Wrote `/var/virtual/cakefest2019/tests/TestCase/Mailer/TicketMailerTest.php`
```

Note file path containing `..` causing issues writing the templates

**Comment by markstory** [comment]
This might be an OS specific thing. The `..` paths work ok on MacOS, but need to work everywhere :smile:

**Comment by steinkel** [comment]
In case it's useful, my environment is `zsh` latest on `Ubuntu 16.04.6 LTS`

**Comment by ADmad** [comment]
Strange, `..` in paths should work fine on any *nix system.

Could the issue be related to non existence of parent directory instead?

**Comment by saeideng** [comment]
this solved by a PR , no ?

**Comment by challgren** [comment]
No this is not solved. Its happening with 2.0.1

**Comment by saeideng** [comment]
@challgren could you open new issue ticket with details ?

**Comment by challgren** [comment]
Yep, didn't want to open a duplicate issue
