### ISSUE TITLE
SQLServer 2012, Bake Issue when Views present.

### ISSUE THREAD

**Issue by tgr0ss** [cakephp/bake#60]
When trying to bake a table in a SQL 2012 database that has table views it provides the following errors, this has been tested w/ deleting the view in question, which then provides an error w/ the next view down the list.   Also has been tested w/ exact db with the views deleted and no bake issues

015-03-23 21:07:04 Error: [Cake\Database\Exception] Cannot describe vwAccountsSummaryView. It has 0 columns.
Stack Trace:
#0 F:\xampp\htdocs\test\app\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(65): Cake\Database\Schema\Collection->describe('vwAccountsSumma...', Array)
#1 F:\xampp\htdocs\test\app\vendor\cakephp\cakephp\src\ORM\Table.php(422): Cake\Database\Schema\CachedCollection->describe('vwAccountsSumma...')
#2 F:\xampp\htdocs\test\app\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(286): Cake\ORM\Table->schema()
#3 F:\xampp\htdocs\test\app\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(202): Bake\Shell\Task\ModelTask->findHasMany(Object(Cake\ORM\Table), Array)
#4 F:\xampp\htdocs\test\app\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(109): Bake\Shell\Task\ModelTask->getAssociations(Object(Cake\ORM\Table))
#5 F:\xampp\htdocs\test\app\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(95): Bake\Shell\Task\ModelTask->bake('Sites')
#6 [internal function]: Bake\Shell\Task\ModelTask->main('sites')
#7 F:\xampp\htdocs\test\app\vendor\cakephp\cakephp\src\Console\Shell.php(387): call_user_func_array(Array, Array)
#8 F:\xampp\htdocs\test\app\vendor\cakephp\cakephp\src\Console\Shell.php(382): Cake\Console\Shell->runCommand(Array, false)
#9 F:\xampp\htdocs\test\app\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(200): Cake\Console\Shell->runCommand(Array, true)
#10 F:\xampp\htdocs\test\app\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(171): Cake\Console\ShellDispatcher->_dispatch()
#11 F:\xampp\htdocs\test\app\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(122): Cake\Console\ShellDispatcher->dispatch()
#12 F:\xampp\htdocs\test\app\bin\cake.php(20): Cake\Console\ShellDispatcher::run(Array)
#13 {main}

**Comment by markstory** [comment]
How are you calling bake when you hit this error? Are you trying to bake classes for the view?

**Comment by tgr0ss** [comment]
I am doing cake bake model [viewName]

**Comment by markstory** [comment]
By view I meant are you baking models for a database view?

**Comment by tgr0ss** [comment]
No i was baking a model for a Table on a MSSQL 2012 DB and the view is causing an error to occur, saying [view_name]. "it has 0 columns" .   If i go to bake a model for the actual view, the same error happens as well.   So to clarify, whether i'm baking a model for an actual table or a view, the same error happens which is directly related to there being a view present in the database, since I had no issues baking the same DB when it was mirrored and the views were removed from the db.

hope that helps.

**Comment by tgr0ss** [comment]
First error says:
Exception: Cannot describe [view_name]. it has 0 columns in app\vendor\cakephp\cakephp\src\Database\Schema\Collection.php, line98

**Comment by markstory** [comment]
Thanks, I suspect the views are being included in the list of 'tables' when it should not be.

**Comment by markstory** [comment]
Pull request up for cakephp/cakephp that fixes views being included in the list of 'tables'.

**Comment by tgr0ss** [comment]
Mark,   

In CakePHP 2.0 we were able to Bake models off Views, will this not be the case in 3?  And if so, should we treat them as models/entities if we're creating them manually?

**Comment by lorenzo** [comment]
@tgr0ss you can create manually, but you will need to manually specify the schema object for the table that maps to the view. We are looking into ways to improve this

**Comment by tgr0ss** [comment]
Thank you.

**Comment by markstory** [comment]
cakephp/cakephp#6501 is the current issue for improving schema reflection on SQLServer views.
