### ISSUE TITLE
Bake for Cakephp 4 Your PHP version must be equal or higher than 7.2.0

### ISSUE THREAD

**Issue by vnt** [cakephp/bake#601]
Hi,
I have a problem with CakePHP bake beta 4 and Mac OS X + MAMP PRO 5.5.1 or Xaamp 

./cake bake model user
PHP Fatal error: Your PHP version must be equal or higher than 7.2.0 to use  CakePHP. in /Sites/cake4/myapp/config/requirements.php on line 24
Fatal  error: Your PHP version must be equal or higher than 7.2.0 to use  CakePHP. in /Users/Sites/cake4/myapp/config/requirements.php on line 24

The PHP versions installed are:
1. Command line: PHP CLI and PHP Apache are the different module.php -v PHP 7.2.21 (cli) (built: Aug 14 2019 16:40:59) ( NTS ) 

2 Version in hosting profile: 
phpinfo() PHP Version 7.2.21

How can I do to use Bake for Cakephp 4?

Thanks a lot,
David

**Comment by markstory** [comment]
You need to use PHP > 7.2.0. That error only shows when PHP self reports its version as lower than 7.2.0. Perhaps the there is another PHP version on your system that is being picked up?

**Comment by saeideng** [comment]
make sure your php version is same in command line and your Apache
these can be different sometimes depends to your config 

also make sure this return true version `php -v` 
you can have different versions on your system but one of them uses in cake and it is `php` not other commands (by default ) 
make sure your main php points to 7.2 

also if your php 7.2 located in `/usr/bin/php7.2` (or other location) 
you can use bake like 
`/usr/bin/php7.2 bin/cake.php`
