### ISSUE TITLE
3.8.x & 4.x - bin/cake bake model PsUsers --tablePrefix Ps_ Error: Unknown option `tablePrefix`.

### ISSUE THREAD

**Issue by vnt** [cakephp/bake#605]
Hello,
I have a database where the tables have the prefix ps_.
I tried using —tablePrefix in the Bake options to remove the prefix. 

`bin/cake bake model PsUsers --tablePrefix Ps_`
Error: Unknown option `tablePrefix`.

`bin/cake bake --help`
Options:  --tablePrefix      Table prefix to be used in models.

Where am I wrong?
Thanks

**Comment by saeideng** [comment]
`tablePrefix` missing in `OptionParser`
I'll fix

**Comment by saeideng** [comment]
if you are using bake version 1.x (compatible with cake 3.x)
it exists 
https://github.com/cakephp/bake/blob/cbd9e01b5c77b5fbb9e10212e30749689a88eb29/src/Shell/BakeShell.php#L314
if not and you are using 2.x (compatible with cake 4.x) looks this is expected
https://github.com/cakephp/bake/blob/9af9764db7617b68c4a3dcfa7280929332a05d70/src/Command/ModelCommand.php#L47-L51


which bake are you using ?

**Comment by vnt** [comment]
I am using 2.x bake for 4.x cake

**Comment by saeideng** [comment]
in bake 1.x you had a shell that sets this variable for `modelTask` class
but now we dont have wrapper class to set `tablePrefix` for ModelCommand.php
one case could be extending the `ModelCommand` and set your table prefix 

why you need to table prefix when there is `table` option ?
it only works on current table not joined tables 

I dont know we need to support the `modelTask` option in bake 2.x or no  ( @markstory  )

but  maybe you could use like bellow example


```php
// src/Application.php
namespace App;

use Bake\Command\ModelCommand;
use Cake\Http\BaseApplication;

class Application extends BaseApplication
{
    public function console($commands)
    {
        // Add instance
        $model = new ModelCommand();
        $model->tablePrefix = 'Ps_';
        $commands->add('bake_prefix_model', $model);
        return $commands;
    }
}
```

run 
```
bin/cake bake_prefix_model PsUsers
```

**Comment by markstory** [comment]
We could reinstate the tablePrefix option if it is useful. I had assumed it wasn't as the ORM generally doesn't handle prefixes like the 2.x model layer did.

**Comment by vnt** [comment]
The TablePrefix option would be useful, thanks.

**Comment by vnt** [comment]
Hi Mark,
is there any news?
Have you reinstate the tablePrefix option?
Thanks a lot

**Comment by markstory** [comment]
>  is there any news?

No there isn't.

>  Have you reinstate the tablePrefix option in Bake for CakePHP 4?

No. The last attempt someone made encountered a number of edge cases that were not solvable and the changes were not merged.

**Comment by samqueiroz** [comment]
whoever has this doubt, use
bin/cake bake model Users --table ps_users

**Comment by ADmad** [comment]
Closing as the `tablePrefix` options isn't going to be added. One can use the `table` option instead of specify the full table name.
