### ISSUE TITLE
3.x: cleanup

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#607]
https://github.com/cakephp/bake/blob/master/src/Template/Bake/Template/login.twig#L22

Shouldnt this `<?= $this->Flash->render('auth') ?>` part be not necessary anymore in 3.x?
Afaik all flash goes by default to normal default one, right?

**Comment by markstory** [comment]
It depends on whether we're optimizing for the AuthComponent flow or the new plugin.

**Comment by dereuromark** [comment]
I mean according to https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/AuthComponent.php#L489-L492 there is no such key "auth" anymore for a long time afaik.
