### ISSUE TITLE
RFC: Class and method comment links for routing?

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#619]
## What?
I propose enhancing the bake plugin to include docblocks which link to the controller class and methods in the routing. Making it easier to click through from the routing to the relevant place in your code.

## Example
```php
/* @see \App\Controller\Api\CallsController::end() */
$routes->connect('/end/:id', ['controller' => 'Calls', 'action' => 'end'])
    ->setPass(['id'])
    ->setMethods(['patch']);
```

## Why?
I think this will improve the routing and make navigating the code much easier. This also helps sidestep the issue with the routing being primarily array based, which makes it hard for tooling to follow it based on the code.

This just adds a little human layer on top of those arrays. Inspired by the Symfony routing docblocks to some degree.

**Comment by dereuromark** [comment]
You could also make an IdeHelper enhancement for this, adding those also for existing code automatically.

**Comment by dereuromark** [comment]
Instead of `see` I would use `uses`. This way you have also bidirectional lookup.

**Comment by dereuromark** [comment]
Do you have any more concrete cases or ideas here?
Like what specifically should be done?
I would also argue that this should go first in IdeHelper, as there it can also benefit existing code, and then, possibly, get backported for freshly generated code.

**Comment by othercorey** [comment]
Closing due to lack of details. There isn't a routing template to update. Please open a PR with a specific idea or extend the IDE support as suggested.
