### ISSUE TITLE
2.0.1 Emtpy mailer layouts

### ISSUE THREAD

**Issue by challgren** [cakephp/bake#625]
When running `bin/cake bake mailer ContactUs` the following output occurs on a MacOS 10.14.6 running PHP 7.3.12 homebrew. The files output in templates/layout are empty.

```
bin/cake bake mailer ContactUs

Creating file /Users/challgren/Projects/TruePedigree/website-cake/templates/layout/email/html/contact_us.php
Could not write to `/Users/challgren/Projects/TruePedigree/website-cake/templates/layout/email/html/contact_us.php`.


Creating file /Users/challgren/Projects/TruePedigree/website-cake/templates/layout/email/text/contact_us.php
Could not write to `/Users/challgren/Projects/TruePedigree/website-cake/templates/layout/email/text/contact_us.php`.


Creating file /Users/challgren/Projects/TruePedigree/website-cake/src/Mailer/ContactUsMailer.php
Wrote `/Users/challgren/Projects/TruePedigree/website-cake/src/Mailer/ContactUsMailer.php`

Baking test case for App\Mailer\ContactUsMailer ...

Creating file /Users/challgren/Projects/TruePedigree/website-cake/tests/TestCase/Mailer/ContactUsMailerTest.php
Wrote `/Users/challgren/Projects/TruePedigree/website-cake/tests/TestCase/Mailer/ContactUsMailerTest.php`
```

**Comment by challgren** [comment]
Even attempting to overwrite them, the error occurs.

**Comment by saeideng** [comment]
looks error is only on `*/templates/*` files

**Comment by challgren** [comment]
That is correct sir

**Comment by ADmad** [comment]
It's a false error message. The file is created just fine but [this](https://github.com/cakephp/cakephp/blob/master/src/Console/ConsoleIo.php#L615) generates error since the file created is an empty file.

**Comment by ADmad** [comment]
I don't think created a new layout file for each mailer is even necessary.

**Comment by challgren** [comment]
Could it be creating the files in the wrong place? Because I noticed that `templates/email/html` and `templates/email/text` don't have any files in them.

**Comment by ADmad** [comment]
Creating empty files under `templates/email/html` and `templates/email/text` doesn't do much good either.

**Comment by ADmad** [comment]
Closing as related PR is open.
