### ISSUE TITLE
Confusing doc numbers

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#628]
https://book.cakephp.org/bake/1/en/development.html
https://book.cakephp.org/bake/2/en/development.html

It is super hard for users to know that those refer to cake3 and cake4.
Since we are not using a proper framework semver, we should at least highlight the matching major CakePHP version here in the header or very clearly in the first part of the docs IMO.

**Comment by markstory** [comment]
> Since we are not using a proper framework semver

What does this mean? Each library has its own semver numbering. I'm not aware of anything in semver saying related libraries need to have lockstep version numbers.

> we should at least highlight the matching major CakePHP version here in the header or very clearly in the first part of the docs IMO.

> we should at least highlight the matching major CakePHP version here in the header or very clearly in the first part of the docs IMO.

Would mentioning which version of CakePHP is compatible in the quickstart/install section help?

**Comment by dereuromark** [comment]
Framework semver isnt sth new :)
https://www.dereuromark.de/2016/01/29/developing-cakephp-3-plugins-its-fun/#framework-semantic-versioning. Afaik CakeDC used sth similar.
It means basically to keep the first plugin major always in sync with the core major.
As such, all those random numbers out there become more meaningful and cognitive load gets reduced. 
Right now it is chaos from like 10 different majors, and you never really know what they fit if you dont check the composer.json etc.

But that issue aside: Yes, we should mention that on each page directly, so people know what major CakePHP version they are looking at right now.

**Comment by ADmad** [comment]
The text "CakePHP Bake 2.x CookBook" could be updated to include cake version like "Bake 2.x (CakePHP 4.x) CookBook"

**Comment by garas** [comment]
Also CakePHP 3.x book links to https://book.cakephp.org/bake/ which redirects to https://book.cakephp.org/bake/2/en/index.html.

And _Back to CakePHP Cookbook_ links to https://book.cakephp.org/, Bake 1.x should link to CakePHP 3.x.

**Comment by dereuromark** [comment]
Also, the dropdown select in the navi could have the cake version in braces

    VERSION: 2.x 

to

    VERSION: 2.x  (CakePHP 4.x)

etc

**Comment by dereuromark** [comment]
We have the same issue for the other plugins, e.g. Auth ones.

**Comment by dereuromark** [comment]
Looks like there is little interest in clarifying this. Closing then.
