### ISSUE TITLE
[CakePHP 3.x] No way to Bake CommandHelpers

### ISSUE THREAD

**Issue by ravage84** [cakephp/bake#633]
It seems the CakePHP 3.x version of Bake does not allow one to bake [Command Helpers](https://book.cakephp.org/3/en/console-and-shells/input-output.html#command-helpers).

This should be added to ease the migration path to CakePHP 4.x (and 5.x, in which the shell part is removed).

**Comment by dereuromark** [comment]
Do you want to make a PR here?

**Comment by mentisy** [comment]
I'm thinking of making a PR for this. Since this is an enhancement, should it target the next minor version (`2.6.0`)? If so, is `2.next` the correct branch?
