### ISSUE TITLE
Cake 3.0 bake index template limits to first 7 fields

### ISSUE THREAD

**Issue by djamesfar** [cakephp/bake#65]
It took me hours to figure out why the eighth field of my users table wasn't showing up in index views.
Template/index.ctp  creates a Collection of fields, but chains on ->take(7) at the end to limit the list, presumably so index tables don't get too wide for screens.  Wouldn't it be better to show them all and offer an optional limit value, or better yet specify a list of fields to show/omit?  In 2.x you just went into the baked view and deleted any `<th>`'s and `<td>`'s you didn't want.  Now you have to pop the hood on the form template and discover and remove the hard-coded (7).  Good luck to newbies!
Either way, arbitrarily, and secretly, lopping off everything after the first 7 fields is not the friendliest Bake feature.

**Comment by lorenzo** [comment]
It is not, but is also extremely annoying having to remove all the fields. Do you have a suggestion of how this could be improved?

**Comment by djamesfar** [comment]
Make a bake template --columnsLimt command-line option or something, then call ->take($columnsLimit) in the form.ctp template.  Unless someone happens to copy the template files into their own plugin and dig through it, the average person will never find that.  
If you hard-code a value behind the scenes that changes the user's output, at the very least it should be mentioned in the documentation!

**Comment by josegonzalez** [comment]
@djamesfar no need for exclamation points, it reads as yelling :)

Would you be willing to come up with a pr for this? Sounds like a useful change - and there are likely other places where this is the case.

The other thing we can do is make this injectable from an event?

**Comment by lorenzo** [comment]
I like the idea :)

**Comment by lorenzo** [comment]
Maybe also an option for the columns to show? Like `--display-fields id,name,created`

**Comment by djamesfar** [comment]
Maybe have an array of excluded fields for indexes.  For example, I always modify the index template for the users table and test for $field==='password' (or alias) and skip it so it doesn't show.  If we could include of list of all fields to *exclude* rather than include, it might be a shorter list.

**Comment by lorenzo** [comment]
We could have both, I think it is a good idea

**Comment by djamesfar** [comment]
@josegonzalez  is there an example of injecting from an event elsewhere in the framework you could point me to?

**Comment by josegonzalez** [comment]
I did it heavily in the bootstrap_cli.php. [Here](http://josediazgonzalez.com/2014/12/03/customizing-bake-and-installing-plugins-with-cakephp-3/) is a blog post example.

**Comment by djamesfar** [comment]
Thanks, I'll check it out.

**Comment by josegonzalez** [comment]
Note: I'm not saying thats the best way, just that it would be nice to be able to inject via an event so that you can persist changes across bakes :)

**Comment by dereuromark** [comment]
You realize that I proposed something like that years ago for cake2.x? :)
I still use it in my bake templates as "scaffoldSkipFields" etc.
https://github.com/dereuromark/cakephp-setup/blob/master/Console/Templates/setup/views/index.ctp#L26-L32
This allows blacklisting certain fields via model that should not be included in the baked views to keep the amount of fields limited.

**Comment by markstory** [comment]
I like the list of fields idea. That seems like a simple way to cover most use cases. Would the list of fields also change the generated forms?

**Comment by djamesfar** [comment]
I like @lorenzo's suggestion of --display-fields "field1,field2," or to have options to both include or exclude, maybe --index-fields-exclude and --index-fields-include.  Might be a good idea to use the word 'index' so it is apparent you're not excluding/including in forms and views.

**Comment by djamesfar** [comment]
To @markstory's question, that would allow you to have an option --form-fields-exclude/include and --view-fields-exclude/include if you wanted to modify the fields list for forms and views.

**Comment by markstory** [comment]
Having separate options for read and write views could work well.

**Comment by josegonzalez** [comment]
I would hope we can share the arg names. `--fields` being anything, `--fields-read` being those that are read-only, and joining them meaning you get some are read/write and some are read only. If anyone wants ordering, it would need to be done explicitly via events, which is something we can doc?

**Comment by djamesfar** [comment]
While this has been labeled an enhancement, I believe the arbitrary limitation of 7 fields in the index is a bug.  I recommend while ideas are kicked around for a solution, the **->take(7)** should be removed from the template, so new adopters of CakePHP 3 don't pull their hair out trying to figure out what happened to their data.  Every time I upgrade all my Cake 3 installs to a newer minor version, I have to go in and remove that method in case I bake another view.


```
/vendor/cakephp/bake/src/Template/Bake/Template/index.ctp :

$fields = collection($fields)
    ->filter(function($field) use ($schema) {
        return !in_array($schema->columnType($field), ['binary', 'text']);
    })
    ->take(7);     <--- remove this
```

**Comment by dereuromark** [comment]
I agree that the default should be less strict, and (as I suggested) this should be configurable by each "baker" on his own what fields make sense and which don't. Just using the first 7 seldom works (tm).

**Comment by markstory** [comment]
@djamesfar You could create custom templates instead of modifying your vendor files.

The limit was put in place to try and address super wide HTML tables when you have wide database tables. I'm open to other solutions but generating visually ugly pages isn't a great option.

**Comment by ib-anurag-mishra** [comment]
I feel that we could show all columns as it was  before  in  bake process  of  cakephp 2.x/ 1.x
and it takes hardly  5 MINUTES TO REMOVE not required  columns. We could  remove  "not required" columns manually.

Also please pay attention that adding "new columns" (on list  page)  is harder  task than to  remove "not required" columns.

Thanks

**Comment by DSchalla** [comment]
Is there any reason to avoid adding a separate flag? Like --index-columns=7 while some value is default? I could implement that today and open a PR for discussion.

**Comment by lorenzo** [comment]
@DSchalla go ahead!
