### ISSUE TITLE
[2.next] Can't load plugin helper

### ISSUE THREAD

**Issue by geoidesic** [cakephp/bake#652]
I tried this: https://book.cakephp.org/bake/2/en/development.html
```
EventManager::instance()->on('Bake.initialize', function (Event $event) {
    $view = $event->getSubject();

    // In my bake templates, allow the use of the MySpecial helper
    $view->loadHelper('QuasarAdmin.Bake');

    // And add an $author variable so it's always available
    $view->set('author', 'Andy');
});
```
... placing it into the `Plugin::bootstrap` method (the docs are out of date, showing `bootstrap_cli.php` file).

But it doesn't load the plugin helper, instead it loads the standard helper:
`object(Bake\View\Helper\BakeHelper)`

[UPDATE]:
Looking at the View code from CakePHP [View](https://github.com/cakephp/cakephp/blob/ff47fda37dcf6ea476f61ee173659705b4252837/src/View/View.php#L1191) it seems to ignore the plugin entirely:
```
public function loadHelper(string $name, array $config = []): Helper
    {
        [, $class] = pluginSplit($name);
        $helpers = $this->helpers();

        return $this->{$class} = $helpers->load($name, $config);
    }
```
I tried this too:
```
$view->loadHelper('QuasarAdmin\View\Helper\Bake');
```
but errors:
```
Error: [Cake\View\Exception\MissingHelperException] Helper class QuasarAdmin\View\Helper\BakeHelper could not be found.
```

**Comment by jadb** [comment]
I never tried this, but here's a suggestion you might want to try:

```php
EventManager::instance()->on('Bake.initialize', function (Event $event) {
    $view = $event->getSubject();

    // In my bake templates, allow the use of the MySpecial helper
    $view->helpers()->unload('Bake')->load('QuasarAdmin.Bake');

    // And add an $author variable so it's always available
    $view->set('author', 'Andy');
});
```

I also can confirm that by looking at the `View` code you pasted, the plugin isn't being ignored.

**Comment by geoidesic** [comment]
Are you sure? Doesn't this `[, $class] = pluginSplit($name)` mean that it is ignoring the plugin segment of the name?
