### ISSUE TITLE
Baking model with non-integer id fields adds allowEmptyString() validator

### ISSUE THREAD

**Issue by othercorey** [cakephp/bake#676]
When baking a sessions model with a primary key of type `text`, you get a validator with:
```
->allowEmptyString('id', null, 'create')
```

I wonder if this is assuming a primary key named `id` is meant to be a serial or auto-increment type.

https://book.cakephp.org/4/en/development/sessions.html#database-sessions

**Comment by dereuromark** [comment]
Looks correct though in this case, no?

**Comment by othercorey** [comment]
The id shouldn't be empty when creating though. It's not auto-generated. Am I misreading that?

**Comment by dereuromark** [comment]
For patching yes. This happens afterwards.

**Comment by dereuromark** [comment]
In the case of session you might be right. It wouldnt be an issue though.

**Comment by othercorey** [comment]
I'm not concerned about sessions specifically. I just don't think that validation should be generated for a NOT NULL primary key id.

**Comment by dereuromark** [comment]
Primary key is usually generated after marshalling is complete (especially since you should not be able to inject it here), right before saving.
So I don't think this is a problem in general. And bake usually aims for normal use cases, not edge case (like session here).

**Comment by othercorey** [comment]
Alright, that's fair. People will have to follow up on their non-standard ids.
