### ISSUE TITLE
Example of creating a new Bake console command would be useful

### ISSUE THREAD

**Issue by ewbarnard** [cakephp/bake#677]
The Bake console can be awfully useful as a skeleton code generator, but it's difficult to figure out how to create a new Bake command. The difficulty is partly due to the transition from Shell commands to Console commands. At Jorge @steinkel suggestion I created a tutorial - it could be an additional page coming after the current "Extending Bake" page.

I placed it in a separate repo because I don't know what to do with the example code. I'm happy leave the sample code as my own repo, or have it incorporated.

The suggested tutorial is here https://github.com/ewbarnard/BakeSample. The tutorial is at https://github.com/ewbarnard/BakeSample/tree/master/docs/en and the sample code is at https://github.com/ewbarnard/BakeSample/tree/master/ValueObject.

The tutorial is ready to PR, subject to any suggestions for improvement. I'd like to demonstrate current best practice, whatever that might be. I did NOT include any tests, with the focus being on what to write as a minimal useful Bake command.

**Comment by markstory** [comment]
I think having a tutorial would be great! You could include the resulting command in the docs directly as that will make it simpler for the reader and for us to maintain in the future.

**Comment by dereuromark** [comment]
@ewbarnard Do you want to add some info here to the cake core docs?
