### ISSUE TITLE
can't bake table in schema other than public

### ISSUE THREAD

**Issue by pyrite357** [cakephp/bake#682]
Hi,

I tried inquiring about this on the CakePHP forums in discourse (https://discourse.cakephp.org/t/bake-w-specify-database-schema/7698). They said to open an issue here. I have a postgresql database with about 20 schemas. How can I bake models for schemas outside of public? I'm using CakePHP 4.0.6 and bake 2.1.0

**Comment by markstory** [comment]
>  How can I bake models for schemas outside of public? I'm using CakePHP 4.0.6 and bake 2.1.0

You'll need to have a separate 'connection' in your database configuration for each schema as we treat schemas as separate 'databases'. Once your model's are generated you can use `setTable('schema.table_name')` in the table configuration. This lets you avoid having to make multiple connections when your application is serving traffic.

**Comment by pyrite357** [comment]
@markstory is it possible to create a Cake model of a "database view" so that you can pass it to Cake's wonderful paginator? That way the view could absorb the complexities of my queries that span multiple schemas. That would solve all my problems, and is what I did in the Cake 2.x days. I switched from 2.x to 4.x, and my world came crashing down lol

p.s. I'll try your suggestion now, thank you so much for responding mark!

**Comment by ADmad** [comment]
> is it possible to create a Cake model of a "database view"

Yes you can.

**Comment by pyrite357** [comment]
@ADmad in 4.x? Since there are no models anymore sorta, would it just be a matter of making a custom table object, and then specifying the view somewhere in there? If not, can you point me in the right direction? I'm sorry that I've been unable to locate any working examples of this myself.

**Comment by ADmad** [comment]
Just create a Table class as usual and use `setTable()` method to set the view name. If you need further assistance please use one of the help forums.

**Comment by pyrite357** [comment]
> Just create a Table class as usual and use `setTable()` method to set the view name. If you need further assistance please use one of the help forums.

Thanks @ADmad , I had a feeling sooner or later someone would point out the need to move the discussion off the issue boards. I'll give it a go, and if I need more help, I'll make a post on discourse.

> You'll need to have a separate 'connection' in your database configuration for each schema as we treat schemas as separate 'databases'. Once your model's are generated you can use `setTable('schema.table_name')` in the table configuration. This lets you avoid having to make multiple connections when your application is serving traffic.

@markstory this is really good info, should we put this in the book for Bake? I had read the book beforehand and didn't see anything like that in there I don't think.

**Comment by markstory** [comment]
> should we put this in the book for Bake? I had read the book beforehand and didn't see anything like that in there I don't think.

Sure. Having it in the bake docs would be great.

**Comment by pyrite357** [comment]
Please don't close the issue yet, I found a way to bake these after all, but I'm testing now

**Comment by pyrite357** [comment]
I'm pretty ecstatic right now; I was able to bake not only a table in another schema, but I was also able to bake a postgresql view into a cake model, and then paginate it with cake! Thanks to coreytaylor on discourse for cluing me in. @othercorey 

Bake CakePHP 4.x Model from a non-public PostgreSQL Schema:
`bin/cake bake model --table "private.soitem" SoItem`

Bake CakePHP 4.x Model from a PostgreSQL database view:
`bin/cake bake model --table "public.v_inventory" FunModel`

**Comment by othercorey** [comment]
Glad to hear it.
