### ISSUE TITLE
bake --connection doesn't work for anything other than the 'default' database connection in CakePHP 4

### ISSUE THREAD

**Issue by andyfoote** [cakephp/bake#691]
This is a (multiple allowed):
bug

* CakePHP Version: 4.0.8
* Platform and Target: CentOS. Command line.

### What you did
As per https://stackoverflow.com/questions/62215177/cakephp-4-bake-wont-let-me-use-a-different-database-connection-to-default I have configured `config/app_local.php` so there are connections to 2 different databases on the same server: 

    'Datasources' => [

    'default' => [
        'host' => 'localhost',
        'username' => '***',
        'password' => '***',
        'database' => 'db1',
        'url' => env('DATABASE_URL', null),
    ],

    'interface_db' => [
        'host' => 'localhost',
        'username' => '***',
        'password' => '***',
        'database' => 'db2',
        'url' => env('DATABASE_URL', null),
    ]
    ]

When I `bake` using the `default` database, everything works fine. When I want to connect to the database defined in the `interface_db` Datasource key, it doesn't work.

    php bin/cake.php bake model -cinterface_db

Also tried:

    php bin/cake.php bake model --connection interface_db

Gives an error:

Error: [Cake\Datasource\Exception\MissingDatasourceConfigException] The datasource configuration "interface_db" was not found. in .../vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php on line 203

### What happened
The application gives an error so nothing is baked.

If I run the same command with the `default` connection:

     php bin/cake.php bake model 

or:

    bin/cake.php bake model --connection default

It works fine.

### What you expected to happen
It should work with any valid array key in Datasources when passed to `-c` or `--connection`.

This worked fine in CakePHP 3.x. This is my first 4.x project so I don't know if something has broken when it's been updated.

**Comment by andyfoote** [comment]
Further information:

    $ php -v
    PHP 7.3.18 (cli) (built: May 14 2020 18:24:56) ( NTS )

**Comment by markstory** [comment]
Are you sure that app_local.php is being loaded? That error generally means that Cake wasn't able to find the named connection.

**Comment by andyfoote** [comment]
> Are you sure that app_local.php is being loaded? 

How would that be the case if it can connect to the `default` database without any problems? Is anything required on the developers part to load it? Cake 3.x (and 2.x) reads it automatically. So yes I'm pretty sure it's being loaded.

**Comment by markstory** [comment]
I'm not able to reproduce this error. I defined an additional connection in `config/app.php` as

```php
        'other' => [
            'className' => Connection::class,
            'driver' => Sqlite::class,
            'database' => ROOT . '/data.sqlite',
        ],
```

Then created that database with `sqlite3 ./data.sqlite` and created the following table

```sql
sqlite> create table widgets (id integer not null auto_increment primary key, name varchar, created datetime);
```

Then I was able to generate models:

```bash
$ bin/cake bake model -c other widgets
One moment while associations are detected.

Baking table class for Widgets...

Creating file /Users/markstory/Sites/cake4app/src/Model/Table/WidgetsTable.php
Wrote `/Users/markstory/Sites/cake4app/src/Model/Table/WidgetsTable.php`

Baking entity class for Widget...

Creating file /Users/markstory/Sites/cake4app/src/Model/Entity/Widget.php
Wrote `/Users/markstory/Sites/cake4app/src/Model/Entity/Widget.php`
Deleted `/Users/markstory/Sites/cake4app/src/Model/Entity/.gitkeep`

Baking test fixture for Widgets...

Creating file /Users/markstory/Sites/cake4app/tests/Fixture/WidgetsFixture.php
Wrote `/Users/markstory/Sites/cake4app/tests/Fixture/WidgetsFixture.php`
Deleted `/Users/markstory/Sites/cake4app/tests/Fixture/.gitkeep`
Bake is detecting possible fixtures...

Baking test case for App\Model\Table\WidgetsTable ...

Creating file /Users/markstory/Sites/cake4app/tests/TestCase/Model/Table/WidgetsTableTest.php
Wrote `/Users/markstory/Sites/cake4app/tests/TestCase/Model/Table/WidgetsTableTest.php`
Done
```

How do I reproduce the problem you're having?

**Comment by andyfoote** [comment]
>  I defined an additional connection in `config/app.php` 

Do you mean `config/app_local.php`?

Unfortuantely I didn't have time for this to not work so downgraded to CakePHP 3.8 and everything worked fine.

If it works for you then it could be a user-error on my part. Although I know my `app_local.php` was deployed and readable as it could `bake` models on the `default` connection.

**Comment by markstory** [comment]
> Do you mean config/app_local.php?

No I meant `config/app.php`. The sandbox app I had setup didn't use `app_local.php`.

**Comment by M3Y3R** [comment]
I had a similar error.

I have created a Default-App over [oven.php](https://github.com/CakeDC/oven) and called it "testimonials". Next, i edit the Datasources-Values in app_local.php. So the Message in the Frontend `CakePHP is NOT able to connect to the database.` is hidden.

Now, when im using the [Bakery](https://bakery.cakephp.org/) like this:
`m3y3r@localhost:~/htdocs/testimonials$ php bin/cake.php bake all users`

The following error wil be shown:
`Exception: Connection to Mysql could not be established: SQLSTATE[HY000] [2002] No such file or directory`


My System:
Windows 10 with xampp and Ubuntu 20.04 LTS as Subsystem for Windows.

Php:
```
m3y3r@localhost:~/htdocs/testimonials$ php -v
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

MySQL:
```
m3y3r@localhost:~/htdocs/testimonials$ mysql -V
mysql  Ver 8.0.20-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
```

**Comment by markstory** [comment]
@M3Y3R This sounds like CakePHP or your CLI environment cannot connect to your database at all. Are you able to make any queries tests or other commands?

**Comment by M3Y3R** [comment]
@markstory you are right.

After a long search I was able to find out the following:
As already mentioned, I use Windows 10 with Ubuntu 20.04 LTS as a subsystem. There are rumors about an error in connection with "localhost" ... You should use the IP 127.0.0.1 instead.

Then the bakery works well ...
