### ISSUE TITLE
Need help with bake in cakephp v 3.5

### ISSUE THREAD

**Issue by sgs2007** [cakephp/bake#696]
I want to create my own theme for bake test. All information what I found in cakephp doc was ( If you wish to modify the default output produced by the “bake” command, you can create your own bake templates in your application. This way does not use the --theme option in the command line when baking. The best way to do this is:

Create a new directory /src/Template/Bake/.
Copy any templates you want to override from vendor/cakephp/bake/src/Template/Bake/ to matching files in your application)

But I can understand this one -  Create a new directory /src/Template/Bake/ . What and How i should do it. Create folder for them or what, and how then use this them for baking test. Also if i want to use key --theme how or what I should passed there ( path to theme or only theme name) and where should I create this theme. Could some one help me.

**Comment by dereuromark** [comment]
See e.g. https://github.com/dereuromark/cakephp-setup/tree/cake3/src/Template/Bake as example
The plugin name becomes the theme usually.

**Comment by zsfoto** [comment]
Just for example: [https://github.com/maiconpinto/cakephp-adminlte-theme](https://github.com/maiconpinto/cakephp-adminlte-theme)
And add the line to bootstrap.php:
`Configure::write('Bake.theme', 'yout-plugin-for-your-theme');`

Or:
If you wait a little bit, I make an own plugin with own template. Now that is a private project in github. When I'll be finish the version 1.0, I'll change the visibility, public.

**Comment by sgs2007** [comment]
> Just for example: https://github.com/maiconpinto/cakephp-adminlte-theme
> And add the line to bootstrap.php:
> `Configure::write('Bake.theme', 'yout-plugin-for-your-theme');`
> 
> Or:
> If you wait a little bit, I make an own plugin with own template. Now that is a private project in github. When I'll be finish the version 1.0, I'll change the visibility, public.
Thx you for help....

**Comment by sgs2007** [comment]
Thx for help.

**Comment by ADmad** [comment]
If you still need assistance you can use one of our help forums.
