### ISSUE TITLE
"extending bake" instructions reference deprecated SimpleBakeTask

### ISSUE THREAD

**Issue by ewbarnard** [cakephp/bake#704]
The current "Extending Bake - 2.x" online documentation <https://book.cakephp.org/bake/2/en/development.html> describes using the deprecated "Shell" classes rather than the current "Command" classes in the section "Creating New Bake Command Options". The documentation fix requires more than just swapping class names; the "Command" approach is slightly different from the "Shell" approach.

**Do you want to address this issue?**

I will be happy to create a documentation PR once I figure out the process. It looks like I need to figure out the documentation-build process to ensure it's a clean PR. I'm currently following instructions to create myself a new bake command (code generator) with CakePHP 4.x / bake 2.x.

**Comment by dereuromark** [comment]
ping @ewbarnard 
anything left to be done or can we close?

**Comment by ewbarnard** [comment]
Mark, you can close. I was going to do more but never got it finished. Thanks for checking - I forgot this was still open! @dereuromark
