### ISSUE TITLE
Possibility to add an addedit-Template to bake all

### ISSUE THREAD

**Issue by majaMH** [cakephp/bake#713]
I often have exactly same template-Files for add and edit. 

Changes have to be done in both template Files...

Is there a possibility to add an addedit template for ControllerActions add and edit at bake all?

In Controller action add and edit has to be a render Command at last. So that this Actions take template addedit

**Comment by dereuromark** [comment]
You can use a common element in both if you want to.
Or rewrite one of the actions to use the other's template.

Both can be handled as custom bake template probably.

**Comment by othercorey** [comment]
This seems like something users could generate on their own. I'm not sure we'll be able to accommodate all users needs if they have a combined add/edit view.
