### ISSUE TITLE
Do not bake password or hidden fields

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#717]
Right now, bake template also adds hidden fields and the field password into index and view templates:

> Password | $2y$10$gB6bNUibyAgahzdnm7ZVje2/SZAmzYnOJher2xdSorDgCPUwcGfwx

I think we should exclude the list of hidden fields and the specific field "password" here from being auto generated into the templates.

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password',
    ];

What do you think?

Personally, I always display a boolean value instead (Yes, No) as "Is Password Set" for password field.
But I think people can still easily add that part back in.

**Comment by markstory** [comment]
I think omitting fields that are hidden in the entities makes sense.
