### ISSUE TITLE
Decouple the migration actions from the shell

### ISSUE THREAD

**Issue by burzum** [cakephp/bake#72]
There seems to be no simple way that would allow me to run migrations via code?

For example, I have a plugin installer and want to run the migrations not using the shell but inside my plugin managers code. I've spent some time on trying to figure out how to do it but there seems to be a lot code around Phinx acting as a wrapper for setting up the connection between Cake and Phinx. 

It would be nice if the migrations plugin would be more abstract than tight coupled with the shell. For example allow me to do something like this:

```php
$migrations = new Migrations('connectionName');
$migrations->migrate(); // App migrations
$migrations->migrate('PluginName'); // Plugin migrations
$migrations->setConnection('otherConnection');
```

Right now the Phinx code is totally interwoven with the Shell code.

**Comment by markstory** [comment]
Does phinx not provide anything we could use either?

**Comment by lorenzo** [comment]
it does, I made @burzum aware of it already

**Comment by burzum** [comment]
@lorenzo you should paste the links here for reference. But I disagree with what you said to some amount because they just did a wrapper around their shell implementation as well.

I think the better starting point is here: https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Migration/Manager.php

I need to try it when I have time to come back to it, got another task in my way. I think I can construct the config using the code from the migrations plugin and the Manager class.

However, this would mean we could re-use that code within the migration plugin. Also I doubt that Phinx is already capable of finding my plugins migrations for me like I proposed:

```php
$migrations->migrate(); // App migrations
$migrations->migrate('PluginName'); // Plugin migrations
```

**Comment by lorenzo** [comment]
Here is their implementation of web-based migrations https://github.com/robmorgan/phinx/blob/0.4.x-dev/app/web.php

**Comment by markstory** [comment]
So isn't this a bit moot then?

**Comment by burzum** [comment]
@lorenzo you don't need most of that code. I'be been right and the manager is a good entry point, check this code: https://gist.github.com/burzum/d3e244450826532a1fe2

```php
		$migrations = new \App\Utility\Migrations();
		debug($migrations->migrate('default'));
		debug($migrations->getStatus());
		debug($migrations->getOutput());
```` 

The output of this is 

```
 Status  Migration ID    Migration Name 
-----------------------------------------
     up  20141211174322  InitialMigration
     up  20150212164322  CategoriesAndStatuses
     up  20150413151209  Testing
```

migrate() is actually executed as well but for whatever reason the phinx libs method doesn't return anything nor does it write something to the console output, no idea why, seems pretty silly to me. I might create an issue ticket in their tracker and proposing that the manager methods should return something.

**Comment by josegonzalez** [comment]
Closing as this belongs in the [migrations](https://github.com/cakephp/migrations) plugin and was implemented [here](https://github.com/cakephp/migrations/releases/tag/1.2).
