### ISSUE TITLE
RFC: Show notice when column names detected with reserved keywords

### ISSUE THREAD

**Issue by LordSimal** [cakephp/bake#720]
Recently I had issues getting my code work with a table which had a column named `key`

Reason behind that name was, that I wanted to create a software key/licence management.

Basically after some hours of debugging and asking the Slack support channel someone there explained to me, that `key` is a reserved keyword in MySQL and therefore basically a bad name for that column.

See https://dev.mysql.com/doc/refman/5.7/en/keywords.html

Since there are quite the amount of reserved keywords it would be nice if `bin/console bake` would somehow inform the user of this issue.

Any opinions on that?

Of course the list from above only contains the keywords from MySQL 5.7, there will probably be others in PostgreSQL and/or SQLite

**Comment by othercorey** [comment]
> Of course the list from above only contains the keywords from MySQL 5.7, there will probably be others in PostgreSQL and/or SQLite

This is the problem. It's a large list with different rules for each db. I think it's reasonable that the developer doesn't use invalid column names.

**Comment by ADmad** [comment]
The list of keywords and reserved words for the various dbs is huge. It's not practical to maintain such a list of in the bake plugin.

**Comment by LordSimal** [comment]
I guessed it would be like that.
But is there any other way to help users with "bad database design choices"?

**Comment by othercorey** [comment]
Once the db has the table or column name, there isn't much we can do other than run the SQL and see if it fails.

**Comment by LordSimal** [comment]
I think there was once a discussion about adding a "check database structure" option for bake which checks your current database structure if there are detected CakePHP naming conventions.
I guess if/when something like that is being developed there could be some place to add this functionality as well.

**Comment by dereuromark** [comment]
I wonder if you could instead add a list to the docs of fields to watch out for
It should also mention that it isn't a complete extensive list, but the most common ones etc.

That should solve it without the need to support such full and long lists directly by the plugin for all DBs.
