### ISSUE TITLE
Create a bake theme not working

### ISSUE THREAD

**Issue by RiteshParyali** [cakephp/bake#735]
I had Tried .
https://book.cakephp.org/bake/2/en/development.html#creating-a-bake-theme
and 
https://book.cakephp.org/bake/2/en/development.html#creating-a-bake-theme
Both are not working,
Every times its using template from vendor folder,

Cakephp-Version - 4.2.1

**Comment by othercorey** [comment]
Explain what you did. How did you create the plugin? How did you run the bake command? What did you put in the theme?
