### ISSUE TITLE
Customizing controller.twig file still loads default when baking

### ISSUE THREAD

**Issue by connect232** [cakephp/bake#736]
Hi,
I have created a custom controller.twig file in the directory templates/bake/Controller.

However, the default controller.twig file is still being used when executing the bake command.

I have found changing $renderer->generate('Bake.Controller/controller) to $renderer->generate('Controller/controller) in vendor/cakephp/bake/src/Command/ControllerCommand.php, makes the command command load my custom controller.twig file.

Can someone advise if the "Bake." in $renderer->generate('Bake.Controller/controller) is needed for other things I am not aware of please?

**Comment by othercorey** [comment]
Please tell us what version of bake and where your controller.twig file is.

**Comment by connect232** [comment]
I am using version 2.3 of bake and I have created a custom controller.twig file in the directory templates/bake/Controller.

**Comment by markstory** [comment]
That template path should be working. I'll see if I can reproduce the problem of templates not being used for controllers.

**Comment by markstory** [comment]
Sorry @connect232 the documentation for application template overrides is wrong. I've opened a pull request to correct them.

**Comment by othercorey** [comment]
Closing this with the documentation changes.
