### ISSUE TITLE
docblock decimal mapped to string instead of float

### ISSUE THREAD

**Issue by gersonfs** [cakephp/bake#738]
Hello!

Is any reason for decimal column type mapped in docblock to string instead of float?
Cakephp also convert decimal columns in float properties;

I particularly edit all docblocks generated in entities from string to float in decimal fields as this reflects the type of data the entity contains.

Or is there a way for me to change this behavior in bake?

https://github.com/cakephp/bake/blob/master/src/View/Helper/DocBlockHelper.php#L181

Thanks!

**Comment by dereuromark** [comment]
What cakephp version are you using?

**Comment by garas** [comment]
See  https://github.com/cakephp/bake/pull/534.

**Comment by gersonfs** [comment]
> What cakephp version are you using?

I'm using 4.2.3 version. But I went to check it now and in fact it is no longer converted to float, but to string. Sorry.
For my purposes the ideal would be to convert decimal to float, since I use only 4 decimal places. Is it possible to do this in both CakePHP and Bake settings?

**Comment by dereuromark** [comment]
You can also use https://github.com/dereuromark/cakephp-decimal and avoid the mentioned float problems.

**Comment by garas** [comment]
You can set column type in table class:

```
class SomeTable extends Table
{
    protected function _initializeSchema(TableSchemaInterface $schema): TableSchemaInterface
    {
        $schema->setColumnType('colname', 'float');
        return $schema;
    }
}
```

**Comment by gersonfs** [comment]
Thanks for the explanation @dereuromark @garas
