### ISSUE TITLE
Baking plugin re-requires cake

### ISSUE THREAD

**Issue by choma** [cakephp/bake#74]
Baking a plugin creates a composer.json file that requires cakephp again, so we got cake downloaded inside plugin's vendor folder.
(Maybe I do not understand how this works, since I'm not a composer-expert, excuse me if this issue loses your time.)

**Comment by markstory** [comment]
The idea with plugin bake is that you would use it to create standalone plugins that you would later install with composer.

**Comment by jadb** [comment]
I think that it should be included in `require-dev` as it's necessary for testing but not in `require` since a plugin would already need to define it's `type` as `cakephp-plugin`.

**Comment by markstory** [comment]
@jadb That's fair.

**Comment by ceeram** [comment]
isnt the composer require also not about the cakephp version it requires?
You might otherwise end up installing the baked plugin in a 2.x application?


2015-04-15 17:26 GMT+02:00 Mark Story <notifications@github.com>:

**Comment by jadb** [comment]
@ceeram you have a good point but cake2 was never officially supported with composer anyways.

**Comment by rchavik** [comment]
@choma Did you run `composer install` in `APP` or the newly baked plugin directory?

I think you need to run in `APP`.

**Comment by ceeram** [comment]
@jadb ok maybe 2.x was not a good example. Then read as a plugin requiring
cakephp 3.1 loading in a 3.0 application. The point of require is to set
both required libraries and their versions. The vendors of a plugin would
normally not end up within a vendor folder in the plugin itself, unlesd you
run composer install in it.
Op 16 apr. 2015 16:21 schreef "Rachman Chavik" <notifications@github.com>:

**Comment by choma** [comment]
@rchavik I'm trying to develop a plugin, that uses a library installable via composer. So first I got cake via composer, then I baked the plugin. I modified the plugin composer.json to require the library I needed. I ran composer on app directory, but that (obviously?) didn't download the library. Then I ran composer in the plugin directory, and that worked, but it downloaded cake again.

I guess in these cases, we should manually remove cake from composer.json. I just think, in most cases we develop/install plugins that runs "inside" cake. And, if somebody is working on a standalone plugin, he maybe needs a composer custom installer anyway. (Again, maybe I'm wrong, since I'm composer-beginner)

**Comment by jadb** [comment]
@ceeram as I previously said, its a very good point. I started with removing it after being suggested by someone on the core to do so on my own plugins under https://github.com/gourmet - and stuck with that.

**Comment by ceeram** [comment]
@jadb i wonder why one would remove cakephp from a plugins require.

@choma composer should install all plugin/vendor libs requirements in the application vendor folder. Composer just does not scan changed composer.json files once installed. So either create a version of your plugin with the updated composer.json and then run composer update to replace the plugin with the new version or require the additional library in your application.

**Comment by ceeram** [comment]
Imo there is nothing to be changed here, and can close this ticket
