### ISSUE TITLE
Not loading custom templates first.

### ISSUE THREAD

**Issue by ulziibadrakh-p** [cakephp/bake#744]
CakePHP 4.2.5
PHP 8.0.2
Windows 10
Not loading my custom templates 
src/templates/bake/Template
src/templates/bake/element

When I rename vendor bake template directory  then its working fine.
![image](https://user-images.githubusercontent.com/169289/115097983-fa00d480-9f5f-11eb-9747-a42b0f2c01e5.png)

**Comment by othercorey** [comment]
Are you custom templates in your Application or in a plugin?

**Comment by othercorey** [comment]
If in your Application, put the templates into **templates/plugin/Bake**.

https://book.cakephp.org/bake/2/en/development.html#application-bake-templates

**Comment by ulziibadrakh-p** [comment]
Thank you it worked
