### ISSUE TITLE
bin/cake bake plugin generates composer.json with an invalid version constraint

### ISSUE THREAD

**Issue by mehov** [cakephp/bake#747]
What I did
==

```
bin/cake bake plugin -v PluginName
```

What I got
==

```
{
    "name": "your-name-here/plugin-name",

    "require": {
        "cakephp/cakephp": "&gt;4"
    },

}
```

What Is The Problem
==

> Loading composer repositories with package information
> [UnexpectedValueException]                                                
> Could not parse version constraint `&gt;4`: Invalid version string "`&gt;4`"

I guess the issue is in this file, but couldn't come up with a fix to suggest.

https://github.com/cakephp/bake/blob/0e679c7e426dc4fda6a91e5e2e2e4b56de5d1318/src/Command/PluginCommand.php#L186

**Comment by ADmad** [comment]
What does the version constraint for `cakephp/cakephp` in your app's `composer.json` look like?
