### ISSUE TITLE
Annotate `@uses` on test method level

### ISSUE THREAD

**Issue by mentisy** [cakephp/bake#755]
Previously discussed here: 
#577

Back then `@uses` was added at test controller class level. This is useful, but personally I'd like to also have them at method level. This way I can avoid having IDE yell at me about unused elements (methods etc.). This scenario occurs especially with controller actions and table find methods. If you only call finder methods through the ORM `find(string $type = 'all'...)` method, the custom methods won't have been called according to the IDE.

I'm not sure if @dereuromark covers this in his [cakephp-ide-helper](https://github.com/dereuromark/cakephp-ide-helper), maybe [PR #135](https://github.com/dereuromark/cakephp-ide-helper/pull/135), but adding it to the plugin code could be useful.

I have forked this repo and added a branch that adds `@uses \{{class}}::{{method}}()` to all test methods that bake generates. I will happily create a PR from my fork if this is something you'd like to implement.

Fork: https://github.com/cakephp/bake/compare/master...mentisy:uses-docblocks

Example of PostsController and index action:
```
/**
 * Test index method
 *
 * @return void
 * @uses \Bake\Test\App\Controller\PostsController::index()
 */
public function testIndex(): void
{
    $this->markTestIncomplete('Not implemented yet.');
}
```

**Comment by dereuromark** [comment]
Feel free to open the PR to discuss the details.

Yes, the IdeHelper already syncs it for existing code
But you are absolutely right that this should also be added to new files using bake plugin :)
