### ISSUE TITLE
Missing relationship docblock variables on `add` and `edit` templates

### ISSUE THREAD

**Issue by mentisy** [cakephp/bake#759]
When an `add` or `edit` template is generated, there's a docblock on top describing the outside variables, like `AppView` and the related entity.

## How it is:

It can look like this:
```php
<?php
/**
 * @var \Bake\Test\App\View\AppView $this
 * @var \App\Model\Entity\Author $author
 */
?>
```

When looking down at the generated form, you could have these form inputs:
```php
echo $this->Form->control('role_id', ['options' => $roles]);
echo $this->Form->control('name');
echo $this->Form->control('description');
```

In my IDE (PHPStorm), I will now get yelled at stating that `$roles` is undefined.

-----------------

## How it should be:

The Bake template should add these relationship variables to the generated template, so it looks like this

```php
<?php
/**
 * @var \Bake\Test\App\View\AppView $this
 * @var \App\Model\Entity\Author $author
 * @var array $roles
 */
?>
```

Now `$roles` is defined as an array, which it will be as the select box uses an array of key/value pairs.

--------------------------

## Suggested changes to fix issue

 I created a fork and a branch over here with suggested changed: https://github.com/cakephp/bake/compare/master...mentisy:association-variables-add-edit-templates?expand=1

**Comment by othercorey** [comment]
Can you create a PR with your changes?

**Comment by mentisy** [comment]
@othercorey See #761
