### ISSUE TITLE
StopException message not shown

### ISSUE THREAD

**Issue by raul338** [cakephp/bake#790]
Note: I don't know if this is a cakephp or bake bug.

When baking a fixture of tables that have columns name starting with underscore, it fails silently

```
$ bin/cake bake fixture ArosAcos
$
```

The exception is thrown in 

https://github.com/cakephp/bake/blob/cbeae91f35ee82656f76ee2f7aca9b0fba2c4768/src/Command/FixtureCommand.php#L220-L230

But the CommandRunner doesn't show the Exception Message

https://github.com/cakephp/cakephp/blob/101b179920a7b8ab68866554539d65c64c6bfd8d/src/Console/CommandRunner.php#L331-L338

I'm trying to bake fixture for [acl plugin](https://github.com/cakephp/acl/) that has a table `aros_acos` with `_create`, `_read`, `_update`, `_delete`columns.
Should the code be adapted to include such cases?

**Comment by othercorey** [comment]
Names starting with an underscore should be allowed when baking since they are valid php variable names.

@markstory Should we log separately or should stop exceptions be logged?

**Comment by markstory** [comment]
The silent `StopException` is because we no longer emit the error text of exceptions. I'll get that error showing up, and it looks like @othercorey has fixed the name validation. 

Nevermind, othercorey did all the work :clap::tada:
