### ISSUE TITLE
Number format helper displays NULL as 0

### ISSUE THREAD

**Issue by drtrppr** [cakephp/bake#807]
When baking an app, NULL-values are shown as a zero because of the use of the Number-helper:

$this->Number->format(null) gives the zero ([issue](https://github.com/cakephp/cakephp/issues/8961)).

When there's a NULL in the database, expect it to be displayed as a blank.

Added a test if field is NULL, and works like expected ([topic](https://discourse.cakephp.org/t/database-nullable-integer-field-has-value-null-cakephp-displaying-0/10082)).

**Comment by ADmad** [comment]
To resolve this the generated template code should be updated to call the NumberHelper only when the value is non-null.
