### ISSUE TITLE
Bake Template: make fileextension configurable

### ISSUE THREAD

**Issue by fabian-mcfly** [cakephp/bake#828]
Currently, the `php`-Extension for newly baked templates is hardcoded. Thus it's not possible to create other filetypes without overwriting the whole `TemplateCommand::bake` method.

https://github.com/cakephp/bake/blob/1c8a2d7b6a15f4bbc77bf15c5c780fbceb41de35/src/Command/TemplateCommand.php#L359

**Comment by othercorey** [comment]
What other extensions would you use?

**Comment by fabian-mcfly** [comment]
[Twig](https://github.com/cakephp/twig-view) for example.

**Comment by othercorey** [comment]
This will be configurable with `TemplateCommand::$ext` in 2.8.
