### ISSUE TITLE
Table with *_id column that isn't a foreign key doesn't generate validation

### ISSUE THREAD

**Issue by othercorey** [cakephp/bake#834]
When baking a model for a table with a column that "looks" like a foreign key such as `external_id` but has no target table, no validation is generated for the column. Instead an association to a non-existent model is generated.

After removing the invalid association, the user might not notice the validation is missing.

**Comment by ajibarra** [comment]
@othercorey Hi, I was trying to reproduce this bug using a table with a field `theme_id` and no themes table but the validation was generated correctly:

```
 $validator
            ->nonNegativeInteger('theme_id')
            ->requirePresence('theme_id', 'create')
            ->notEmptyString('theme_id');
```

Could you please provide more details about how to reproduce this bug? Please include Bake version and a DB schema if possible.

**Comment by dereuromark** [comment]
Is this still valid and reproducable?

**Comment by dereuromark** [comment]
Seems solved with https://github.com/cakephp/bake/pull/842 for now?
