### ISSUE TITLE
Primary key excluded from $_accessible array for has many relationship tables

### ISSUE THREAD

**Issue by othercorey** [cakephp/bake#835]
### Description

If you have a table such as `day_events` which has `day_id` and `created_at` as the primary key, these columns are excluded from the generated $_accessible array in the Entity.

The `created_at` column will also be missing from the validator config in the Table.

### Bake Version

2.7.0

**Comment by othercorey** [comment]
This seems to expect the primary key to be generated. However, for multi-column keys, that's probably not true.

Users can work around it by removing the primary key and introducing the individual constraints they represent.

**Comment by ajibarra** [comment]
@othercorey Hi, so your suggestion would be adding both columns to $_accessible for multi-column primary key?

**Comment by othercorey** [comment]
> @othercorey Hi, so your suggestion would be adding both columns to $_accessible for multi-column primary key?

Yes. For a complete solution, we should decide if a primary key could be autogenerated or not.

**Comment by dereuromark** [comment]
Not sure if we can provide a non-default (key) scenario here for bake?
Should we close this or is anyone interested in working this out?

**Comment by othercorey** [comment]
@ADmad thoughts?

**Comment by ADmad** [comment]
I don't see how bake can decide which columns of a primary key should be accessible and which shouldn't. I have never used multiple column PKs on a table with user editable records, so no idea what people's expectations are for setting the PK values for such cases.

I would just chalk this one up as beyond auto generation capabilities.
