### ISSUE TITLE
RFC: Do not generate associations for `_id` fields if no Table object or database table present

### ISSUE THREAD

**Issue by ajibarra** [cakephp/bake#839]
### Description

When baking a model, if you database table has a field with `_id` suffix it generates a belongsTo association. It is usually useful but sometimes it is not an actual association.

i.e A `users` table with an `external_id` to store the user id in another app/service.

Currently Bake would generate a belongsTo association with `Externals` as alias, even if ExternalsTable does not exist and `externals` table does not exist onto database.

I would propose to only generate the association if any of the above conditions is met.

I have a partial solution already but I would like to know your thoughts.

**Comment by othercorey** [comment]
This seems like https://github.com/cakephp/bake/issues/834

**Comment by ajibarra** [comment]
> This seems like #834

I have created this one after working on #834 . However I understood the problem in that one was about validation and not the association itself. Please let me know if I misunderstood.

Anyway I can prepare a PR this week to avoid creating associations to table that does not exist.

**Comment by othercorey** [comment]
The invalid association is a side-effect of the bug overall. However, removing an invalid association was simple compared to re-adding missing validation.
