### ISSUE TITLE
Advice needed - additional common actions for bake

### ISSUE THREAD

**Issue by imagra** [cakephp/bake#87]
What is better way to bake an additional common actions (like enable, moveup, movedown and etc.) additionally to index, view, add, edit, delete? Is there a trick that I have missed or proper way will be  modify CAKE/vendor/cakephp/bake/src/Shell/Task/ControllerTask.php by making branch?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
