### ISSUE TITLE
`--datasource` alias to `--connection` for consistency

### ISSUE THREAD

**Issue by mehov** [cakephp/bake#899]
### Description

The `bake` tool accepts the `--connection` argument choosing which database connection to use. These connections are defined [in the application's `config/app_local.php`](https://github.com/cakephp/app/blob/de208ea53390b9e392b30254b8d835e18260c5d6/config/app_local.example.php#L37), but as `Datasources`. 

Maybe it would be good for consistency to accept `--datasource` as an argument as well? Or at least when someone passes `--datasource`, make it say we should be using `--connection` - just like Git suggests the right argument when you make a typo.

When I relatively rarely need this, I keep trying `--datasource`, and every time it says *Error: Unknown option `datasource`*, so I have to go search what is the right one.

**Comment by ADmad** [comment]
> so I have to go search what is the right one.

You make it sound like a big chore when just using the `--help` option gives you the list of valid options with description for each command.

**Comment by ADmad** [comment]
The term `connection` is consistently used through the core's codebase and our docs. The `Table` class also has methods `setConnection()` and `setConnection()`. So `--connection` option is intuitive enough, there's no need to add an alias for it.
