### ISSUE TITLE
bake not override plugins bake template

### ISSUE THREAD

**Issue by tgoeminne** [cakephp/bake#922]
### Description

it would appear that bake is not following the standard way of overwriting a plugins template files.

eg you have bootstrapUi plugin andcwant to override its bake templates. Placing them in templates/plugin/BootstrapUI/bake/Template bake will ignore them?

### Bake Version

4.3

**Comment by othercorey** [comment]
@ADmad what is expected here?

**Comment by ADmad** [comment]
IDK. If there aren't any tests for it then I guess it's not supported/implemented.

**Comment by ndm2** [comment]
I've tried explaining it over at BootstrapUI, it's currently not supported, as theme templates are meant to trump all other templates.

https://github.com/FriendsOfCake/bootstrap-ui/issues/384#issuecomment-1546480322
