### ISSUE TITLE
 Return value of Bake\Command\ModelCommand::getDisplayField() must be of the type string or null, array returned in

### ISSUE THREAD

**Issue by latheefp** [cakephp/bake#926]
### Description

Getting error while baking a model related to mysql View. after upgrading to 4.4.14
`root@0b92294f1614:/var/www/html# ./bin/cake bake model campaign_views
One moment while associations are detected.
2023-06-02 16:02:03 error: [TypeError] Return value of Bake\Command\ModelCommand::getDisplayField() must be of the type string or null, array returned in /var/www/html/vendor/cakephp/bake/src/Command/ModelCommand.php on line 485
Stack Trace:
- /var/www/html/vendor/cakephp/bake/src/Command/ModelCommand.php:127
- /var/www/html/vendor/cakephp/bake/src/Command/ModelCommand.php:98
- /var/www/html/vendor/cakephp/bake/src/Command/ModelCommand.php:81
- /var/www/html/vendor/cakephp/cakephp/src/Console/BaseCommand.php:189
- /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /var/www/html/bin/cake.php:12`

Schema.

mysql> describe campaign_views;
+---------------+--------------+------+-----+---------+-------+
| Field         | Type         | Null | Key | Default | Extra |
+---------------+--------------+------+-----+---------+-------+
| id            | int          | NO   |     | 0       |       |
| campaign_name | varchar(128) | NO   |     | NULL    |       |
| start_date    | date         | NO   |     | NULL    |       |
| end_date      | date         | NO   |     | NULL    |       |
| created       | datetime     | NO   |     | NULL    |       |
| user_id       | int          | NO   |     | NULL    |       |
| template_id   | bigint       | NO   |     | NULL    |       |
| template      | varchar(64)  | YES  |     | NULL    |       |
| status        | varchar(16)  | YES  |     | NULL    |       |
| account_id    | int          | YES  |     | NULL    |       |
| company_name  | varchar(32)  | YES  |     | NULL    |       |
| user          | varchar(255) | YES  |     | NULL    |       |
+---------------+--------------+------+-----+---------+-------+
12 rows in set (0.00 sec)

### Bake Version

4.4.14

### PHP Version

PHP 7.4.33 (cli) (built: Nov 15 2022 06:03:30) ( NTS )

**Comment by othercorey** [comment]
What version bake is installed? The line numbers don't line up with latest.

You can find this in the composer.lock file.

**Comment by ajibarra** [comment]
Tried to reproduce using 4.4.14:

```
cakephp/bake                                   2.9.3                             Bake plugin for CakePHP
cakephp/cakephp                                4.4.14                            The CakePHP framework
```

Table:

```
create table db.campaign_views
(
    id            int auto_increment primary key,
    campaign_name varchar(128) not null,
    start_date    date         not null,
    end_date      date         not null,
    created       datetime     not null,
    user_id       int          not null,
    template_id   bigint       not null,
    template      varchar(64)  null,
    status        varchar(16)  null,
    account_id    int          null,
    company_name  varchar(32)  null,
    user          varchar(255) null
);
```
It runs successfully

```
./bin/cake bake model campaign_views
One moment while associations are detected.

Baking table class for CampaignViews...

Creating file /var/www/html/src/Model/Table/CampaignViewsTable.php
Wrote `/var/www/html/src/Model/Table/CampaignViewsTable.php`

Baking entity class for CampaignView...

Creating file /var/www/html/src/Model/Entity/CampaignView.php
Wrote `/var/www/html/src/Model/Entity/CampaignView.php`

Baking test fixture for CampaignViews...

Creating file /var/www/html/tests/Fixture/CampaignViewsFixture.php
Wrote `/var/www/html/tests/Fixture/CampaignViewsFixture.php`
Bake is detecting possible fixtures...

Baking test case for App\Model\Table\CampaignViewsTable ...

Creating file /var/www/html/tests/TestCase/Model/Table/CampaignViewsTableTest.php
Wrote `/var/www/html/tests/TestCase/Model/Table/CampaignViewsTableTest.php`
```

**Comment by othercorey** [comment]
@markstory Any ideas here?

**Comment by ndm2** [comment]
Last time this matched up with the given line numbers and return type hints was in version 2.5.2: https://github.com/cakephp/bake/blob/2.5.2/src/Command/ModelCommand.php#L485

This has been fixed quite some time ago in https://github.com/cakephp/bake/pull/766, so OP was probably using an outdated bake version.

**Comment by othercorey** [comment]
Thanks for checking!
