### ISSUE TITLE
Dont show deprecated validation rules

### ISSUE THREAD

**Issue by dereuromark** [cakephp/bake#93]
Refs https://github.com/cakephp/cakephp/issues/6581 and the deprecation of

- notEmpty (now notBlank)

And maybe also

- blank
- userDefined

as they would throw deprecation warnings now.

**Comment by markstory** [comment]
I can't find reference to these anywhere in the current bake code. Perhaps you are thinking of the interactive mode which doesn't exist in Cake3.

**Comment by dereuromark** [comment]
I was thinking that when working on 2.7 :) Good to know.
