### ISSUE TITLE
[3.x] Adaption to the new behavior of `EntityTrait::has()`

### ISSUE THREAD

**Issue by passchn** [cakephp/bake#931]
### Description

In CakePHP ^5.0, `EntityTrait::has()` will now return `true` if a property is `null`, see: https://github.com/cakephp/cakephp/pull/16847. 

This has implications on the template creation. E.g. in the Template/view.twig, contained fields on an Entity might be null, but the check for null is no longer present: 
https://github.com/cakephp/bake/blob/3.x/templates/bake/Template/view.twig#L62 

````php
<?= ${{ singularVar }}->has('{{ details.property }}') ? $this->Html->link(${{ singularVar }}->{{ details.property }}->{{ details.displayField }}, ['controller' => '{{ details.controller }}', 'action' => 'view', ${{ singularVar }}->{{ details.property }}->{{ details.primaryKey[0] }}]) : '' ?></td>
````

The Code above would try to get `null->{{ details.displayField }}`. 

There is a Method `hasValue()` on EntityTrait but I could not find out if this is the official alternative. 

### Bake Version

3.x

### PHP Version

8.1

**Comment by passchn** [comment]
Idea: For Templating, it would be nice to have helper methods  such as `Entity::hasNotNull()` or `Entity::hasMany()` etc. so that you know the property is not null or that it is an array.

**Comment by dereuromark** [comment]
You could make a PR to change it to hasValue()
https://github.com/cakephp/cakephp/blob/d833c71d3ef92d267225ae966f0c86c226309b42/src/Datasource/EntityTrait.php#L452
Since that is the easiest way out here for template usage of something that needs to be not empty.

**Comment by passchn** [comment]
I was unsure if this is the way to go or if this has other implications. But then this would be the solution :) It would also be great to name `hasValue()` as an alternative in the 5.x Migration guide.

**Comment by passchn** [comment]
I can make PRs for both later today or tomorrow. :)

**Comment by passchn** [comment]
Sorry for not actually making the PR. :D And thanks @LordSimal for fixing it :)
