### ISSUE TITLE
Cake Bake isn't working now?

### ISSUE THREAD

**Issue by chrisShick** [cakephp/bake#94]
So, I understand cakephp/bake has now been made into a plugin. I have the plugin installed, but running `bin/cake bake shell` command produces this error: 
````
Exception: Shell class for Bake could not be found.
````
If I try `bin/cake bake.bake` it recognizes the shell but then it throws all sorts of errors when I try to bake a model.

**Comment by markstory** [comment]
When did bake stop working? What sort of errors does it throw?

**Comment by dereuromark** [comment]
It works for me (and all others). So you must have some invalid setup. Pasting the exact error messages might help reproducing it.

**Comment by chrisShick** [comment]
I am sorry guys!! I had a very late night before and I was thinking quite clearly! It was a setup problem.

**Comment by daveozoalor** [comment]
I have the same problem @chrisShick  what was the solution?

**Comment by chrisShick** [comment]
@daveozoalor I did not install cakephp composer correctly. I rebaked the project and the problem went away.
