### ISSUE TITLE
Record properties don't match fields in FixtureTask

### ISSUE THREAD

**Issue by sean-nicholas** [cakephp/bake#97]
FixtureTask will create entities when using records from database: https://github.com/cakephp/bake/blob/master/src/Shell/Task/FixtureTask.php#L423-426

So $_hidden and $_virtual will be parsed and you get a record whose properties don't match the fields: 
> SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1

Maybe using hydrate(false) will help?

**Comment by lorenzo** [comment]
@markstory I created https://github.com/cakephp/cakephp/issues/6627

**Comment by markstory** [comment]
I'm too slow :smile:

**Comment by markstory** [comment]
Reopening as I think the code in bake needs to change too.

**Comment by markstory** [comment]
Pull request open now.
