### ISSUE TITLE
Records with datetime break Fixture

### ISSUE THREAD

**Issue by sean-nicholas** [cakephp/bake#98]
When using records from database in FixtureTask with a datetime field it will create following code:

```php
 public $records = [
        [
            ...
            'last_login' => Cake\I18n\Time::__set_state(array(
   'date' => '2015-02-05 12:58:15',
   'timezone_type' => 3,
   'timezone' => 'Europe/Berlin',
)),
...
```

Which results in 
> Parse error: syntax error, unexpected '(', expecting ']'

Maybe the records should be set in 
```php
public function init() {}
```
But the second problem is the namespace:

> Fatal error: Class 'App\Test\Fixture\Cake\I18n\Time' not found in tests\Fixture\UsersFixture.php on line 69

There is missing a blackslash before Cake\I18n\Time

**Comment by markstory** [comment]
Pull request open now.
