### ISSUE TITLE
Bake incorrectly uses enum->label() in view templates

### ISSUE THREAD

**Issue by markstory** [cakephp/bake#989]
### Description

I was baking templates for a model containing

```php
        $this->getSchema()->setColumnType('role', EnumType::from(MemberRoleEnum::class));
```
The `role` column is backed by a varchar column in the schema.

The related enum looks like

```php
namespace App\Model\Enum;

enum MemberRoleEnum: string
{
    case Member = 'member';
    case Manager = 'manager';
    case Owner = 'owner';
}
```
However, bake generates the following for the `view.php` template

```php
                <tr>
                    <th><?= __('Role') ?></th>
                <td><?= h($organizationMember->role-label()) ?></td>
                </tr>

```

Which isn't logically sound code. We could do better column type detection here and generate better code.

### Bake Version

3.1.1

### PHP Version

5.0.8

**Comment by ADmad** [comment]
Bake assumes that the enum used is generated using bake which adds the [label()](https://github.com/cakephp/bake/blob/3.x/templates/bake/Model/enum.twig#L34) method to the enum.

**Comment by dereuromark** [comment]
We could probably do a method exists check and use fallback if the method is not existing.

**Comment by dereuromark** [comment]
Or we check on EnumLabelInterface?
